// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/report/types/appender.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/report/types/appender.go -destination=report/types/appender.go -typed
//

// Package mock_types is a generated GoMock package.
package mock_types

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAppender is a mock of Appender interface.
type MockAppender struct {
	ctrl     *gomock.Controller
	recorder *MockAppenderMockRecorder
	isgomock struct{}
}

// MockAppenderMockRecorder is the mock recorder for MockAppender.
type MockAppenderMockRecorder struct {
	mock *MockAppender
}

// NewMockAppender creates a new mock instance.
func NewMockAppender(ctrl *gomock.Controller) *MockAppender {
	mock := &MockAppender{ctrl: ctrl}
	mock.recorder = &MockAppenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppender) EXPECT() *MockAppenderMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockAppender) Append(ctx context.Context, uid string, startAt int, lines []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, uid, startAt, lines)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockAppenderMockRecorder) Append(ctx, uid, startAt, lines any) *MockAppenderAppendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockAppender)(nil).Append), ctx, uid, startAt, lines)
	return &MockAppenderAppendCall{Call: call}
}

// MockAppenderAppendCall wrap *gomock.Call
type MockAppenderAppendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAppenderAppendCall) Return(arg0 error) *MockAppenderAppendCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAppenderAppendCall) Do(f func(context.Context, string, int, []string) error) *MockAppenderAppendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAppenderAppendCall) DoAndReturn(f func(context.Context, string, int, []string) error) *MockAppenderAppendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Close mocks base method.
func (m *MockAppender) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockAppenderMockRecorder) Close() *MockAppenderCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAppender)(nil).Close))
	return &MockAppenderCloseCall{Call: call}
}

// MockAppenderCloseCall wrap *gomock.Call
type MockAppenderCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAppenderCloseCall) Return(arg0 error) *MockAppenderCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAppenderCloseCall) Do(f func() error) *MockAppenderCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAppenderCloseCall) DoAndReturn(f func() error) *MockAppenderCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
