// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/report/types/conveyor.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/report/types/conveyor.go -destination=report/types/conveyor.go -typed
//

// Package mock_types is a generated GoMock package.
package mock_types

import (
	context "context"
	reflect "reflect"

	log "drassi.run/gha-runner/pkg/log"
	types "drassi.run/gha-runner/pkg/report/types"
	gomock "go.uber.org/mock/gomock"
)

// MockConveyor is a mock of Conveyor interface.
type MockConveyor struct {
	ctrl     *gomock.Controller
	recorder *MockConveyorMockRecorder
	isgomock struct{}
}

// MockConveyorMockRecorder is the mock recorder for MockConveyor.
type MockConveyorMockRecorder struct {
	mock *MockConveyor
}

// NewMockConveyor creates a new mock instance.
func NewMockConveyor(ctrl *gomock.Controller) *MockConveyor {
	mock := &MockConveyor{ctrl: ctrl}
	mock.recorder = &MockConveyorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConveyor) EXPECT() *MockConveyorMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConveyor) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockConveyorMockRecorder) Close() *MockConveyorCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConveyor)(nil).Close))
	return &MockConveyorCloseCall{Call: call}
}

// MockConveyorCloseCall wrap *gomock.Call
type MockConveyorCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConveyorCloseCall) Return(arg0 error) *MockConveyorCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConveyorCloseCall) Do(f func() error) *MockConveyorCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConveyorCloseCall) DoAndReturn(f func() error) *MockConveyorCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Run mocks base method.
func (m *MockConveyor) Run(ctx context.Context) (*types.Stat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(*types.Stat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockConveyorMockRecorder) Run(ctx any) *MockConveyorRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockConveyor)(nil).Run), ctx)
	return &MockConveyorRunCall{Call: call}
}

// MockConveyorRunCall wrap *gomock.Call
type MockConveyorRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConveyorRunCall) Return(arg0 *types.Stat, arg1 error) *MockConveyorRunCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConveyorRunCall) Do(f func(context.Context) (*types.Stat, error)) *MockConveyorRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConveyorRunCall) DoAndReturn(f func(context.Context) (*types.Stat, error)) *MockConveyorRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockConveyor) Update(u *log.Update) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", u)
}

// Update indicates an expected call of Update.
func (mr *MockConveyorMockRecorder) Update(u any) *MockConveyorUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConveyor)(nil).Update), u)
	return &MockConveyorUpdateCall{Call: call}
}

// MockConveyorUpdateCall wrap *gomock.Call
type MockConveyorUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConveyorUpdateCall) Return() *MockConveyorUpdateCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConveyorUpdateCall) Do(f func(*log.Update)) *MockConveyorUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConveyorUpdateCall) DoAndReturn(f func(*log.Update)) *MockConveyorUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
