// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/secret/masker.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/secret/masker.go -destination=executor/secret/masker.go -typed
//

// Package mock_secret is a generated GoMock package.
package mock_secret

import (
	reflect "reflect"

	secret "drassi.run/core/pkg/executor/secret"
	gomock "go.uber.org/mock/gomock"
)

// MockMasker is a mock of Masker interface.
type MockMasker struct {
	ctrl     *gomock.Controller
	recorder *MockMaskerMockRecorder
}

// MockMaskerMockRecorder is the mock recorder for MockMasker.
type MockMaskerMockRecorder struct {
	mock *MockMasker
}

// NewMockMasker creates a new mock instance.
func NewMockMasker(ctrl *gomock.Controller) *MockMasker {
	mock := &MockMasker{ctrl: ctrl}
	mock.recorder = &MockMaskerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMasker) EXPECT() *MockMaskerMockRecorder {
	return m.recorder
}

// AddSecret mocks base method.
func (m *MockMasker) AddSecret(secret secret.Secret) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddSecret", secret)
}

// AddSecret indicates an expected call of AddSecret.
func (mr *MockMaskerMockRecorder) AddSecret(secret any) *MockMaskerAddSecretCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSecret", reflect.TypeOf((*MockMasker)(nil).AddSecret), secret)
	return &MockMaskerAddSecretCall{Call: call}
}

// MockMaskerAddSecretCall wrap *gomock.Call
type MockMaskerAddSecretCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMaskerAddSecretCall) Return() *MockMaskerAddSecretCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMaskerAddSecretCall) Do(f func(secret.Secret)) *MockMaskerAddSecretCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMaskerAddSecretCall) DoAndReturn(f func(secret.Secret)) *MockMaskerAddSecretCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Mask mocks base method.
func (m *MockMasker) Mask(input string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mask", input)
	ret0, _ := ret[0].(string)
	return ret0
}

// Mask indicates an expected call of Mask.
func (mr *MockMaskerMockRecorder) Mask(input any) *MockMaskerMaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mask", reflect.TypeOf((*MockMasker)(nil).Mask), input)
	return &MockMaskerMaskCall{Call: call}
}

// MockMaskerMaskCall wrap *gomock.Call
type MockMaskerMaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMaskerMaskCall) Return(arg0 string) *MockMaskerMaskCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMaskerMaskCall) Do(f func(string) string) *MockMaskerMaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMaskerMaskCall) DoAndReturn(f func(string) string) *MockMaskerMaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
