//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GiteaRunner) DeepCopyInto(out *GiteaRunner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GiteaRunner.
func (in *GiteaRunner) DeepCopy() *GiteaRunner {
	if in == nil {
		return nil
	}
	out := new(GiteaRunner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GiteaRunner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GiteaRunnerSpec) DeepCopyInto(out *GiteaRunnerSpec) {
	*out = *in
	if in.RunnerLabels != nil {
		in, out := &in.RunnerLabels, &out.RunnerLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.SandboxerRef.DeepCopyInto(&out.SandboxerRef)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GiteaRunnerSpec.
func (in *GiteaRunnerSpec) DeepCopy() *GiteaRunnerSpec {
	if in == nil {
		return nil
	}
	out := new(GiteaRunnerSpec)
	in.DeepCopyInto(out)
	return out
}
