// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/report/job_service.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/report/job_service.go -destination=report/job_service.go -typed
//

// Package mock_report is a generated GoMock package.
package mock_report

import (
	reflect "reflect"

	logtypes "drassi.run/gha-runner/pkg/log/logtypes"
	timeline "drassi.run/gha-runner/pkg/timeline"
	gomock "go.uber.org/mock/gomock"
)

// MockJobService is a mock of JobService interface.
type MockJobService struct {
	ctrl     *gomock.Controller
	recorder *MockJobServiceMockRecorder
	isgomock struct{}
}

// MockJobServiceMockRecorder is the mock recorder for MockJobService.
type MockJobServiceMockRecorder struct {
	mock *MockJobService
}

// NewMockJobService creates a new mock instance.
func NewMockJobService(ctrl *gomock.Controller) *MockJobService {
	mock := &MockJobService{ctrl: ctrl}
	mock.recorder = &MockJobServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobService) EXPECT() *MockJobServiceMockRecorder {
	return m.recorder
}

// AttachmentUploader mocks base method.
func (m *MockJobService) AttachmentUploader(uid, kind, name string) logtypes.Uploader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachmentUploader", uid, kind, name)
	ret0, _ := ret[0].(logtypes.Uploader)
	return ret0
}

// AttachmentUploader indicates an expected call of AttachmentUploader.
func (mr *MockJobServiceMockRecorder) AttachmentUploader(uid, kind, name any) *MockJobServiceAttachmentUploaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachmentUploader", reflect.TypeOf((*MockJobService)(nil).AttachmentUploader), uid, kind, name)
	return &MockJobServiceAttachmentUploaderCall{Call: call}
}

// MockJobServiceAttachmentUploaderCall wrap *gomock.Call
type MockJobServiceAttachmentUploaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobServiceAttachmentUploaderCall) Return(arg0 logtypes.Uploader) *MockJobServiceAttachmentUploaderCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobServiceAttachmentUploaderCall) Do(f func(string, string, string) logtypes.Uploader) *MockJobServiceAttachmentUploaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobServiceAttachmentUploaderCall) DoAndReturn(f func(string, string, string) logtypes.Uploader) *MockJobServiceAttachmentUploaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LiveFeedAppender mocks base method.
func (m *MockJobService) LiveFeedAppender() logtypes.Appender {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LiveFeedAppender")
	ret0, _ := ret[0].(logtypes.Appender)
	return ret0
}

// LiveFeedAppender indicates an expected call of LiveFeedAppender.
func (mr *MockJobServiceMockRecorder) LiveFeedAppender() *MockJobServiceLiveFeedAppenderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LiveFeedAppender", reflect.TypeOf((*MockJobService)(nil).LiveFeedAppender))
	return &MockJobServiceLiveFeedAppenderCall{Call: call}
}

// MockJobServiceLiveFeedAppenderCall wrap *gomock.Call
type MockJobServiceLiveFeedAppenderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobServiceLiveFeedAppenderCall) Return(arg0 logtypes.Appender) *MockJobServiceLiveFeedAppenderCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobServiceLiveFeedAppenderCall) Do(f func() logtypes.Appender) *MockJobServiceLiveFeedAppenderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobServiceLiveFeedAppenderCall) DoAndReturn(f func() logtypes.Appender) *MockJobServiceLiveFeedAppenderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LogsUploader mocks base method.
func (m *MockJobService) LogsUploader(uid string) logtypes.Uploader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogsUploader", uid)
	ret0, _ := ret[0].(logtypes.Uploader)
	return ret0
}

// LogsUploader indicates an expected call of LogsUploader.
func (mr *MockJobServiceMockRecorder) LogsUploader(uid any) *MockJobServiceLogsUploaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogsUploader", reflect.TypeOf((*MockJobService)(nil).LogsUploader), uid)
	return &MockJobServiceLogsUploaderCall{Call: call}
}

// MockJobServiceLogsUploaderCall wrap *gomock.Call
type MockJobServiceLogsUploaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobServiceLogsUploaderCall) Return(arg0 logtypes.Uploader) *MockJobServiceLogsUploaderCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobServiceLogsUploaderCall) Do(f func(string) logtypes.Uploader) *MockJobServiceLogsUploaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobServiceLogsUploaderCall) DoAndReturn(f func(string) logtypes.Uploader) *MockJobServiceLogsUploaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TimelineRecorder mocks base method.
func (m *MockJobService) TimelineRecorder() timeline.Recorder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TimelineRecorder")
	ret0, _ := ret[0].(timeline.Recorder)
	return ret0
}

// TimelineRecorder indicates an expected call of TimelineRecorder.
func (mr *MockJobServiceMockRecorder) TimelineRecorder() *MockJobServiceTimelineRecorderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimelineRecorder", reflect.TypeOf((*MockJobService)(nil).TimelineRecorder))
	return &MockJobServiceTimelineRecorderCall{Call: call}
}

// MockJobServiceTimelineRecorderCall wrap *gomock.Call
type MockJobServiceTimelineRecorderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobServiceTimelineRecorderCall) Return(arg0 timeline.Recorder) *MockJobServiceTimelineRecorderCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobServiceTimelineRecorderCall) Do(f func() timeline.Recorder) *MockJobServiceTimelineRecorderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobServiceTimelineRecorderCall) DoAndReturn(f func() timeline.Recorder) *MockJobServiceTimelineRecorderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
