# SPDX-FileCopyrightText: (c) 2024 The Drassi Authors
#
# SPDX-License-Identifier: Apache-2.0

# https://golangci-lint.run/usage/linters/
# https://golangci-lint.run/usage/configuration/
linters:
  enable:
    - gofmt
    - govet

linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/spf13/pflag.FlagSet).SetAnnotation
      - (*github.com/spf13/pflag.FlagSet).MarkHidden
      - (*github.com/go-git/go-git/v5.Repository).DeleteBranch

issues:
  exclude-files:
    - _test\.go
