# https://golangci-lint.run/usage/linters/
# https://golangci-lint.run/usage/configuration/
linters:
  enable:
    - gofmt
    - govet

linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/spf13/pflag.FlagSet).SetAnnotation
      - (*github.com/spf13/pflag.FlagSet).MarkHidden
      - (*github.com/go-git/go-git/v5.Repository).DeleteBranch

issues:
  exclude-rules:
    - path: pkg/util/oauth2/clientcredentials/
      linters: [ staticcheck ]

    # not yet finished packages
    - path: pkg/container/
      linters: [ unused ]
    - path: pkg/sandboxer/
      linters: [ unused ]
    - path: pkg/executor/
      linters: [ unused ]

  exclude-files:
    - _test\.go
