# SPDX-FileCopyrightText: (c) 2024 The Drassi Authors
#
# SPDX-License-Identifier: Apache-2.0

exclude: |
  (?x)^(
    .*\.svg|
    .*\.excalidraw
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-toml
      - id: trailing-whitespace
        exclude_types: [ markdown ]
        exclude: |
          core/pkg/expression/grammar/.*.interp
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-symlinks
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
