# SPDX-FileCopyrightText: (c) 2024 The Drassi Authors
#
# SPDX-License-Identifier: Apache-2.0

# * https://spdx.github.io/spdx-spec/v2.3/file-tags/
# * https://spdx.dev/learn/handling-license-info/
# * https://reuse.software/spec-3.3/
inlineHeader = """
SPDX-FileCopyrightText: (c) {{props["inceptionYear"]}} {{props["copyrightOwner"]}}

SPDX-License-Identifier: {{props["license"]}}
"""

excludes = [
  "core/mock/**/*.go",
  "zz_generated.*.go"
]

[properties]
license = "Apache-2.0"
inceptionYear = 2024
copyrightOwner = "The Drassi Authors"
