// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/support/tracker.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/support/tracker.go -destination=executor/support/tracker.go -typed
//

// Package mock_support is a generated GoMock package.
package mock_support

import (
	context "context"
	io "io"
	reflect "reflect"

	support "drassi.run/core/pkg/executor/support"
	gomock "go.uber.org/mock/gomock"
)

// MockTracker is a mock of Tracker interface.
type MockTracker struct {
	ctrl     *gomock.Controller
	recorder *MockTrackerMockRecorder
	isgomock struct{}
}

// MockTrackerMockRecorder is the mock recorder for MockTracker.
type MockTrackerMockRecorder struct {
	mock *MockTracker
}

// NewMockTracker creates a new mock instance.
func NewMockTracker(ctrl *gomock.Controller) *MockTracker {
	mock := &MockTracker{ctrl: ctrl}
	mock.recorder = &MockTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracker) EXPECT() *MockTrackerMockRecorder {
	return m.recorder
}

// AddIssue mocks base method.
func (m *MockTracker) AddIssue(ctx context.Context, issue *support.Issue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIssue", ctx, issue)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIssue indicates an expected call of AddIssue.
func (mr *MockTrackerMockRecorder) AddIssue(ctx, issue any) *MockTrackerAddIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIssue", reflect.TypeOf((*MockTracker)(nil).AddIssue), ctx, issue)
	return &MockTrackerAddIssueCall{Call: call}
}

// MockTrackerAddIssueCall wrap *gomock.Call
type MockTrackerAddIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTrackerAddIssueCall) Return(arg0 error) *MockTrackerAddIssueCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTrackerAddIssueCall) Do(f func(context.Context, *support.Issue) error) *MockTrackerAddIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTrackerAddIssueCall) DoAndReturn(f func(context.Context, *support.Issue) error) *MockTrackerAddIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AttachFile mocks base method.
func (m *MockTracker) AttachFile(ctx context.Context, kind, name string, reader io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachFile", ctx, kind, name, reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachFile indicates an expected call of AttachFile.
func (mr *MockTrackerMockRecorder) AttachFile(ctx, kind, name, reader any) *MockTrackerAttachFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachFile", reflect.TypeOf((*MockTracker)(nil).AttachFile), ctx, kind, name, reader)
	return &MockTrackerAttachFileCall{Call: call}
}

// MockTrackerAttachFileCall wrap *gomock.Call
type MockTrackerAttachFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTrackerAttachFileCall) Return(arg0 error) *MockTrackerAttachFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTrackerAttachFileCall) Do(f func(context.Context, string, string, io.Reader) error) *MockTrackerAttachFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTrackerAttachFileCall) DoAndReturn(f func(context.Context, string, string, io.Reader) error) *MockTrackerAttachFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
