// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/command/cmdtypes/attach.go
//
// Generated by this command:
//
//	mockgen -typed -destination=command/cmdtypes/attach.go -source=../pkg/command/cmdtypes/attach.go
//

// Package mock_cmdtypes is a generated GoMock package.
package mock_cmdtypes

import (
	context "context"
	reflect "reflect"

	cmdtypes "drassi.run/core/pkg/command/cmdtypes"
	gomock "go.uber.org/mock/gomock"
)

// MockAttacher is a mock of Attacher interface.
type MockAttacher[R any] struct {
	ctrl     *gomock.Controller
	recorder *MockAttacherMockRecorder[R]
	isgomock struct{}
}

// MockAttacherMockRecorder is the mock recorder for MockAttacher.
type MockAttacherMockRecorder[R any] struct {
	mock *MockAttacher[R]
}

// NewMockAttacher creates a new mock instance.
func NewMockAttacher[R any](ctrl *gomock.Controller) *MockAttacher[R] {
	mock := &MockAttacher[R]{ctrl: ctrl}
	mock.recorder = &MockAttacherMockRecorder[R]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttacher[R]) EXPECT() *MockAttacherMockRecorder[R] {
	return m.recorder
}

// Upload mocks base method.
func (m *MockAttacher[R]) Upload(ctx context.Context, res R, attachment *cmdtypes.Attachment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, res, attachment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockAttacherMockRecorder[R]) Upload(ctx, res, attachment any) *MockAttacherUploadCall[R] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockAttacher[R])(nil).Upload), ctx, res, attachment)
	return &MockAttacherUploadCall[R]{Call: call}
}

// MockAttacherUploadCall wrap *gomock.Call
type MockAttacherUploadCall[R any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAttacherUploadCall[R]) Return(arg0 error) *MockAttacherUploadCall[R] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAttacherUploadCall[R]) Do(f func(context.Context, R, *cmdtypes.Attachment) error) *MockAttacherUploadCall[R] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAttacherUploadCall[R]) DoAndReturn(f func(context.Context, R, *cmdtypes.Attachment) error) *MockAttacherUploadCall[R] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
