// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/command/cmdtypes/types.go
//
// Generated by this command:
//
//	mockgen -typed -destination=command/cmdtypes/types.go -source=../pkg/command/cmdtypes/types.go
//

// Package mock_cmdtypes is a generated GoMock package.
package mock_cmdtypes

import (
	reflect "reflect"

	records "drassi.run/core/pkg/model/records"
	runtime "drassi.run/core/pkg/runtime"
	gomock "go.uber.org/mock/gomock"
)

// MockSupportAddPath is a mock of SupportAddPath interface.
type MockSupportAddPath struct {
	ctrl     *gomock.Controller
	recorder *MockSupportAddPathMockRecorder
	isgomock struct{}
}

// MockSupportAddPathMockRecorder is the mock recorder for MockSupportAddPath.
type MockSupportAddPathMockRecorder struct {
	mock *MockSupportAddPath
}

// NewMockSupportAddPath creates a new mock instance.
func NewMockSupportAddPath(ctrl *gomock.Controller) *MockSupportAddPath {
	mock := &MockSupportAddPath{ctrl: ctrl}
	mock.recorder = &MockSupportAddPathMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupportAddPath) EXPECT() *MockSupportAddPathMockRecorder {
	return m.recorder
}

// AddPath mocks base method.
func (m *MockSupportAddPath) AddPath(paths []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPath", paths)
}

// AddPath indicates an expected call of AddPath.
func (mr *MockSupportAddPathMockRecorder) AddPath(paths any) *MockSupportAddPathAddPathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPath", reflect.TypeOf((*MockSupportAddPath)(nil).AddPath), paths)
	return &MockSupportAddPathAddPathCall{Call: call}
}

// MockSupportAddPathAddPathCall wrap *gomock.Call
type MockSupportAddPathAddPathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSupportAddPathAddPathCall) Return() *MockSupportAddPathAddPathCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSupportAddPathAddPathCall) Do(f func([]string)) *MockSupportAddPathAddPathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSupportAddPathAddPathCall) DoAndReturn(f func([]string)) *MockSupportAddPathAddPathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSupportSetEnv is a mock of SupportSetEnv interface.
type MockSupportSetEnv struct {
	ctrl     *gomock.Controller
	recorder *MockSupportSetEnvMockRecorder
	isgomock struct{}
}

// MockSupportSetEnvMockRecorder is the mock recorder for MockSupportSetEnv.
type MockSupportSetEnvMockRecorder struct {
	mock *MockSupportSetEnv
}

// NewMockSupportSetEnv creates a new mock instance.
func NewMockSupportSetEnv(ctrl *gomock.Controller) *MockSupportSetEnv {
	mock := &MockSupportSetEnv{ctrl: ctrl}
	mock.recorder = &MockSupportSetEnvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupportSetEnv) EXPECT() *MockSupportSetEnvMockRecorder {
	return m.recorder
}

// SetEnv mocks base method.
func (m *MockSupportSetEnv) SetEnv(env map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEnv", env)
}

// SetEnv indicates an expected call of SetEnv.
func (mr *MockSupportSetEnvMockRecorder) SetEnv(env any) *MockSupportSetEnvSetEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnv", reflect.TypeOf((*MockSupportSetEnv)(nil).SetEnv), env)
	return &MockSupportSetEnvSetEnvCall{Call: call}
}

// MockSupportSetEnvSetEnvCall wrap *gomock.Call
type MockSupportSetEnvSetEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSupportSetEnvSetEnvCall) Return() *MockSupportSetEnvSetEnvCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSupportSetEnvSetEnvCall) Do(f func(map[string]string)) *MockSupportSetEnvSetEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSupportSetEnvSetEnvCall) DoAndReturn(f func(map[string]string)) *MockSupportSetEnvSetEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSupportSetOutput is a mock of SupportSetOutput interface.
type MockSupportSetOutput struct {
	ctrl     *gomock.Controller
	recorder *MockSupportSetOutputMockRecorder
	isgomock struct{}
}

// MockSupportSetOutputMockRecorder is the mock recorder for MockSupportSetOutput.
type MockSupportSetOutputMockRecorder struct {
	mock *MockSupportSetOutput
}

// NewMockSupportSetOutput creates a new mock instance.
func NewMockSupportSetOutput(ctrl *gomock.Controller) *MockSupportSetOutput {
	mock := &MockSupportSetOutput{ctrl: ctrl}
	mock.recorder = &MockSupportSetOutputMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupportSetOutput) EXPECT() *MockSupportSetOutputMockRecorder {
	return m.recorder
}

// SetOutput mocks base method.
func (m *MockSupportSetOutput) SetOutput(output map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOutput", output)
}

// SetOutput indicates an expected call of SetOutput.
func (mr *MockSupportSetOutputMockRecorder) SetOutput(output any) *MockSupportSetOutputSetOutputCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOutput", reflect.TypeOf((*MockSupportSetOutput)(nil).SetOutput), output)
	return &MockSupportSetOutputSetOutputCall{Call: call}
}

// MockSupportSetOutputSetOutputCall wrap *gomock.Call
type MockSupportSetOutputSetOutputCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSupportSetOutputSetOutputCall) Return() *MockSupportSetOutputSetOutputCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSupportSetOutputSetOutputCall) Do(f func(map[string]string)) *MockSupportSetOutputSetOutputCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSupportSetOutputSetOutputCall) DoAndReturn(f func(map[string]string)) *MockSupportSetOutputSetOutputCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSupportSaveState is a mock of SupportSaveState interface.
type MockSupportSaveState struct {
	ctrl     *gomock.Controller
	recorder *MockSupportSaveStateMockRecorder
	isgomock struct{}
}

// MockSupportSaveStateMockRecorder is the mock recorder for MockSupportSaveState.
type MockSupportSaveStateMockRecorder struct {
	mock *MockSupportSaveState
}

// NewMockSupportSaveState creates a new mock instance.
func NewMockSupportSaveState(ctrl *gomock.Controller) *MockSupportSaveState {
	mock := &MockSupportSaveState{ctrl: ctrl}
	mock.recorder = &MockSupportSaveStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupportSaveState) EXPECT() *MockSupportSaveStateMockRecorder {
	return m.recorder
}

// SaveState mocks base method.
func (m *MockSupportSaveState) SaveState(state map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveState", state)
}

// SaveState indicates an expected call of SaveState.
func (mr *MockSupportSaveStateMockRecorder) SaveState(state any) *MockSupportSaveStateSaveStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveState", reflect.TypeOf((*MockSupportSaveState)(nil).SaveState), state)
	return &MockSupportSaveStateSaveStateCall{Call: call}
}

// MockSupportSaveStateSaveStateCall wrap *gomock.Call
type MockSupportSaveStateSaveStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSupportSaveStateSaveStateCall) Return() *MockSupportSaveStateSaveStateCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSupportSaveStateSaveStateCall) Do(f func(map[string]string)) *MockSupportSaveStateSaveStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSupportSaveStateSaveStateCall) DoAndReturn(f func(map[string]string)) *MockSupportSaveStateSaveStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockHasPathTranslator is a mock of HasPathTranslator interface.
type MockHasPathTranslator struct {
	ctrl     *gomock.Controller
	recorder *MockHasPathTranslatorMockRecorder
	isgomock struct{}
}

// MockHasPathTranslatorMockRecorder is the mock recorder for MockHasPathTranslator.
type MockHasPathTranslatorMockRecorder struct {
	mock *MockHasPathTranslator
}

// NewMockHasPathTranslator creates a new mock instance.
func NewMockHasPathTranslator(ctrl *gomock.Controller) *MockHasPathTranslator {
	mock := &MockHasPathTranslator{ctrl: ctrl}
	mock.recorder = &MockHasPathTranslatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHasPathTranslator) EXPECT() *MockHasPathTranslatorMockRecorder {
	return m.recorder
}

// PathTranslator mocks base method.
func (m *MockHasPathTranslator) PathTranslator() runtime.PathTranslator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathTranslator")
	ret0, _ := ret[0].(runtime.PathTranslator)
	return ret0
}

// PathTranslator indicates an expected call of PathTranslator.
func (mr *MockHasPathTranslatorMockRecorder) PathTranslator() *MockHasPathTranslatorPathTranslatorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathTranslator", reflect.TypeOf((*MockHasPathTranslator)(nil).PathTranslator))
	return &MockHasPathTranslatorPathTranslatorCall{Call: call}
}

// MockHasPathTranslatorPathTranslatorCall wrap *gomock.Call
type MockHasPathTranslatorPathTranslatorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHasPathTranslatorPathTranslatorCall) Return(arg0 runtime.PathTranslator) *MockHasPathTranslatorPathTranslatorCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHasPathTranslatorPathTranslatorCall) Do(f func() runtime.PathTranslator) *MockHasPathTranslatorPathTranslatorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHasPathTranslatorPathTranslatorCall) DoAndReturn(f func() runtime.PathTranslator) *MockHasPathTranslatorPathTranslatorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockHasForge is a mock of HasForge interface.
type MockHasForge struct {
	ctrl     *gomock.Controller
	recorder *MockHasForgeMockRecorder
	isgomock struct{}
}

// MockHasForgeMockRecorder is the mock recorder for MockHasForge.
type MockHasForgeMockRecorder struct {
	mock *MockHasForge
}

// NewMockHasForge creates a new mock instance.
func NewMockHasForge(ctrl *gomock.Controller) *MockHasForge {
	mock := &MockHasForge{ctrl: ctrl}
	mock.recorder = &MockHasForgeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHasForge) EXPECT() *MockHasForgeMockRecorder {
	return m.recorder
}

// Forge mocks base method.
func (m *MockHasForge) Forge() *records.Forge {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Forge")
	ret0, _ := ret[0].(*records.Forge)
	return ret0
}

// Forge indicates an expected call of Forge.
func (mr *MockHasForgeMockRecorder) Forge() *MockHasForgeForgeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Forge", reflect.TypeOf((*MockHasForge)(nil).Forge))
	return &MockHasForgeForgeCall{Call: call}
}

// MockHasForgeForgeCall wrap *gomock.Call
type MockHasForgeForgeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHasForgeForgeCall) Return(arg0 *records.Forge) *MockHasForgeForgeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHasForgeForgeCall) Do(f func() *records.Forge) *MockHasForgeForgeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHasForgeForgeCall) DoAndReturn(f func() *records.Forge) *MockHasForgeForgeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
