// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/log/logtypes/types.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/log/logtypes/types.go -destination=log/logtypes/types.go -typed
//

// Package mock_logtypes is a generated GoMock package.
package mock_logtypes

import (
	context "context"
	reflect "reflect"

	log "drassi.run/gha-runner/pkg/log"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriber is a mock of Subscriber interface.
type MockSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriberMockRecorder
	isgomock struct{}
}

// MockSubscriberMockRecorder is the mock recorder for MockSubscriber.
type MockSubscriberMockRecorder struct {
	mock *MockSubscriber
}

// NewMockSubscriber creates a new mock instance.
func NewMockSubscriber(ctrl *gomock.Controller) *MockSubscriber {
	mock := &MockSubscriber{ctrl: ctrl}
	mock.recorder = &MockSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriber) EXPECT() *MockSubscriberMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockSubscriber) Run(ctx context.Context, ch <-chan *log.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx, ch)
}

// Run indicates an expected call of Run.
func (mr *MockSubscriberMockRecorder) Run(ctx, ch any) *MockSubscriberRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockSubscriber)(nil).Run), ctx, ch)
	return &MockSubscriberRunCall{Call: call}
}

// MockSubscriberRunCall wrap *gomock.Call
type MockSubscriberRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSubscriberRunCall) Return() *MockSubscriberRunCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSubscriberRunCall) Do(f func(context.Context, <-chan *log.Event)) *MockSubscriberRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSubscriberRunCall) DoAndReturn(f func(context.Context, <-chan *log.Event)) *MockSubscriberRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSignedUrlResponse is a mock of SignedUrlResponse interface.
type MockSignedUrlResponse struct {
	ctrl     *gomock.Controller
	recorder *MockSignedUrlResponseMockRecorder
	isgomock struct{}
}

// MockSignedUrlResponseMockRecorder is the mock recorder for MockSignedUrlResponse.
type MockSignedUrlResponseMockRecorder struct {
	mock *MockSignedUrlResponse
}

// NewMockSignedUrlResponse creates a new mock instance.
func NewMockSignedUrlResponse(ctrl *gomock.Controller) *MockSignedUrlResponse {
	mock := &MockSignedUrlResponse{ctrl: ctrl}
	mock.recorder = &MockSignedUrlResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignedUrlResponse) EXPECT() *MockSignedUrlResponseMockRecorder {
	return m.recorder
}

// GetStorageType mocks base method.
func (m *MockSignedUrlResponse) GetStorageType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetStorageType indicates an expected call of GetStorageType.
func (mr *MockSignedUrlResponseMockRecorder) GetStorageType() *MockSignedUrlResponseGetStorageTypeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageType", reflect.TypeOf((*MockSignedUrlResponse)(nil).GetStorageType))
	return &MockSignedUrlResponseGetStorageTypeCall{Call: call}
}

// MockSignedUrlResponseGetStorageTypeCall wrap *gomock.Call
type MockSignedUrlResponseGetStorageTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSignedUrlResponseGetStorageTypeCall) Return(arg0 string) *MockSignedUrlResponseGetStorageTypeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSignedUrlResponseGetStorageTypeCall) Do(f func() string) *MockSignedUrlResponseGetStorageTypeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSignedUrlResponseGetStorageTypeCall) DoAndReturn(f func() string) *MockSignedUrlResponseGetStorageTypeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUrl mocks base method.
func (m *MockSignedUrlResponse) GetUrl() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUrl")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUrl indicates an expected call of GetUrl.
func (mr *MockSignedUrlResponseMockRecorder) GetUrl() *MockSignedUrlResponseGetUrlCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUrl", reflect.TypeOf((*MockSignedUrlResponse)(nil).GetUrl))
	return &MockSignedUrlResponseGetUrlCall{Call: call}
}

// MockSignedUrlResponseGetUrlCall wrap *gomock.Call
type MockSignedUrlResponseGetUrlCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSignedUrlResponseGetUrlCall) Return(arg0 string) *MockSignedUrlResponseGetUrlCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSignedUrlResponseGetUrlCall) Do(f func() string) *MockSignedUrlResponseGetUrlCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSignedUrlResponseGetUrlCall) DoAndReturn(f func() string) *MockSignedUrlResponseGetUrlCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
