// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/log/logtypes/uploader.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/log/logtypes/uploader.go -destination=log/logtypes/uploader.go -typed
//

// Package mock_logtypes is a generated GoMock package.
package mock_logtypes

import (
	context "context"
	io "io"
	reflect "reflect"

	logtypes "drassi.run/gha-runner/pkg/log/logtypes"
	gomock "go.uber.org/mock/gomock"
)

// MockUploader is a mock of Uploader interface.
type MockUploader struct {
	ctrl     *gomock.Controller
	recorder *MockUploaderMockRecorder
	isgomock struct{}
}

// MockUploaderMockRecorder is the mock recorder for MockUploader.
type MockUploaderMockRecorder struct {
	mock *MockUploader
}

// NewMockUploader creates a new mock instance.
func NewMockUploader(ctrl *gomock.Controller) *MockUploader {
	mock := &MockUploader{ctrl: ctrl}
	mock.recorder = &MockUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploader) EXPECT() *MockUploaderMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockUploader) Upload(ctx context.Context, r io.Reader, stat *logtypes.Stat) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, r, stat)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockUploaderMockRecorder) Upload(ctx, r, stat any) *MockUploaderUploadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockUploader)(nil).Upload), ctx, r, stat)
	return &MockUploaderUploadCall{Call: call}
}

// MockUploaderUploadCall wrap *gomock.Call
type MockUploaderUploadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUploaderUploadCall) Return(arg0 error) *MockUploaderUploadCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUploaderUploadCall) Do(f func(context.Context, io.Reader, *logtypes.Stat) error) *MockUploaderUploadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUploaderUploadCall) DoAndReturn(f func(context.Context, io.Reader, *logtypes.Stat) error) *MockUploaderUploadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
