// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/container/engine.go
//
// Generated by this command:
//
//	mockgen -typed -destination=container/engine.go -source=../pkg/container/engine.go
//

// Package mock_container is a generated GoMock package.
package mock_container

import (
	context "context"
	io "io"
	fs "io/fs"
	reflect "reflect"

	container "drassi.run/core/pkg/container"
	types "drassi.run/core/pkg/container/types"
	gomock "go.uber.org/mock/gomock"
)

// MockEngine is a mock of Engine interface.
type MockEngine struct {
	ctrl     *gomock.Controller
	recorder *MockEngineMockRecorder
	isgomock struct{}
}

// MockEngineMockRecorder is the mock recorder for MockEngine.
type MockEngineMockRecorder struct {
	mock *MockEngine
}

// NewMockEngine creates a new mock instance.
func NewMockEngine(ctrl *gomock.Controller) *MockEngine {
	mock := &MockEngine{ctrl: ctrl}
	mock.recorder = &MockEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngine) EXPECT() *MockEngineMockRecorder {
	return m.recorder
}

// Address mocks base method.
func (m *MockEngine) Address() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Address")
	ret0, _ := ret[0].(string)
	return ret0
}

// Address indicates an expected call of Address.
func (mr *MockEngineMockRecorder) Address() *MockEngineAddressCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Address", reflect.TypeOf((*MockEngine)(nil).Address))
	return &MockEngineAddressCall{Call: call}
}

// MockEngineAddressCall wrap *gomock.Call
type MockEngineAddressCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineAddressCall) Return(arg0 string) *MockEngineAddressCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineAddressCall) Do(f func() string) *MockEngineAddressCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineAddressCall) DoAndReturn(f func() string) *MockEngineAddressCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Close mocks base method.
func (m *MockEngine) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEngineMockRecorder) Close() *MockEngineCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEngine)(nil).Close))
	return &MockEngineCloseCall{Call: call}
}

// MockEngineCloseCall wrap *gomock.Call
type MockEngineCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineCloseCall) Return(arg0 error) *MockEngineCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineCloseCall) Do(f func() error) *MockEngineCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineCloseCall) DoAndReturn(f func() error) *MockEngineCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ContainerExec mocks base method.
func (m *MockEngine) ContainerExec(ctx context.Context, id string, opts *container.ExecOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerExec", ctx, id, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerExec indicates an expected call of ContainerExec.
func (mr *MockEngineMockRecorder) ContainerExec(ctx, id, opts any) *MockEngineContainerExecCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerExec", reflect.TypeOf((*MockEngine)(nil).ContainerExec), ctx, id, opts)
	return &MockEngineContainerExecCall{Call: call}
}

// MockEngineContainerExecCall wrap *gomock.Call
type MockEngineContainerExecCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineContainerExecCall) Return(arg0 string, arg1 error) *MockEngineContainerExecCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineContainerExecCall) Do(f func(context.Context, string, *container.ExecOptions) (string, error)) *MockEngineContainerExecCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineContainerExecCall) DoAndReturn(f func(context.Context, string, *container.ExecOptions) (string, error)) *MockEngineContainerExecCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ContainerInspect mocks base method.
func (m *MockEngine) ContainerInspect(ctx context.Context, id string) (*types.ContainerSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerInspect", ctx, id)
	ret0, _ := ret[0].(*types.ContainerSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerInspect indicates an expected call of ContainerInspect.
func (mr *MockEngineMockRecorder) ContainerInspect(ctx, id any) *MockEngineContainerInspectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerInspect", reflect.TypeOf((*MockEngine)(nil).ContainerInspect), ctx, id)
	return &MockEngineContainerInspectCall{Call: call}
}

// MockEngineContainerInspectCall wrap *gomock.Call
type MockEngineContainerInspectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineContainerInspectCall) Return(arg0 *types.ContainerSpec, arg1 error) *MockEngineContainerInspectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineContainerInspectCall) Do(f func(context.Context, string) (*types.ContainerSpec, error)) *MockEngineContainerInspectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineContainerInspectCall) DoAndReturn(f func(context.Context, string) (*types.ContainerSpec, error)) *MockEngineContainerInspectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ContainerRemove mocks base method.
func (m *MockEngine) ContainerRemove(ctx context.Context, opts *container.RemoveOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerRemove", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ContainerRemove indicates an expected call of ContainerRemove.
func (mr *MockEngineMockRecorder) ContainerRemove(ctx, opts any) *MockEngineContainerRemoveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerRemove", reflect.TypeOf((*MockEngine)(nil).ContainerRemove), ctx, opts)
	return &MockEngineContainerRemoveCall{Call: call}
}

// MockEngineContainerRemoveCall wrap *gomock.Call
type MockEngineContainerRemoveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineContainerRemoveCall) Return(arg0 error) *MockEngineContainerRemoveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineContainerRemoveCall) Do(f func(context.Context, *container.RemoveOptions) error) *MockEngineContainerRemoveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineContainerRemoveCall) DoAndReturn(f func(context.Context, *container.RemoveOptions) error) *MockEngineContainerRemoveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ContainerRun mocks base method.
func (m *MockEngine) ContainerRun(ctx context.Context, spec *types.ContainerSpec, opts *container.RunOptions) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerRun", ctx, spec, opts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerRun indicates an expected call of ContainerRun.
func (mr *MockEngineMockRecorder) ContainerRun(ctx, spec, opts any) *MockEngineContainerRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerRun", reflect.TypeOf((*MockEngine)(nil).ContainerRun), ctx, spec, opts)
	return &MockEngineContainerRunCall{Call: call}
}

// MockEngineContainerRunCall wrap *gomock.Call
type MockEngineContainerRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineContainerRunCall) Return(arg0 string, arg1 error) *MockEngineContainerRunCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineContainerRunCall) Do(f func(context.Context, *types.ContainerSpec, *container.RunOptions) (string, error)) *MockEngineContainerRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineContainerRunCall) DoAndReturn(f func(context.Context, *types.ContainerSpec, *container.RunOptions) (string, error)) *MockEngineContainerRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CopyIn mocks base method.
func (m *MockEngine) CopyIn(ctx context.Context, id string, opts *container.CopyInOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyIn", ctx, id, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyIn indicates an expected call of CopyIn.
func (mr *MockEngineMockRecorder) CopyIn(ctx, id, opts any) *MockEngineCopyInCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyIn", reflect.TypeOf((*MockEngine)(nil).CopyIn), ctx, id, opts)
	return &MockEngineCopyInCall{Call: call}
}

// MockEngineCopyInCall wrap *gomock.Call
type MockEngineCopyInCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineCopyInCall) Return(arg0 error) *MockEngineCopyInCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineCopyInCall) Do(f func(context.Context, string, *container.CopyInOptions) error) *MockEngineCopyInCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineCopyInCall) DoAndReturn(f func(context.Context, string, *container.CopyInOptions) error) *MockEngineCopyInCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CopyOut mocks base method.
func (m *MockEngine) CopyOut(ctx context.Context, id string, opts *container.CopyOutOptions) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyOut", ctx, id, opts)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyOut indicates an expected call of CopyOut.
func (mr *MockEngineMockRecorder) CopyOut(ctx, id, opts any) *MockEngineCopyOutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyOut", reflect.TypeOf((*MockEngine)(nil).CopyOut), ctx, id, opts)
	return &MockEngineCopyOutCall{Call: call}
}

// MockEngineCopyOutCall wrap *gomock.Call
type MockEngineCopyOutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineCopyOutCall) Return(arg0 io.ReadCloser, arg1 error) *MockEngineCopyOutCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineCopyOutCall) Do(f func(context.Context, string, *container.CopyOutOptions) (io.ReadCloser, error)) *MockEngineCopyOutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineCopyOutCall) DoAndReturn(f func(context.Context, string, *container.CopyOutOptions) (io.ReadCloser, error)) *MockEngineCopyOutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ImageBuild mocks base method.
func (m *MockEngine) ImageBuild(ctx context.Context, context io.Reader, opts *container.BuildOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImageBuild", ctx, context, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImageBuild indicates an expected call of ImageBuild.
func (mr *MockEngineMockRecorder) ImageBuild(ctx, context, opts any) *MockEngineImageBuildCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImageBuild", reflect.TypeOf((*MockEngine)(nil).ImageBuild), ctx, context, opts)
	return &MockEngineImageBuildCall{Call: call}
}

// MockEngineImageBuildCall wrap *gomock.Call
type MockEngineImageBuildCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineImageBuildCall) Return(arg0 error) *MockEngineImageBuildCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineImageBuildCall) Do(f func(context.Context, io.Reader, *container.BuildOptions) error) *MockEngineImageBuildCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineImageBuildCall) DoAndReturn(f func(context.Context, io.Reader, *container.BuildOptions) error) *MockEngineImageBuildCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ImagePull mocks base method.
func (m *MockEngine) ImagePull(ctx context.Context, ref string, opts *container.PullOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImagePull", ctx, ref, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImagePull indicates an expected call of ImagePull.
func (mr *MockEngineMockRecorder) ImagePull(ctx, ref, opts any) *MockEngineImagePullCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImagePull", reflect.TypeOf((*MockEngine)(nil).ImagePull), ctx, ref, opts)
	return &MockEngineImagePullCall{Call: call}
}

// MockEngineImagePullCall wrap *gomock.Call
type MockEngineImagePullCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineImagePullCall) Return(arg0 error) *MockEngineImagePullCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineImagePullCall) Do(f func(context.Context, string, *container.PullOptions) error) *MockEngineImagePullCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineImagePullCall) DoAndReturn(f func(context.Context, string, *container.PullOptions) error) *MockEngineImagePullCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NetworkCreate mocks base method.
func (m *MockEngine) NetworkCreate(ctx context.Context, spec *types.NetworkSpec) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkCreate", ctx, spec)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkCreate indicates an expected call of NetworkCreate.
func (mr *MockEngineMockRecorder) NetworkCreate(ctx, spec any) *MockEngineNetworkCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkCreate", reflect.TypeOf((*MockEngine)(nil).NetworkCreate), ctx, spec)
	return &MockEngineNetworkCreateCall{Call: call}
}

// MockEngineNetworkCreateCall wrap *gomock.Call
type MockEngineNetworkCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineNetworkCreateCall) Return(arg0 string, arg1 error) *MockEngineNetworkCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineNetworkCreateCall) Do(f func(context.Context, *types.NetworkSpec) (string, error)) *MockEngineNetworkCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineNetworkCreateCall) DoAndReturn(f func(context.Context, *types.NetworkSpec) (string, error)) *MockEngineNetworkCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NetworkRemove mocks base method.
func (m *MockEngine) NetworkRemove(ctx context.Context, opts *container.RemoveOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkRemove", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// NetworkRemove indicates an expected call of NetworkRemove.
func (mr *MockEngineMockRecorder) NetworkRemove(ctx, opts any) *MockEngineNetworkRemoveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkRemove", reflect.TypeOf((*MockEngine)(nil).NetworkRemove), ctx, opts)
	return &MockEngineNetworkRemoveCall{Call: call}
}

// MockEngineNetworkRemoveCall wrap *gomock.Call
type MockEngineNetworkRemoveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineNetworkRemoveCall) Return(arg0 error) *MockEngineNetworkRemoveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineNetworkRemoveCall) Do(f func(context.Context, *container.RemoveOptions) error) *MockEngineNetworkRemoveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineNetworkRemoveCall) DoAndReturn(f func(context.Context, *container.RemoveOptions) error) *MockEngineNetworkRemoveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stat mocks base method.
func (m *MockEngine) Stat(ctx context.Context, id, path string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", ctx, id, path)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockEngineMockRecorder) Stat(ctx, id, path any) *MockEngineStatCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockEngine)(nil).Stat), ctx, id, path)
	return &MockEngineStatCall{Call: call}
}

// MockEngineStatCall wrap *gomock.Call
type MockEngineStatCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineStatCall) Return(arg0 fs.FileInfo, arg1 error) *MockEngineStatCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineStatCall) Do(f func(context.Context, string, string) (fs.FileInfo, error)) *MockEngineStatCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineStatCall) DoAndReturn(f func(context.Context, string, string) (fs.FileInfo, error)) *MockEngineStatCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// VolumeCreate mocks base method.
func (m *MockEngine) VolumeCreate(ctx context.Context, spec *types.VolumeSpec) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VolumeCreate", ctx, spec)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VolumeCreate indicates an expected call of VolumeCreate.
func (mr *MockEngineMockRecorder) VolumeCreate(ctx, spec any) *MockEngineVolumeCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VolumeCreate", reflect.TypeOf((*MockEngine)(nil).VolumeCreate), ctx, spec)
	return &MockEngineVolumeCreateCall{Call: call}
}

// MockEngineVolumeCreateCall wrap *gomock.Call
type MockEngineVolumeCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineVolumeCreateCall) Return(arg0 string, arg1 error) *MockEngineVolumeCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineVolumeCreateCall) Do(f func(context.Context, *types.VolumeSpec) (string, error)) *MockEngineVolumeCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineVolumeCreateCall) DoAndReturn(f func(context.Context, *types.VolumeSpec) (string, error)) *MockEngineVolumeCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// VolumeRemove mocks base method.
func (m *MockEngine) VolumeRemove(ctx context.Context, opts *container.RemoveOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VolumeRemove", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// VolumeRemove indicates an expected call of VolumeRemove.
func (mr *MockEngineMockRecorder) VolumeRemove(ctx, opts any) *MockEngineVolumeRemoveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VolumeRemove", reflect.TypeOf((*MockEngine)(nil).VolumeRemove), ctx, opts)
	return &MockEngineVolumeRemoveCall{Call: call}
}

// MockEngineVolumeRemoveCall wrap *gomock.Call
type MockEngineVolumeRemoveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineVolumeRemoveCall) Return(arg0 error) *MockEngineVolumeRemoveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineVolumeRemoveCall) Do(f func(context.Context, *container.RemoveOptions) error) *MockEngineVolumeRemoveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineVolumeRemoveCall) DoAndReturn(f func(context.Context, *container.RemoveOptions) error) *MockEngineVolumeRemoveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRegistryAuth is a mock of RegistryAuth interface.
type MockRegistryAuth struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryAuthMockRecorder
	isgomock struct{}
}

// MockRegistryAuthMockRecorder is the mock recorder for MockRegistryAuth.
type MockRegistryAuthMockRecorder struct {
	mock *MockRegistryAuth
}

// NewMockRegistryAuth creates a new mock instance.
func NewMockRegistryAuth(ctrl *gomock.Controller) *MockRegistryAuth {
	mock := &MockRegistryAuth{ctrl: ctrl}
	mock.recorder = &MockRegistryAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistryAuth) EXPECT() *MockRegistryAuthMockRecorder {
	return m.recorder
}

// Credential mocks base method.
func (m *MockRegistryAuth) Credential() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Credential")
	ret0, _ := ret[0].(string)
	return ret0
}

// Credential indicates an expected call of Credential.
func (mr *MockRegistryAuthMockRecorder) Credential() *MockRegistryAuthCredentialCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Credential", reflect.TypeOf((*MockRegistryAuth)(nil).Credential))
	return &MockRegistryAuthCredentialCall{Call: call}
}

// MockRegistryAuthCredentialCall wrap *gomock.Call
type MockRegistryAuthCredentialCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRegistryAuthCredentialCall) Return(arg0 string) *MockRegistryAuthCredentialCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRegistryAuthCredentialCall) Do(f func() string) *MockRegistryAuthCredentialCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRegistryAuthCredentialCall) DoAndReturn(f func() string) *MockRegistryAuthCredentialCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
