// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/containerd/containerd/v2/core/leases (interfaces: Manager)
//
// Generated by this command:
//
//	mockgen -typed -destination=containerd/leases/manager.go github.com/containerd/containerd/v2/core/leases Manager
//

// Package mock_leases is a generated GoMock package.
package mock_leases

import (
	context "context"
	reflect "reflect"

	leases "github.com/containerd/containerd/v2/core/leases"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// AddResource mocks base method.
func (m *MockManager) AddResource(arg0 context.Context, arg1 leases.Lease, arg2 leases.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddResource", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddResource indicates an expected call of AddResource.
func (mr *MockManagerMockRecorder) AddResource(arg0, arg1, arg2 any) *MockManagerAddResourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddResource", reflect.TypeOf((*MockManager)(nil).AddResource), arg0, arg1, arg2)
	return &MockManagerAddResourceCall{Call: call}
}

// MockManagerAddResourceCall wrap *gomock.Call
type MockManagerAddResourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerAddResourceCall) Return(arg0 error) *MockManagerAddResourceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerAddResourceCall) Do(f func(context.Context, leases.Lease, leases.Resource) error) *MockManagerAddResourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerAddResourceCall) DoAndReturn(f func(context.Context, leases.Lease, leases.Resource) error) *MockManagerAddResourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockManager) Create(arg0 context.Context, arg1 ...leases.Opt) (leases.Lease, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(leases.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockManagerMockRecorder) Create(arg0 any, arg1 ...any) *MockManagerCreateCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockManager)(nil).Create), varargs...)
	return &MockManagerCreateCall{Call: call}
}

// MockManagerCreateCall wrap *gomock.Call
type MockManagerCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerCreateCall) Return(arg0 leases.Lease, arg1 error) *MockManagerCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerCreateCall) Do(f func(context.Context, ...leases.Opt) (leases.Lease, error)) *MockManagerCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerCreateCall) DoAndReturn(f func(context.Context, ...leases.Opt) (leases.Lease, error)) *MockManagerCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockManager) Delete(arg0 context.Context, arg1 leases.Lease, arg2 ...leases.DeleteOpt) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockManagerMockRecorder) Delete(arg0, arg1 any, arg2 ...any) *MockManagerDeleteCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockManager)(nil).Delete), varargs...)
	return &MockManagerDeleteCall{Call: call}
}

// MockManagerDeleteCall wrap *gomock.Call
type MockManagerDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerDeleteCall) Return(arg0 error) *MockManagerDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerDeleteCall) Do(f func(context.Context, leases.Lease, ...leases.DeleteOpt) error) *MockManagerDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerDeleteCall) DoAndReturn(f func(context.Context, leases.Lease, ...leases.DeleteOpt) error) *MockManagerDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteResource mocks base method.
func (m *MockManager) DeleteResource(arg0 context.Context, arg1 leases.Lease, arg2 leases.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResource", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResource indicates an expected call of DeleteResource.
func (mr *MockManagerMockRecorder) DeleteResource(arg0, arg1, arg2 any) *MockManagerDeleteResourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResource", reflect.TypeOf((*MockManager)(nil).DeleteResource), arg0, arg1, arg2)
	return &MockManagerDeleteResourceCall{Call: call}
}

// MockManagerDeleteResourceCall wrap *gomock.Call
type MockManagerDeleteResourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerDeleteResourceCall) Return(arg0 error) *MockManagerDeleteResourceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerDeleteResourceCall) Do(f func(context.Context, leases.Lease, leases.Resource) error) *MockManagerDeleteResourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerDeleteResourceCall) DoAndReturn(f func(context.Context, leases.Lease, leases.Resource) error) *MockManagerDeleteResourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockManager) List(arg0 context.Context, arg1 ...string) ([]leases.Lease, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]leases.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockManagerMockRecorder) List(arg0 any, arg1 ...any) *MockManagerListCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockManager)(nil).List), varargs...)
	return &MockManagerListCall{Call: call}
}

// MockManagerListCall wrap *gomock.Call
type MockManagerListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerListCall) Return(arg0 []leases.Lease, arg1 error) *MockManagerListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerListCall) Do(f func(context.Context, ...string) ([]leases.Lease, error)) *MockManagerListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerListCall) DoAndReturn(f func(context.Context, ...string) ([]leases.Lease, error)) *MockManagerListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListResources mocks base method.
func (m *MockManager) ListResources(arg0 context.Context, arg1 leases.Lease) ([]leases.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResources", arg0, arg1)
	ret0, _ := ret[0].([]leases.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResources indicates an expected call of ListResources.
func (mr *MockManagerMockRecorder) ListResources(arg0, arg1 any) *MockManagerListResourcesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResources", reflect.TypeOf((*MockManager)(nil).ListResources), arg0, arg1)
	return &MockManagerListResourcesCall{Call: call}
}

// MockManagerListResourcesCall wrap *gomock.Call
type MockManagerListResourcesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerListResourcesCall) Return(arg0 []leases.Resource, arg1 error) *MockManagerListResourcesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerListResourcesCall) Do(f func(context.Context, leases.Lease) ([]leases.Resource, error)) *MockManagerListResourcesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerListResourcesCall) DoAndReturn(f func(context.Context, leases.Lease) ([]leases.Resource, error)) *MockManagerListResourcesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
