// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/logging/logger.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/logging/logger.go -destination=executor/logging/logger.go -typed
//

// Package mock_logging is a generated GoMock package.
package mock_logging

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Logf mocks base method.
func (m *MockLogger) Logf(tag, format string, a ...any) {
	m.ctrl.T.Helper()
	varargs := []any{tag, format}
	for _, a_2 := range a {
		varargs = append(varargs, a_2)
	}
	m.ctrl.Call(m, "Logf", varargs...)
}

// Logf indicates an expected call of Logf.
func (mr *MockLoggerMockRecorder) Logf(tag, format any, a ...any) *MockLoggerLogfCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{tag, format}, a...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logf", reflect.TypeOf((*MockLogger)(nil).Logf), varargs...)
	return &MockLoggerLogfCall{Call: call}
}

// MockLoggerLogfCall wrap *gomock.Call
type MockLoggerLogfCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoggerLogfCall) Return() *MockLoggerLogfCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoggerLogfCall) Do(f func(string, string, ...any)) *MockLoggerLogfCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoggerLogfCall) DoAndReturn(f func(string, string, ...any)) *MockLoggerLogfCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
