// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/logging/logger.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/logging/logger.go -destination=executor/logging/logger.go -typed
//

// Package mock_logging is a generated GoMock package.
package mock_logging

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Log mocks base method.
func (m *MockLogger) Log(tag, format string, a ...any) {
	m.ctrl.T.Helper()
	varargs := []any{tag, format}
	for _, a_2 := range a {
		varargs = append(varargs, a_2)
	}
	m.ctrl.Call(m, "Log", varargs...)
}

// Log indicates an expected call of Log.
func (mr *MockLoggerMockRecorder) Log(tag, format any, a ...any) *MockLoggerLogCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{tag, format}, a...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockLogger)(nil).Log), varargs...)
	return &MockLoggerLogCall{Call: call}
}

// MockLoggerLogCall wrap *gomock.Call
type MockLoggerLogCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLoggerLogCall) Return() *MockLoggerLogCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLoggerLogCall) Do(f func(string, string, ...any)) *MockLoggerLogCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLoggerLogCall) DoAndReturn(f func(string, string, ...any)) *MockLoggerLogCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
