// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/containerd/containerd/v2/core/snapshots (interfaces: Snapshotter)
//
// Generated by this command:
//
//	mockgen -typed -destination=containerd/snapshots/snapshotter.go github.com/containerd/containerd/v2/core/snapshots Snapshotter
//

// Package mock_snapshots is a generated GoMock package.
package mock_snapshots

import (
	context "context"
	reflect "reflect"

	mount "github.com/containerd/containerd/v2/core/mount"
	snapshots "github.com/containerd/containerd/v2/core/snapshots"
	gomock "go.uber.org/mock/gomock"
)

// MockSnapshotter is a mock of Snapshotter interface.
type MockSnapshotter struct {
	ctrl     *gomock.Controller
	recorder *MockSnapshotterMockRecorder
	isgomock struct{}
}

// MockSnapshotterMockRecorder is the mock recorder for MockSnapshotter.
type MockSnapshotterMockRecorder struct {
	mock *MockSnapshotter
}

// NewMockSnapshotter creates a new mock instance.
func NewMockSnapshotter(ctrl *gomock.Controller) *MockSnapshotter {
	mock := &MockSnapshotter{ctrl: ctrl}
	mock.recorder = &MockSnapshotterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnapshotter) EXPECT() *MockSnapshotterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSnapshotter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSnapshotterMockRecorder) Close() *MockSnapshotterCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSnapshotter)(nil).Close))
	return &MockSnapshotterCloseCall{Call: call}
}

// MockSnapshotterCloseCall wrap *gomock.Call
type MockSnapshotterCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSnapshotterCloseCall) Return(arg0 error) *MockSnapshotterCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSnapshotterCloseCall) Do(f func() error) *MockSnapshotterCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSnapshotterCloseCall) DoAndReturn(f func() error) *MockSnapshotterCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Commit mocks base method.
func (m *MockSnapshotter) Commit(ctx context.Context, name, key string, opts ...snapshots.Opt) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Commit", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockSnapshotterMockRecorder) Commit(ctx, name, key any, opts ...any) *MockSnapshotterCommitCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name, key}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockSnapshotter)(nil).Commit), varargs...)
	return &MockSnapshotterCommitCall{Call: call}
}

// MockSnapshotterCommitCall wrap *gomock.Call
type MockSnapshotterCommitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSnapshotterCommitCall) Return(arg0 error) *MockSnapshotterCommitCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSnapshotterCommitCall) Do(f func(context.Context, string, string, ...snapshots.Opt) error) *MockSnapshotterCommitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSnapshotterCommitCall) DoAndReturn(f func(context.Context, string, string, ...snapshots.Opt) error) *MockSnapshotterCommitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Mounts mocks base method.
func (m *MockSnapshotter) Mounts(ctx context.Context, key string) ([]mount.Mount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mounts", ctx, key)
	ret0, _ := ret[0].([]mount.Mount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Mounts indicates an expected call of Mounts.
func (mr *MockSnapshotterMockRecorder) Mounts(ctx, key any) *MockSnapshotterMountsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mounts", reflect.TypeOf((*MockSnapshotter)(nil).Mounts), ctx, key)
	return &MockSnapshotterMountsCall{Call: call}
}

// MockSnapshotterMountsCall wrap *gomock.Call
type MockSnapshotterMountsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSnapshotterMountsCall) Return(arg0 []mount.Mount, arg1 error) *MockSnapshotterMountsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSnapshotterMountsCall) Do(f func(context.Context, string) ([]mount.Mount, error)) *MockSnapshotterMountsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSnapshotterMountsCall) DoAndReturn(f func(context.Context, string) ([]mount.Mount, error)) *MockSnapshotterMountsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Prepare mocks base method.
func (m *MockSnapshotter) Prepare(ctx context.Context, key, parent string, opts ...snapshots.Opt) ([]mount.Mount, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, parent}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Prepare", varargs...)
	ret0, _ := ret[0].([]mount.Mount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prepare indicates an expected call of Prepare.
func (mr *MockSnapshotterMockRecorder) Prepare(ctx, key, parent any, opts ...any) *MockSnapshotterPrepareCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, parent}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockSnapshotter)(nil).Prepare), varargs...)
	return &MockSnapshotterPrepareCall{Call: call}
}

// MockSnapshotterPrepareCall wrap *gomock.Call
type MockSnapshotterPrepareCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSnapshotterPrepareCall) Return(arg0 []mount.Mount, arg1 error) *MockSnapshotterPrepareCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSnapshotterPrepareCall) Do(f func(context.Context, string, string, ...snapshots.Opt) ([]mount.Mount, error)) *MockSnapshotterPrepareCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSnapshotterPrepareCall) DoAndReturn(f func(context.Context, string, string, ...snapshots.Opt) ([]mount.Mount, error)) *MockSnapshotterPrepareCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Remove mocks base method.
func (m *MockSnapshotter) Remove(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockSnapshotterMockRecorder) Remove(ctx, key any) *MockSnapshotterRemoveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockSnapshotter)(nil).Remove), ctx, key)
	return &MockSnapshotterRemoveCall{Call: call}
}

// MockSnapshotterRemoveCall wrap *gomock.Call
type MockSnapshotterRemoveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSnapshotterRemoveCall) Return(arg0 error) *MockSnapshotterRemoveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSnapshotterRemoveCall) Do(f func(context.Context, string) error) *MockSnapshotterRemoveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSnapshotterRemoveCall) DoAndReturn(f func(context.Context, string) error) *MockSnapshotterRemoveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stat mocks base method.
func (m *MockSnapshotter) Stat(ctx context.Context, key string) (snapshots.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", ctx, key)
	ret0, _ := ret[0].(snapshots.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockSnapshotterMockRecorder) Stat(ctx, key any) *MockSnapshotterStatCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockSnapshotter)(nil).Stat), ctx, key)
	return &MockSnapshotterStatCall{Call: call}
}

// MockSnapshotterStatCall wrap *gomock.Call
type MockSnapshotterStatCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSnapshotterStatCall) Return(arg0 snapshots.Info, arg1 error) *MockSnapshotterStatCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSnapshotterStatCall) Do(f func(context.Context, string) (snapshots.Info, error)) *MockSnapshotterStatCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSnapshotterStatCall) DoAndReturn(f func(context.Context, string) (snapshots.Info, error)) *MockSnapshotterStatCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockSnapshotter) Update(ctx context.Context, info snapshots.Info, fieldpaths ...string) (snapshots.Info, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, info}
	for _, a := range fieldpaths {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(snapshots.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSnapshotterMockRecorder) Update(ctx, info any, fieldpaths ...any) *MockSnapshotterUpdateCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, info}, fieldpaths...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSnapshotter)(nil).Update), varargs...)
	return &MockSnapshotterUpdateCall{Call: call}
}

// MockSnapshotterUpdateCall wrap *gomock.Call
type MockSnapshotterUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSnapshotterUpdateCall) Return(arg0 snapshots.Info, arg1 error) *MockSnapshotterUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSnapshotterUpdateCall) Do(f func(context.Context, snapshots.Info, ...string) (snapshots.Info, error)) *MockSnapshotterUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSnapshotterUpdateCall) DoAndReturn(f func(context.Context, snapshots.Info, ...string) (snapshots.Info, error)) *MockSnapshotterUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Usage mocks base method.
func (m *MockSnapshotter) Usage(ctx context.Context, key string) (snapshots.Usage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Usage", ctx, key)
	ret0, _ := ret[0].(snapshots.Usage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Usage indicates an expected call of Usage.
func (mr *MockSnapshotterMockRecorder) Usage(ctx, key any) *MockSnapshotterUsageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Usage", reflect.TypeOf((*MockSnapshotter)(nil).Usage), ctx, key)
	return &MockSnapshotterUsageCall{Call: call}
}

// MockSnapshotterUsageCall wrap *gomock.Call
type MockSnapshotterUsageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSnapshotterUsageCall) Return(arg0 snapshots.Usage, arg1 error) *MockSnapshotterUsageCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSnapshotterUsageCall) Do(f func(context.Context, string) (snapshots.Usage, error)) *MockSnapshotterUsageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSnapshotterUsageCall) DoAndReturn(f func(context.Context, string) (snapshots.Usage, error)) *MockSnapshotterUsageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// View mocks base method.
func (m *MockSnapshotter) View(ctx context.Context, key, parent string, opts ...snapshots.Opt) ([]mount.Mount, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, parent}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "View", varargs...)
	ret0, _ := ret[0].([]mount.Mount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// View indicates an expected call of View.
func (mr *MockSnapshotterMockRecorder) View(ctx, key, parent any, opts ...any) *MockSnapshotterViewCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, parent}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "View", reflect.TypeOf((*MockSnapshotter)(nil).View), varargs...)
	return &MockSnapshotterViewCall{Call: call}
}

// MockSnapshotterViewCall wrap *gomock.Call
type MockSnapshotterViewCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSnapshotterViewCall) Return(arg0 []mount.Mount, arg1 error) *MockSnapshotterViewCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSnapshotterViewCall) Do(f func(context.Context, string, string, ...snapshots.Opt) ([]mount.Mount, error)) *MockSnapshotterViewCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSnapshotterViewCall) DoAndReturn(f func(context.Context, string, string, ...snapshots.Opt) ([]mount.Mount, error)) *MockSnapshotterViewCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Walk mocks base method.
func (m *MockSnapshotter) Walk(ctx context.Context, fn snapshots.WalkFunc, filters ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, fn}
	for _, a := range filters {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Walk", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Walk indicates an expected call of Walk.
func (mr *MockSnapshotterMockRecorder) Walk(ctx, fn any, filters ...any) *MockSnapshotterWalkCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, fn}, filters...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Walk", reflect.TypeOf((*MockSnapshotter)(nil).Walk), varargs...)
	return &MockSnapshotterWalkCall{Call: call}
}

// MockSnapshotterWalkCall wrap *gomock.Call
type MockSnapshotterWalkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSnapshotterWalkCall) Return(arg0 error) *MockSnapshotterWalkCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSnapshotterWalkCall) Do(f func(context.Context, snapshots.WalkFunc, ...string) error) *MockSnapshotterWalkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSnapshotterWalkCall) DoAndReturn(f func(context.Context, snapshots.WalkFunc, ...string) error) *MockSnapshotterWalkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
