// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/types/types.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/types/types.go -destination=types/types.go -typed
//

// Package mock_types is a generated GoMock package.
package mock_types

import (
	reflect "reflect"

	executor "drassi.run/core/pkg/executor"
	gomock "go.uber.org/mock/gomock"
)

// MockRecordStore is a mock of RecordStore interface.
type MockRecordStore struct {
	ctrl     *gomock.Controller
	recorder *MockRecordStoreMockRecorder
	isgomock struct{}
}

// MockRecordStoreMockRecorder is the mock recorder for MockRecordStore.
type MockRecordStoreMockRecorder struct {
	mock *MockRecordStore
}

// NewMockRecordStore creates a new mock instance.
func NewMockRecordStore(ctrl *gomock.Controller) *MockRecordStore {
	mock := &MockRecordStore{ctrl: ctrl}
	mock.recorder = &MockRecordStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordStore) EXPECT() *MockRecordStoreMockRecorder {
	return m.recorder
}

// RecordUid mocks base method.
func (m *MockRecordStore) RecordUid(stage executor.Stage, uid string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordUid", stage, uid)
	ret0, _ := ret[0].(string)
	return ret0
}

// RecordUid indicates an expected call of RecordUid.
func (mr *MockRecordStoreMockRecorder) RecordUid(stage, uid any) *MockRecordStoreRecordUidCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordUid", reflect.TypeOf((*MockRecordStore)(nil).RecordUid), stage, uid)
	return &MockRecordStoreRecordUidCall{Call: call}
}

// MockRecordStoreRecordUidCall wrap *gomock.Call
type MockRecordStoreRecordUidCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRecordStoreRecordUidCall) Return(arg0 string) *MockRecordStoreRecordUidCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRecordStoreRecordUidCall) Do(f func(executor.Stage, string) string) *MockRecordStoreRecordUidCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRecordStoreRecordUidCall) DoAndReturn(f func(executor.Stage, string) string) *MockRecordStoreRecordUidCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
