// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/problem/factory.go
//
// Generated by this command:
//
//	mockgen -typed -destination=problem/factory.go -source=../pkg/problem/factory.go
//

// Package mock_problem is a generated GoMock package.
package mock_problem

import (
	reflect "reflect"

	problem "drassi.run/core/pkg/problem"
	gomock "go.uber.org/mock/gomock"
)

// MockDetector is a mock of Detector interface.
type MockDetector struct {
	ctrl     *gomock.Controller
	recorder *MockDetectorMockRecorder
	isgomock struct{}
}

// MockDetectorMockRecorder is the mock recorder for MockDetector.
type MockDetectorMockRecorder struct {
	mock *MockDetector
}

// NewMockDetector creates a new mock instance.
func NewMockDetector(ctrl *gomock.Controller) *MockDetector {
	mock := &MockDetector{ctrl: ctrl}
	mock.recorder = &MockDetectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDetector) EXPECT() *MockDetectorMockRecorder {
	return m.recorder
}

// Detect mocks base method.
func (m *MockDetector) Detect(line string) *problem.Problem {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detect", line)
	ret0, _ := ret[0].(*problem.Problem)
	return ret0
}

// Detect indicates an expected call of Detect.
func (mr *MockDetectorMockRecorder) Detect(line any) *MockDetectorDetectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detect", reflect.TypeOf((*MockDetector)(nil).Detect), line)
	return &MockDetectorDetectCall{Call: call}
}

// MockDetectorDetectCall wrap *gomock.Call
type MockDetectorDetectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDetectorDetectCall) Return(pbl *problem.Problem) *MockDetectorDetectCall {
	c.Call = c.Call.Return(pbl)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDetectorDetectCall) Do(f func(string) *problem.Problem) *MockDetectorDetectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDetectorDetectCall) DoAndReturn(f func(string) *problem.Problem) *MockDetectorDetectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
