// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/problem/matcher.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/problem/matcher.go -destination=problem/matcher.go -typed
//

// Package mock_problem is a generated GoMock package.
package mock_problem

import (
	reflect "reflect"

	problem "drassi.run/core/pkg/problem"
	gomock "go.uber.org/mock/gomock"
)

// MockMatcher is a mock of Matcher interface.
type MockMatcher struct {
	ctrl     *gomock.Controller
	recorder *MockMatcherMockRecorder
	isgomock struct{}
}

// MockMatcherMockRecorder is the mock recorder for MockMatcher.
type MockMatcherMockRecorder struct {
	mock *MockMatcher
}

// NewMockMatcher creates a new mock instance.
func NewMockMatcher(ctrl *gomock.Controller) *MockMatcher {
	mock := &MockMatcher{ctrl: ctrl}
	mock.recorder = &MockMatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatcher) EXPECT() *MockMatcherMockRecorder {
	return m.recorder
}

// Match mocks base method.
func (m *MockMatcher) Match(line string) *problem.Problem {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Match", line)
	ret0, _ := ret[0].(*problem.Problem)
	return ret0
}

// Match indicates an expected call of Match.
func (mr *MockMatcherMockRecorder) Match(line any) *MockMatcherMatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Match", reflect.TypeOf((*MockMatcher)(nil).Match), line)
	return &MockMatcherMatchCall{Call: call}
}

// MockMatcherMatchCall wrap *gomock.Call
type MockMatcherMatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMatcherMatchCall) Return(arg0 *problem.Problem) *MockMatcherMatchCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMatcherMatchCall) Do(f func(string) *problem.Problem) *MockMatcherMatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMatcherMatchCall) DoAndReturn(f func(string) *problem.Problem) *MockMatcherMatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Reset mocks base method.
func (m *MockMatcher) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockMatcherMockRecorder) Reset() *MockMatcherResetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockMatcher)(nil).Reset))
	return &MockMatcherResetCall{Call: call}
}

// MockMatcherResetCall wrap *gomock.Call
type MockMatcherResetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMatcherResetCall) Return() *MockMatcherResetCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMatcherResetCall) Do(f func()) *MockMatcherResetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMatcherResetCall) DoAndReturn(f func()) *MockMatcherResetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
