// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/problem/matcher.go
//
// Generated by this command:
//
//	mockgen -typed -destination=problem/matcher.go -source=../pkg/problem/matcher.go
//

// Package mock_problem is a generated GoMock package.
package mock_problem

import (
	reflect "reflect"

	problem "drassi.run/core/pkg/problem"
	gomock "go.uber.org/mock/gomock"
)

// MockMatcher is a mock of Matcher interface.
type MockMatcher struct {
	ctrl     *gomock.Controller
	recorder *MockMatcherMockRecorder
	isgomock struct{}
}

// MockMatcherMockRecorder is the mock recorder for MockMatcher.
type MockMatcherMockRecorder struct {
	mock *MockMatcher
}

// NewMockMatcher creates a new mock instance.
func NewMockMatcher(ctrl *gomock.Controller) *MockMatcher {
	mock := &MockMatcher{ctrl: ctrl}
	mock.recorder = &MockMatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatcher) EXPECT() *MockMatcherMockRecorder {
	return m.recorder
}

// Len mocks base method.
func (m *MockMatcher) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockMatcherMockRecorder) Len() *MockMatcherLenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockMatcher)(nil).Len))
	return &MockMatcherLenCall{Call: call}
}

// MockMatcherLenCall wrap *gomock.Call
type MockMatcherLenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMatcherLenCall) Return(arg0 int) *MockMatcherLenCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMatcherLenCall) Do(f func() int) *MockMatcherLenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMatcherLenCall) DoAndReturn(f func() int) *MockMatcherLenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Match mocks base method.
func (m *MockMatcher) Match(states []*problem.Problem, line string) *problem.Problem {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Match", states, line)
	ret0, _ := ret[0].(*problem.Problem)
	return ret0
}

// Match indicates an expected call of Match.
func (mr *MockMatcherMockRecorder) Match(states, line any) *MockMatcherMatchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Match", reflect.TypeOf((*MockMatcher)(nil).Match), states, line)
	return &MockMatcherMatchCall{Call: call}
}

// MockMatcherMatchCall wrap *gomock.Call
type MockMatcherMatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMatcherMatchCall) Return(arg0 *problem.Problem) *MockMatcherMatchCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMatcherMatchCall) Do(f func([]*problem.Problem, string) *problem.Problem) *MockMatcherMatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMatcherMatchCall) DoAndReturn(f func([]*problem.Problem, string) *problem.Problem) *MockMatcherMatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
