// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/log/batcher.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/log/batcher.go -destination=log/batcher.go -typed
//

// Package mock_log is a generated GoMock package.
package mock_log

import (
	reflect "reflect"

	log "drassi.run/gha-runner/pkg/log"
	gomock "go.uber.org/mock/gomock"
)

// MockBatch is a mock of Batch interface.
type MockBatch struct {
	ctrl     *gomock.Controller
	recorder *MockBatchMockRecorder
	isgomock struct{}
}

// MockBatchMockRecorder is the mock recorder for MockBatch.
type MockBatchMockRecorder struct {
	mock *MockBatch
}

// NewMockBatch creates a new mock instance.
func NewMockBatch(ctrl *gomock.Controller) *MockBatch {
	mock := &MockBatch{ctrl: ctrl}
	mock.recorder = &MockBatchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatch) EXPECT() *MockBatchMockRecorder {
	return m.recorder
}

// Empty mocks base method.
func (m *MockBatch) Empty() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Empty")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Empty indicates an expected call of Empty.
func (mr *MockBatchMockRecorder) Empty() *MockBatchEmptyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Empty", reflect.TypeOf((*MockBatch)(nil).Empty))
	return &MockBatchEmptyCall{Call: call}
}

// MockBatchEmptyCall wrap *gomock.Call
type MockBatchEmptyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBatchEmptyCall) Return(arg0 bool) *MockBatchEmptyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBatchEmptyCall) Do(f func() bool) *MockBatchEmptyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBatchEmptyCall) DoAndReturn(f func() bool) *MockBatchEmptyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Lines mocks base method.
func (m *MockBatch) Lines() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lines")
	ret0, _ := ret[0].(int)
	return ret0
}

// Lines indicates an expected call of Lines.
func (mr *MockBatchMockRecorder) Lines() *MockBatchLinesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lines", reflect.TypeOf((*MockBatch)(nil).Lines))
	return &MockBatchLinesCall{Call: call}
}

// MockBatchLinesCall wrap *gomock.Call
type MockBatchLinesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBatchLinesCall) Return(arg0 int) *MockBatchLinesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBatchLinesCall) Do(f func() int) *MockBatchLinesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBatchLinesCall) DoAndReturn(f func() int) *MockBatchLinesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Scan mocks base method.
func (m *MockBatch) Scan() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scan")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scan indicates an expected call of Scan.
func (mr *MockBatchMockRecorder) Scan() *MockBatchScanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockBatch)(nil).Scan))
	return &MockBatchScanCall{Call: call}
}

// MockBatchScanCall wrap *gomock.Call
type MockBatchScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBatchScanCall) Return(arg0 []string, arg1 error) *MockBatchScanCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBatchScanCall) Do(f func() ([]string, error)) *MockBatchScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBatchScanCall) DoAndReturn(f func() ([]string, error)) *MockBatchScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockBatcher is a mock of Batcher interface.
type MockBatcher struct {
	ctrl     *gomock.Controller
	recorder *MockBatcherMockRecorder
	isgomock struct{}
}

// MockBatcherMockRecorder is the mock recorder for MockBatcher.
type MockBatcherMockRecorder struct {
	mock *MockBatcher
}

// NewMockBatcher creates a new mock instance.
func NewMockBatcher(ctrl *gomock.Controller) *MockBatcher {
	mock := &MockBatcher{ctrl: ctrl}
	mock.recorder = &MockBatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatcher) EXPECT() *MockBatcherMockRecorder {
	return m.recorder
}

// Channel mocks base method.
func (m *MockBatcher) Channel() <-chan log.Batch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Channel")
	ret0, _ := ret[0].(<-chan log.Batch)
	return ret0
}

// Channel indicates an expected call of Channel.
func (mr *MockBatcherMockRecorder) Channel() *MockBatcherChannelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Channel", reflect.TypeOf((*MockBatcher)(nil).Channel))
	return &MockBatcherChannelCall{Call: call}
}

// MockBatcherChannelCall wrap *gomock.Call
type MockBatcherChannelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBatcherChannelCall) Return(arg0 <-chan log.Batch) *MockBatcherChannelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBatcherChannelCall) Do(f func() <-chan log.Batch) *MockBatcherChannelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBatcherChannelCall) DoAndReturn(f func() <-chan log.Batch) *MockBatcherChannelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Close mocks base method.
func (m *MockBatcher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBatcherMockRecorder) Close() *MockBatcherCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBatcher)(nil).Close))
	return &MockBatcherCloseCall{Call: call}
}

// MockBatcherCloseCall wrap *gomock.Call
type MockBatcherCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBatcherCloseCall) Return(arg0 error) *MockBatcherCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBatcherCloseCall) Do(f func() error) *MockBatcherCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBatcherCloseCall) DoAndReturn(f func() error) *MockBatcherCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockBatcher) Update(u *log.Update) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", u)
}

// Update indicates an expected call of Update.
func (mr *MockBatcherMockRecorder) Update(u any) *MockBatcherUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBatcher)(nil).Update), u)
	return &MockBatcherUpdateCall{Call: call}
}

// MockBatcherUpdateCall wrap *gomock.Call
type MockBatcherUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBatcherUpdateCall) Return() *MockBatcherUpdateCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBatcherUpdateCall) Do(f func(*log.Update)) *MockBatcherUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBatcherUpdateCall) DoAndReturn(f func(*log.Update)) *MockBatcherUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
