// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/log/chunker.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/log/chunker.go -destination=log/chunker.go -typed
//

// Package mock_log is a generated GoMock package.
package mock_log

import (
	reflect "reflect"

	log "drassi.run/gha-runner/pkg/log"
	gomock "go.uber.org/mock/gomock"
)

// MockChunker is a mock of Chunker interface.
type MockChunker struct {
	ctrl     *gomock.Controller
	recorder *MockChunkerMockRecorder
	isgomock struct{}
}

// MockChunkerMockRecorder is the mock recorder for MockChunker.
type MockChunkerMockRecorder struct {
	mock *MockChunker
}

// NewMockChunker creates a new mock instance.
func NewMockChunker(ctrl *gomock.Controller) *MockChunker {
	mock := &MockChunker{ctrl: ctrl}
	mock.recorder = &MockChunkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunker) EXPECT() *MockChunkerMockRecorder {
	return m.recorder
}

// Channel mocks base method.
func (m *MockChunker) Channel() <-chan log.Chunk {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Channel")
	ret0, _ := ret[0].(<-chan log.Chunk)
	return ret0
}

// Channel indicates an expected call of Channel.
func (mr *MockChunkerMockRecorder) Channel() *MockChunkerChannelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Channel", reflect.TypeOf((*MockChunker)(nil).Channel))
	return &MockChunkerChannelCall{Call: call}
}

// MockChunkerChannelCall wrap *gomock.Call
type MockChunkerChannelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChunkerChannelCall) Return(arg0 <-chan log.Chunk) *MockChunkerChannelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChunkerChannelCall) Do(f func() <-chan log.Chunk) *MockChunkerChannelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChunkerChannelCall) DoAndReturn(f func() <-chan log.Chunk) *MockChunkerChannelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Close mocks base method.
func (m *MockChunker) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockChunkerMockRecorder) Close() *MockChunkerCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockChunker)(nil).Close))
	return &MockChunkerCloseCall{Call: call}
}

// MockChunkerCloseCall wrap *gomock.Call
type MockChunkerCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChunkerCloseCall) Return(arg0 error) *MockChunkerCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChunkerCloseCall) Do(f func() error) *MockChunkerCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChunkerCloseCall) DoAndReturn(f func() error) *MockChunkerCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockChunker) Update(u *log.Update) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", u)
}

// Update indicates an expected call of Update.
func (mr *MockChunkerMockRecorder) Update(u any) *MockChunkerUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockChunker)(nil).Update), u)
	return &MockChunkerUpdateCall{Call: call}
}

// MockChunkerUpdateCall wrap *gomock.Call
type MockChunkerUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChunkerUpdateCall) Return() *MockChunkerUpdateCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChunkerUpdateCall) Do(f func(*log.Update)) *MockChunkerUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChunkerUpdateCall) DoAndReturn(f func(*log.Update)) *MockChunkerUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
