// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/log/chunker.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/log/chunker.go -destination=log/chunker.go -typed
//

// Package mock_log is a generated GoMock package.
package mock_log

import (
	io "io"
	reflect "reflect"

	log "drassi.run/gha-runner/pkg/log"
	gomock "go.uber.org/mock/gomock"
)

// MockChunk is a mock of Chunk interface.
type MockChunk struct {
	ctrl     *gomock.Controller
	recorder *MockChunkMockRecorder
	isgomock struct{}
}

// MockChunkMockRecorder is the mock recorder for MockChunk.
type MockChunkMockRecorder struct {
	mock *MockChunk
}

// NewMockChunk creates a new mock instance.
func NewMockChunk(ctrl *gomock.Controller) *MockChunk {
	mock := &MockChunk{ctrl: ctrl}
	mock.recorder = &MockChunkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunk) EXPECT() *MockChunkMockRecorder {
	return m.recorder
}

// Empty mocks base method.
func (m *MockChunk) Empty() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Empty")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Empty indicates an expected call of Empty.
func (mr *MockChunkMockRecorder) Empty() *MockChunkEmptyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Empty", reflect.TypeOf((*MockChunk)(nil).Empty))
	return &MockChunkEmptyCall{Call: call}
}

// MockChunkEmptyCall wrap *gomock.Call
type MockChunkEmptyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChunkEmptyCall) Return(arg0 bool) *MockChunkEmptyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChunkEmptyCall) Do(f func() bool) *MockChunkEmptyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChunkEmptyCall) DoAndReturn(f func() bool) *MockChunkEmptyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Lines mocks base method.
func (m *MockChunk) Lines() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lines")
	ret0, _ := ret[0].(int)
	return ret0
}

// Lines indicates an expected call of Lines.
func (mr *MockChunkMockRecorder) Lines() *MockChunkLinesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lines", reflect.TypeOf((*MockChunk)(nil).Lines))
	return &MockChunkLinesCall{Call: call}
}

// MockChunkLinesCall wrap *gomock.Call
type MockChunkLinesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChunkLinesCall) Return(arg0 int) *MockChunkLinesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChunkLinesCall) Do(f func() int) *MockChunkLinesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChunkLinesCall) DoAndReturn(f func() int) *MockChunkLinesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Reader mocks base method.
func (m *MockChunk) Reader() (io.ReadSeekCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reader")
	ret0, _ := ret[0].(io.ReadSeekCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reader indicates an expected call of Reader.
func (mr *MockChunkMockRecorder) Reader() *MockChunkReaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reader", reflect.TypeOf((*MockChunk)(nil).Reader))
	return &MockChunkReaderCall{Call: call}
}

// MockChunkReaderCall wrap *gomock.Call
type MockChunkReaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChunkReaderCall) Return(arg0 io.ReadSeekCloser, arg1 error) *MockChunkReaderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChunkReaderCall) Do(f func() (io.ReadSeekCloser, error)) *MockChunkReaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChunkReaderCall) DoAndReturn(f func() (io.ReadSeekCloser, error)) *MockChunkReaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Size mocks base method.
func (m *MockChunk) Size() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *MockChunkMockRecorder) Size() *MockChunkSizeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockChunk)(nil).Size))
	return &MockChunkSizeCall{Call: call}
}

// MockChunkSizeCall wrap *gomock.Call
type MockChunkSizeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChunkSizeCall) Return(arg0 int64) *MockChunkSizeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChunkSizeCall) Do(f func() int64) *MockChunkSizeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChunkSizeCall) DoAndReturn(f func() int64) *MockChunkSizeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockChunker is a mock of Chunker interface.
type MockChunker struct {
	ctrl     *gomock.Controller
	recorder *MockChunkerMockRecorder
	isgomock struct{}
}

// MockChunkerMockRecorder is the mock recorder for MockChunker.
type MockChunkerMockRecorder struct {
	mock *MockChunker
}

// NewMockChunker creates a new mock instance.
func NewMockChunker(ctrl *gomock.Controller) *MockChunker {
	mock := &MockChunker{ctrl: ctrl}
	mock.recorder = &MockChunkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunker) EXPECT() *MockChunkerMockRecorder {
	return m.recorder
}

// Channel mocks base method.
func (m *MockChunker) Channel() <-chan log.Chunk {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Channel")
	ret0, _ := ret[0].(<-chan log.Chunk)
	return ret0
}

// Channel indicates an expected call of Channel.
func (mr *MockChunkerMockRecorder) Channel() *MockChunkerChannelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Channel", reflect.TypeOf((*MockChunker)(nil).Channel))
	return &MockChunkerChannelCall{Call: call}
}

// MockChunkerChannelCall wrap *gomock.Call
type MockChunkerChannelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChunkerChannelCall) Return(arg0 <-chan log.Chunk) *MockChunkerChannelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChunkerChannelCall) Do(f func() <-chan log.Chunk) *MockChunkerChannelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChunkerChannelCall) DoAndReturn(f func() <-chan log.Chunk) *MockChunkerChannelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Close mocks base method.
func (m *MockChunker) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockChunkerMockRecorder) Close() *MockChunkerCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockChunker)(nil).Close))
	return &MockChunkerCloseCall{Call: call}
}

// MockChunkerCloseCall wrap *gomock.Call
type MockChunkerCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChunkerCloseCall) Return(arg0 error) *MockChunkerCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChunkerCloseCall) Do(f func() error) *MockChunkerCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChunkerCloseCall) DoAndReturn(f func() error) *MockChunkerCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockChunker) Update(u *log.Update) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", u)
}

// Update indicates an expected call of Update.
func (mr *MockChunkerMockRecorder) Update(u any) *MockChunkerUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockChunker)(nil).Update), u)
	return &MockChunkerUpdateCall{Call: call}
}

// MockChunkerUpdateCall wrap *gomock.Call
type MockChunkerUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChunkerUpdateCall) Return() *MockChunkerUpdateCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChunkerUpdateCall) Do(f func(*log.Update)) *MockChunkerUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChunkerUpdateCall) DoAndReturn(f func(*log.Update)) *MockChunkerUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
