// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/command/issue/issue.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/command/issue/issue.go -destination=executor/command/issue/issue.go -typed
//

// Package mock_issue is a generated GoMock package.
package mock_issue

import (
	context "context"
	reflect "reflect"

	issue "drassi.run/core/pkg/executor/command/issue"
	gomock "go.uber.org/mock/gomock"
)

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
	isgomock struct{}
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// AddIssue mocks base method.
func (m *MockReporter) AddIssue(ctx context.Context, issue *issue.Issue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIssue", ctx, issue)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIssue indicates an expected call of AddIssue.
func (mr *MockReporterMockRecorder) AddIssue(ctx, issue any) *MockReporterAddIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIssue", reflect.TypeOf((*MockReporter)(nil).AddIssue), ctx, issue)
	return &MockReporterAddIssueCall{Call: call}
}

// MockReporterAddIssueCall wrap *gomock.Call
type MockReporterAddIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterAddIssueCall) Return(arg0 error) *MockReporterAddIssueCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterAddIssueCall) Do(f func(context.Context, *issue.Issue) error) *MockReporterAddIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterAddIssueCall) DoAndReturn(f func(context.Context, *issue.Issue) error) *MockReporterAddIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
