// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/command/issue/issue.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/command/issue/issue.go -destination=executor/command/issue/issue.go -typed
//

// Package mock_issue is a generated GoMock package.
package mock_issue

import (
	context "context"
	reflect "reflect"

	issue "drassi.run/core/pkg/executor/command/issue"
	gomock "go.uber.org/mock/gomock"
)

// MockReporter is a mock of Reporter interface.
type MockReporter[R any] struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder[R]
	isgomock struct{}
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder[R any] struct {
	mock *MockReporter[R]
}

// NewMockReporter creates a new mock instance.
func NewMockReporter[R any](ctrl *gomock.Controller) *MockReporter[R] {
	mock := &MockReporter[R]{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder[R]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter[R]) EXPECT() *MockReporterMockRecorder[R] {
	return m.recorder
}

// AddIssue mocks base method.
func (m *MockReporter[R]) AddIssue(ctx context.Context, res R, issue *issue.Issue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIssue", ctx, res, issue)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIssue indicates an expected call of AddIssue.
func (mr *MockReporterMockRecorder[R]) AddIssue(ctx, res, issue any) *MockReporterAddIssueCall[R] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIssue", reflect.TypeOf((*MockReporter[R])(nil).AddIssue), ctx, res, issue)
	return &MockReporterAddIssueCall[R]{Call: call}
}

// MockReporterAddIssueCall wrap *gomock.Call
type MockReporterAddIssueCall[R any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterAddIssueCall[R]) Return(arg0 error) *MockReporterAddIssueCall[R] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterAddIssueCall[R]) Do(f func(context.Context, R, *issue.Issue) error) *MockReporterAddIssueCall[R] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterAddIssueCall[R]) DoAndReturn(f func(context.Context, R, *issue.Issue) error) *MockReporterAddIssueCall[R] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
