// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/runtime/provision/operations.go
//
// Generated by this command:
//
//	mockgen -typed -destination=runtime/provision/operations.go -source=../pkg/runtime/provision/operations.go
//

// Package mock_provision is a generated GoMock package.
package mock_provision

import (
	reflect "reflect"

	provision "drassi.run/core/pkg/runtime/provision"
	sandboxer "drassi.run/core/pkg/sandboxer"
	gomock "go.uber.org/mock/gomock"
)

// MockOperation is a mock of Operation interface.
type MockOperation[Req any] struct {
	ctrl     *gomock.Controller
	recorder *MockOperationMockRecorder[Req]
	isgomock struct{}
}

// MockOperationMockRecorder is the mock recorder for MockOperation.
type MockOperationMockRecorder[Req any] struct {
	mock *MockOperation[Req]
}

// NewMockOperation creates a new mock instance.
func NewMockOperation[Req any](ctrl *gomock.Controller) *MockOperation[Req] {
	mock := &MockOperation[Req]{ctrl: ctrl}
	mock.recorder = &MockOperationMockRecorder[Req]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperation[Req]) EXPECT() *MockOperationMockRecorder[Req] {
	return m.recorder
}

// Name mocks base method.
func (m *MockOperation[Req]) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockOperationMockRecorder[Req]) Name() *MockOperationNameCall[Req] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockOperation[Req])(nil).Name))
	return &MockOperationNameCall[Req]{Call: call}
}

// MockOperationNameCall wrap *gomock.Call
type MockOperationNameCall[Req any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationNameCall[Req]) Return(arg0 string) *MockOperationNameCall[Req] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationNameCall[Req]) Do(f func() string) *MockOperationNameCall[Req] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationNameCall[Req]) DoAndReturn(f func() string) *MockOperationNameCall[Req] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PostLaunch mocks base method.
func (m *MockOperation[Req]) PostLaunch(pctx *provision.Context, sb sandboxer.Sandbox) (sandboxer.Sandbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostLaunch", pctx, sb)
	ret0, _ := ret[0].(sandboxer.Sandbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostLaunch indicates an expected call of PostLaunch.
func (mr *MockOperationMockRecorder[Req]) PostLaunch(pctx, sb any) *MockOperationPostLaunchCall[Req] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostLaunch", reflect.TypeOf((*MockOperation[Req])(nil).PostLaunch), pctx, sb)
	return &MockOperationPostLaunchCall[Req]{Call: call}
}

// MockOperationPostLaunchCall wrap *gomock.Call
type MockOperationPostLaunchCall[Req any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationPostLaunchCall[Req]) Return(arg0 sandboxer.Sandbox, arg1 error) *MockOperationPostLaunchCall[Req] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationPostLaunchCall[Req]) Do(f func(*provision.Context, sandboxer.Sandbox) (sandboxer.Sandbox, error)) *MockOperationPostLaunchCall[Req] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationPostLaunchCall[Req]) DoAndReturn(f func(*provision.Context, sandboxer.Sandbox) (sandboxer.Sandbox, error)) *MockOperationPostLaunchCall[Req] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PreLaunch mocks base method.
func (m *MockOperation[Req]) PreLaunch(pctx *provision.Context, req Req) (Req, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreLaunch", pctx, req)
	ret0, _ := ret[0].(Req)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreLaunch indicates an expected call of PreLaunch.
func (mr *MockOperationMockRecorder[Req]) PreLaunch(pctx, req any) *MockOperationPreLaunchCall[Req] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreLaunch", reflect.TypeOf((*MockOperation[Req])(nil).PreLaunch), pctx, req)
	return &MockOperationPreLaunchCall[Req]{Call: call}
}

// MockOperationPreLaunchCall wrap *gomock.Call
type MockOperationPreLaunchCall[Req any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationPreLaunchCall[Req]) Return(arg0 Req, arg1 error) *MockOperationPreLaunchCall[Req] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationPreLaunchCall[Req]) Do(f func(*provision.Context, Req) (Req, error)) *MockOperationPreLaunchCall[Req] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationPreLaunchCall[Req]) DoAndReturn(f func(*provision.Context, Req) (Req, error)) *MockOperationPreLaunchCall[Req] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Prepare mocks base method.
func (m *MockOperation[Req]) Prepare(pctx *provision.Context) (sandboxer.Cleanup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare", pctx)
	ret0, _ := ret[0].(sandboxer.Cleanup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prepare indicates an expected call of Prepare.
func (mr *MockOperationMockRecorder[Req]) Prepare(pctx any) *MockOperationPrepareCall[Req] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockOperation[Req])(nil).Prepare), pctx)
	return &MockOperationPrepareCall[Req]{Call: call}
}

// MockOperationPrepareCall wrap *gomock.Call
type MockOperationPrepareCall[Req any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationPrepareCall[Req]) Return(arg0 sandboxer.Cleanup, arg1 error) *MockOperationPrepareCall[Req] {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationPrepareCall[Req]) Do(f func(*provision.Context) (sandboxer.Cleanup, error)) *MockOperationPrepareCall[Req] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationPrepareCall[Req]) DoAndReturn(f func(*provision.Context) (sandboxer.Cleanup, error)) *MockOperationPrepareCall[Req] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
