// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/executor_job.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/executor_job.go -destination=executor/executor_job.go -typed
//

// Package mock_executor is a generated GoMock package.
package mock_executor

import (
	context "context"
	reflect "reflect"

	executor "drassi.run/core/pkg/executor"
	records "drassi.run/core/pkg/model/records"
	dig "go.uber.org/dig"
	gomock "go.uber.org/mock/gomock"
)

// MockJobExecutor is a mock of JobExecutor interface.
type MockJobExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockJobExecutorMockRecorder
	isgomock struct{}
}

// MockJobExecutorMockRecorder is the mock recorder for MockJobExecutor.
type MockJobExecutorMockRecorder struct {
	mock *MockJobExecutor
}

// NewMockJobExecutor creates a new mock instance.
func NewMockJobExecutor(ctrl *gomock.Controller) *MockJobExecutor {
	mock := &MockJobExecutor{ctrl: ctrl}
	mock.recorder = &MockJobExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobExecutor) EXPECT() *MockJobExecutorMockRecorder {
	return m.recorder
}

// AddPath mocks base method.
func (m *MockJobExecutor) AddPath(paths []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPath", paths)
}

// AddPath indicates an expected call of AddPath.
func (mr *MockJobExecutorMockRecorder) AddPath(paths any) *MockJobExecutorAddPathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPath", reflect.TypeOf((*MockJobExecutor)(nil).AddPath), paths)
	return &MockJobExecutorAddPathCall{Call: call}
}

// MockJobExecutorAddPathCall wrap *gomock.Call
type MockJobExecutorAddPathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorAddPathCall) Return() *MockJobExecutorAddPathCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorAddPathCall) Do(f func([]string)) *MockJobExecutorAddPathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorAddPathCall) DoAndReturn(f func([]string)) *MockJobExecutorAddPathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Finalize mocks base method.
func (m *MockJobExecutor) Finalize(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Finalize", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Finalize indicates an expected call of Finalize.
func (mr *MockJobExecutorMockRecorder) Finalize(ctx any) *MockJobExecutorFinalizeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockJobExecutor)(nil).Finalize), ctx)
	return &MockJobExecutorFinalizeCall{Call: call}
}

// MockJobExecutorFinalizeCall wrap *gomock.Call
type MockJobExecutorFinalizeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorFinalizeCall) Return(arg0 error) *MockJobExecutorFinalizeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorFinalizeCall) Do(f func(context.Context) error) *MockJobExecutorFinalizeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorFinalizeCall) DoAndReturn(f func(context.Context) error) *MockJobExecutorFinalizeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Initialize mocks base method.
func (m *MockJobExecutor) Initialize(ctx context.Context, scope *dig.Scope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", ctx, scope)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockJobExecutorMockRecorder) Initialize(ctx, scope any) *MockJobExecutorInitializeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockJobExecutor)(nil).Initialize), ctx, scope)
	return &MockJobExecutorInitializeCall{Call: call}
}

// MockJobExecutorInitializeCall wrap *gomock.Call
type MockJobExecutorInitializeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorInitializeCall) Return(arg0 error) *MockJobExecutorInitializeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorInitializeCall) Do(f func(context.Context, *dig.Scope) error) *MockJobExecutorInitializeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorInitializeCall) DoAndReturn(f func(context.Context, *dig.Scope) error) *MockJobExecutorInitializeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// JobRun mocks base method.
func (m *MockJobExecutor) JobRun() *executor.JobRun {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobRun")
	ret0, _ := ret[0].(*executor.JobRun)
	return ret0
}

// JobRun indicates an expected call of JobRun.
func (mr *MockJobExecutorMockRecorder) JobRun() *MockJobExecutorJobRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobRun", reflect.TypeOf((*MockJobExecutor)(nil).JobRun))
	return &MockJobExecutorJobRunCall{Call: call}
}

// MockJobExecutorJobRunCall wrap *gomock.Call
type MockJobExecutorJobRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorJobRunCall) Return(arg0 *executor.JobRun) *MockJobExecutorJobRunCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorJobRunCall) Do(f func() *executor.JobRun) *MockJobExecutorJobRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorJobRunCall) DoAndReturn(f func() *executor.JobRun) *MockJobExecutorJobRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RunJob mocks base method.
func (m *MockJobExecutor) RunJob(ctx context.Context) *records.Job {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunJob", ctx)
	ret0, _ := ret[0].(*records.Job)
	return ret0
}

// RunJob indicates an expected call of RunJob.
func (mr *MockJobExecutorMockRecorder) RunJob(ctx any) *MockJobExecutorRunJobCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunJob", reflect.TypeOf((*MockJobExecutor)(nil).RunJob), ctx)
	return &MockJobExecutorRunJobCall{Call: call}
}

// MockJobExecutorRunJobCall wrap *gomock.Call
type MockJobExecutorRunJobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorRunJobCall) Return(arg0 *records.Job) *MockJobExecutorRunJobCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorRunJobCall) Do(f func(context.Context) *records.Job) *MockJobExecutorRunJobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorRunJobCall) DoAndReturn(f func(context.Context) *records.Job) *MockJobExecutorRunJobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetEnv mocks base method.
func (m *MockJobExecutor) SetEnv(env map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEnv", env)
}

// SetEnv indicates an expected call of SetEnv.
func (mr *MockJobExecutorMockRecorder) SetEnv(env any) *MockJobExecutorSetEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnv", reflect.TypeOf((*MockJobExecutor)(nil).SetEnv), env)
	return &MockJobExecutorSetEnvCall{Call: call}
}

// MockJobExecutorSetEnvCall wrap *gomock.Call
type MockJobExecutorSetEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorSetEnvCall) Return() *MockJobExecutorSetEnvCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorSetEnvCall) Do(f func(map[string]string)) *MockJobExecutorSetEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorSetEnvCall) DoAndReturn(f func(map[string]string)) *MockJobExecutorSetEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetStatus mocks base method.
func (m *MockJobExecutor) SetStatus(status records.Result) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStatus", status)
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockJobExecutorMockRecorder) SetStatus(status any) *MockJobExecutorSetStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockJobExecutor)(nil).SetStatus), status)
	return &MockJobExecutorSetStatusCall{Call: call}
}

// MockJobExecutorSetStatusCall wrap *gomock.Call
type MockJobExecutorSetStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorSetStatusCall) Return() *MockJobExecutorSetStatusCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorSetStatusCall) Do(f func(records.Result)) *MockJobExecutorSetStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorSetStatusCall) DoAndReturn(f func(records.Result)) *MockJobExecutorSetStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Status mocks base method.
func (m *MockJobExecutor) Status() records.Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(records.Result)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockJobExecutorMockRecorder) Status() *MockJobExecutorStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockJobExecutor)(nil).Status))
	return &MockJobExecutorStatusCall{Call: call}
}

// MockJobExecutorStatusCall wrap *gomock.Call
type MockJobExecutorStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorStatusCall) Return(arg0 records.Result) *MockJobExecutorStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorStatusCall) Do(f func() records.Result) *MockJobExecutorStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorStatusCall) DoAndReturn(f func() records.Result) *MockJobExecutorStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
