// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/executor_step.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/executor_step.go -destination=executor/executor_step.go -typed
//

// Package mock_executor is a generated GoMock package.
package mock_executor

import (
	context "context"
	io "io"
	reflect "reflect"

	executor "drassi.run/core/pkg/executor"
	records "drassi.run/core/pkg/model/records"
	dig "go.uber.org/dig"
	gomock "go.uber.org/mock/gomock"
)

// MockStepExecutor is a mock of StepExecutor interface.
type MockStepExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockStepExecutorMockRecorder
}

// MockStepExecutorMockRecorder is the mock recorder for MockStepExecutor.
type MockStepExecutorMockRecorder struct {
	mock *MockStepExecutor
}

// NewMockStepExecutor creates a new mock instance.
func NewMockStepExecutor(ctrl *gomock.Controller) *MockStepExecutor {
	mock := &MockStepExecutor{ctrl: ctrl}
	mock.recorder = &MockStepExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStepExecutor) EXPECT() *MockStepExecutorMockRecorder {
	return m.recorder
}

// ChildExecutor mocks base method.
func (m *MockStepExecutor) ChildExecutor(id string) executor.StepExecutor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChildExecutor", id)
	ret0, _ := ret[0].(executor.StepExecutor)
	return ret0
}

// ChildExecutor indicates an expected call of ChildExecutor.
func (mr *MockStepExecutorMockRecorder) ChildExecutor(id any) *MockStepExecutorChildExecutorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChildExecutor", reflect.TypeOf((*MockStepExecutor)(nil).ChildExecutor), id)
	return &MockStepExecutorChildExecutorCall{Call: call}
}

// MockStepExecutorChildExecutorCall wrap *gomock.Call
type MockStepExecutorChildExecutorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorChildExecutorCall) Return(arg0 executor.StepExecutor) *MockStepExecutorChildExecutorCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorChildExecutorCall) Do(f func(string) executor.StepExecutor) *MockStepExecutorChildExecutorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorChildExecutorCall) DoAndReturn(f func(string) executor.StepExecutor) *MockStepExecutorChildExecutorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ComposeEnv mocks base method.
func (m *MockStepExecutor) ComposeEnv() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComposeEnv")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// ComposeEnv indicates an expected call of ComposeEnv.
func (mr *MockStepExecutorMockRecorder) ComposeEnv() *MockStepExecutorComposeEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComposeEnv", reflect.TypeOf((*MockStepExecutor)(nil).ComposeEnv))
	return &MockStepExecutorComposeEnvCall{Call: call}
}

// MockStepExecutorComposeEnvCall wrap *gomock.Call
type MockStepExecutorComposeEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorComposeEnvCall) Return(arg0 map[string]string) *MockStepExecutorComposeEnvCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorComposeEnvCall) Do(f func() map[string]string) *MockStepExecutorComposeEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorComposeEnvCall) DoAndReturn(f func() map[string]string) *MockStepExecutorComposeEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Context mocks base method.
func (m *MockStepExecutor) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockStepExecutorMockRecorder) Context() *MockStepExecutorContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockStepExecutor)(nil).Context))
	return &MockStepExecutorContextCall{Call: call}
}

// MockStepExecutorContextCall wrap *gomock.Call
type MockStepExecutorContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorContextCall) Return(arg0 context.Context) *MockStepExecutorContextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorContextCall) Do(f func() context.Context) *MockStepExecutorContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorContextCall) DoAndReturn(f func() context.Context) *MockStepExecutorContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateStepSummary mocks base method.
func (m *MockStepExecutor) CreateStepSummary(r io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStepSummary", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStepSummary indicates an expected call of CreateStepSummary.
func (mr *MockStepExecutorMockRecorder) CreateStepSummary(r any) *MockStepExecutorCreateStepSummaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStepSummary", reflect.TypeOf((*MockStepExecutor)(nil).CreateStepSummary), r)
	return &MockStepExecutorCreateStepSummaryCall{Call: call}
}

// MockStepExecutorCreateStepSummaryCall wrap *gomock.Call
type MockStepExecutorCreateStepSummaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorCreateStepSummaryCall) Return(arg0 error) *MockStepExecutorCreateStepSummaryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorCreateStepSummaryCall) Do(f func(io.Reader) error) *MockStepExecutorCreateStepSummaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorCreateStepSummaryCall) DoAndReturn(f func(io.Reader) error) *MockStepExecutorCreateStepSummaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Initialize mocks base method.
func (m *MockStepExecutor) Initialize(scope *dig.Scope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", scope)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockStepExecutorMockRecorder) Initialize(scope any) *MockStepExecutorInitializeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockStepExecutor)(nil).Initialize), scope)
	return &MockStepExecutorInitializeCall{Call: call}
}

// MockStepExecutorInitializeCall wrap *gomock.Call
type MockStepExecutorInitializeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorInitializeCall) Return(arg0 error) *MockStepExecutorInitializeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorInitializeCall) Do(f func(*dig.Scope) error) *MockStepExecutorInitializeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorInitializeCall) DoAndReturn(f func(*dig.Scope) error) *MockStepExecutorInitializeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// JobExecutor mocks base method.
func (m *MockStepExecutor) JobExecutor() executor.JobExecutor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobExecutor")
	ret0, _ := ret[0].(executor.JobExecutor)
	return ret0
}

// JobExecutor indicates an expected call of JobExecutor.
func (mr *MockStepExecutorMockRecorder) JobExecutor() *MockStepExecutorJobExecutorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobExecutor", reflect.TypeOf((*MockStepExecutor)(nil).JobExecutor))
	return &MockStepExecutorJobExecutorCall{Call: call}
}

// MockStepExecutorJobExecutorCall wrap *gomock.Call
type MockStepExecutorJobExecutorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorJobExecutorCall) Return(arg0 executor.JobExecutor) *MockStepExecutorJobExecutorCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorJobExecutorCall) Do(f func() executor.JobExecutor) *MockStepExecutorJobExecutorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorJobExecutorCall) DoAndReturn(f func() executor.JobExecutor) *MockStepExecutorJobExecutorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NewChildExecutor mocks base method.
func (m *MockStepExecutor) NewChildExecutor(stepRun executor.StepRun) executor.StepExecutor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewChildExecutor", stepRun)
	ret0, _ := ret[0].(executor.StepExecutor)
	return ret0
}

// NewChildExecutor indicates an expected call of NewChildExecutor.
func (mr *MockStepExecutorMockRecorder) NewChildExecutor(stepRun any) *MockStepExecutorNewChildExecutorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewChildExecutor", reflect.TypeOf((*MockStepExecutor)(nil).NewChildExecutor), stepRun)
	return &MockStepExecutorNewChildExecutorCall{Call: call}
}

// MockStepExecutorNewChildExecutorCall wrap *gomock.Call
type MockStepExecutorNewChildExecutorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorNewChildExecutorCall) Return(arg0 executor.StepExecutor) *MockStepExecutorNewChildExecutorCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorNewChildExecutorCall) Do(f func(executor.StepRun) executor.StepExecutor) *MockStepExecutorNewChildExecutorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorNewChildExecutorCall) DoAndReturn(f func(executor.StepRun) executor.StepExecutor) *MockStepExecutorNewChildExecutorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ParentExecutor mocks base method.
func (m *MockStepExecutor) ParentExecutor() executor.StepExecutor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParentExecutor")
	ret0, _ := ret[0].(executor.StepExecutor)
	return ret0
}

// ParentExecutor indicates an expected call of ParentExecutor.
func (mr *MockStepExecutorMockRecorder) ParentExecutor() *MockStepExecutorParentExecutorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParentExecutor", reflect.TypeOf((*MockStepExecutor)(nil).ParentExecutor))
	return &MockStepExecutorParentExecutorCall{Call: call}
}

// MockStepExecutorParentExecutorCall wrap *gomock.Call
type MockStepExecutorParentExecutorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorParentExecutorCall) Return(arg0 executor.StepExecutor) *MockStepExecutorParentExecutorCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorParentExecutorCall) Do(f func() executor.StepExecutor) *MockStepExecutorParentExecutorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorParentExecutorCall) DoAndReturn(f func() executor.StepExecutor) *MockStepExecutorParentExecutorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RunStep mocks base method.
func (m *MockStepExecutor) RunStep(fn func(executor.StepRun) *executor.Task) *records.Step {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunStep", fn)
	ret0, _ := ret[0].(*records.Step)
	return ret0
}

// RunStep indicates an expected call of RunStep.
func (mr *MockStepExecutorMockRecorder) RunStep(fn any) *MockStepExecutorRunStepCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunStep", reflect.TypeOf((*MockStepExecutor)(nil).RunStep), fn)
	return &MockStepExecutorRunStepCall{Call: call}
}

// MockStepExecutorRunStepCall wrap *gomock.Call
type MockStepExecutorRunStepCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorRunStepCall) Return(arg0 *records.Step) *MockStepExecutorRunStepCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorRunStepCall) Do(f func(func(executor.StepRun) *executor.Task) *records.Step) *MockStepExecutorRunStepCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorRunStepCall) DoAndReturn(f func(func(executor.StepRun) *executor.Task) *records.Step) *MockStepExecutorRunStepCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveState mocks base method.
func (m *MockStepExecutor) SaveState(state map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveState", state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveState indicates an expected call of SaveState.
func (mr *MockStepExecutorMockRecorder) SaveState(state any) *MockStepExecutorSaveStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveState", reflect.TypeOf((*MockStepExecutor)(nil).SaveState), state)
	return &MockStepExecutorSaveStateCall{Call: call}
}

// MockStepExecutorSaveStateCall wrap *gomock.Call
type MockStepExecutorSaveStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorSaveStateCall) Return(arg0 error) *MockStepExecutorSaveStateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorSaveStateCall) Do(f func(map[string]string) error) *MockStepExecutorSaveStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorSaveStateCall) DoAndReturn(f func(map[string]string) error) *MockStepExecutorSaveStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetContext mocks base method.
func (m *MockStepExecutor) SetContext(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetContext", ctx)
}

// SetContext indicates an expected call of SetContext.
func (mr *MockStepExecutorMockRecorder) SetContext(ctx any) *MockStepExecutorSetContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContext", reflect.TypeOf((*MockStepExecutor)(nil).SetContext), ctx)
	return &MockStepExecutorSetContextCall{Call: call}
}

// MockStepExecutorSetContextCall wrap *gomock.Call
type MockStepExecutorSetContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorSetContextCall) Return() *MockStepExecutorSetContextCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorSetContextCall) Do(f func(context.Context)) *MockStepExecutorSetContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorSetContextCall) DoAndReturn(f func(context.Context)) *MockStepExecutorSetContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetEnv mocks base method.
func (m *MockStepExecutor) SetEnv(env map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEnv", env)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEnv indicates an expected call of SetEnv.
func (mr *MockStepExecutorMockRecorder) SetEnv(env any) *MockStepExecutorSetEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnv", reflect.TypeOf((*MockStepExecutor)(nil).SetEnv), env)
	return &MockStepExecutorSetEnvCall{Call: call}
}

// MockStepExecutorSetEnvCall wrap *gomock.Call
type MockStepExecutorSetEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorSetEnvCall) Return(arg0 error) *MockStepExecutorSetEnvCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorSetEnvCall) Do(f func(map[string]string) error) *MockStepExecutorSetEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorSetEnvCall) DoAndReturn(f func(map[string]string) error) *MockStepExecutorSetEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetOutput mocks base method.
func (m *MockStepExecutor) SetOutput(output map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOutput", output)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOutput indicates an expected call of SetOutput.
func (mr *MockStepExecutorMockRecorder) SetOutput(output any) *MockStepExecutorSetOutputCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOutput", reflect.TypeOf((*MockStepExecutor)(nil).SetOutput), output)
	return &MockStepExecutorSetOutputCall{Call: call}
}

// MockStepExecutorSetOutputCall wrap *gomock.Call
type MockStepExecutorSetOutputCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorSetOutputCall) Return(arg0 error) *MockStepExecutorSetOutputCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorSetOutputCall) Do(f func(map[string]string) error) *MockStepExecutorSetOutputCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorSetOutputCall) DoAndReturn(f func(map[string]string) error) *MockStepExecutorSetOutputCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetStatus mocks base method.
func (m *MockStepExecutor) SetStatus(status records.Result) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStatus", status)
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockStepExecutorMockRecorder) SetStatus(status any) *MockStepExecutorSetStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockStepExecutor)(nil).SetStatus), status)
	return &MockStepExecutorSetStatusCall{Call: call}
}

// MockStepExecutorSetStatusCall wrap *gomock.Call
type MockStepExecutorSetStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorSetStatusCall) Return() *MockStepExecutorSetStatusCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorSetStatusCall) Do(f func(records.Result)) *MockStepExecutorSetStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorSetStatusCall) DoAndReturn(f func(records.Result)) *MockStepExecutorSetStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StepRun mocks base method.
func (m *MockStepExecutor) StepRun() executor.StepRun {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StepRun")
	ret0, _ := ret[0].(executor.StepRun)
	return ret0
}

// StepRun indicates an expected call of StepRun.
func (mr *MockStepExecutorMockRecorder) StepRun() *MockStepExecutorStepRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StepRun", reflect.TypeOf((*MockStepExecutor)(nil).StepRun))
	return &MockStepExecutorStepRunCall{Call: call}
}

// MockStepExecutorStepRunCall wrap *gomock.Call
type MockStepExecutorStepRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorStepRunCall) Return(arg0 executor.StepRun) *MockStepExecutorStepRunCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorStepRunCall) Do(f func() executor.StepRun) *MockStepExecutorStepRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorStepRunCall) DoAndReturn(f func() executor.StepRun) *MockStepExecutorStepRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
