// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/executor_step.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/executor_step.go -destination=executor/executor_step.go -typed
//

// Package mock_executor is a generated GoMock package.
package mock_executor

import (
	context "context"
	io "io"
	reflect "reflect"

	executor "drassi.run/core/pkg/executor"
	records "drassi.run/core/pkg/model/records"
	dig "go.uber.org/dig"
	gomock "go.uber.org/mock/gomock"
)

// MockStepExecutor is a mock of StepExecutor interface.
type MockStepExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockStepExecutorMockRecorder
	isgomock struct{}
}

// MockStepExecutorMockRecorder is the mock recorder for MockStepExecutor.
type MockStepExecutorMockRecorder struct {
	mock *MockStepExecutor
}

// NewMockStepExecutor creates a new mock instance.
func NewMockStepExecutor(ctrl *gomock.Controller) *MockStepExecutor {
	mock := &MockStepExecutor{ctrl: ctrl}
	mock.recorder = &MockStepExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStepExecutor) EXPECT() *MockStepExecutorMockRecorder {
	return m.recorder
}

// ComposeEnv mocks base method.
func (m *MockStepExecutor) ComposeEnv(systemEnv bool) map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComposeEnv", systemEnv)
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// ComposeEnv indicates an expected call of ComposeEnv.
func (mr *MockStepExecutorMockRecorder) ComposeEnv(systemEnv any) *MockStepExecutorComposeEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComposeEnv", reflect.TypeOf((*MockStepExecutor)(nil).ComposeEnv), systemEnv)
	return &MockStepExecutorComposeEnvCall{Call: call}
}

// MockStepExecutorComposeEnvCall wrap *gomock.Call
type MockStepExecutorComposeEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorComposeEnvCall) Return(arg0 map[string]string) *MockStepExecutorComposeEnvCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorComposeEnvCall) Do(f func(bool) map[string]string) *MockStepExecutorComposeEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorComposeEnvCall) DoAndReturn(f func(bool) map[string]string) *MockStepExecutorComposeEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateStepSummary mocks base method.
func (m *MockStepExecutor) CreateStepSummary(r io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStepSummary", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStepSummary indicates an expected call of CreateStepSummary.
func (mr *MockStepExecutorMockRecorder) CreateStepSummary(r any) *MockStepExecutorCreateStepSummaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStepSummary", reflect.TypeOf((*MockStepExecutor)(nil).CreateStepSummary), r)
	return &MockStepExecutorCreateStepSummaryCall{Call: call}
}

// MockStepExecutorCreateStepSummaryCall wrap *gomock.Call
type MockStepExecutorCreateStepSummaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorCreateStepSummaryCall) Return(arg0 error) *MockStepExecutorCreateStepSummaryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorCreateStepSummaryCall) Do(f func(io.Reader) error) *MockStepExecutorCreateStepSummaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorCreateStepSummaryCall) DoAndReturn(f func(io.Reader) error) *MockStepExecutorCreateStepSummaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Initialize mocks base method.
func (m *MockStepExecutor) Initialize(ctx context.Context, scope *dig.Scope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", ctx, scope)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockStepExecutorMockRecorder) Initialize(ctx, scope any) *MockStepExecutorInitializeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockStepExecutor)(nil).Initialize), ctx, scope)
	return &MockStepExecutorInitializeCall{Call: call}
}

// MockStepExecutorInitializeCall wrap *gomock.Call
type MockStepExecutorInitializeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorInitializeCall) Return(arg0 error) *MockStepExecutorInitializeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorInitializeCall) Do(f func(context.Context, *dig.Scope) error) *MockStepExecutorInitializeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorInitializeCall) DoAndReturn(f func(context.Context, *dig.Scope) error) *MockStepExecutorInitializeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RunStep mocks base method.
func (m *MockStepExecutor) RunStep(ctx context.Context, fn func(executor.StepRun) *executor.Task) *records.Step {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunStep", ctx, fn)
	ret0, _ := ret[0].(*records.Step)
	return ret0
}

// RunStep indicates an expected call of RunStep.
func (mr *MockStepExecutorMockRecorder) RunStep(ctx, fn any) *MockStepExecutorRunStepCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunStep", reflect.TypeOf((*MockStepExecutor)(nil).RunStep), ctx, fn)
	return &MockStepExecutorRunStepCall{Call: call}
}

// MockStepExecutorRunStepCall wrap *gomock.Call
type MockStepExecutorRunStepCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorRunStepCall) Return(arg0 *records.Step) *MockStepExecutorRunStepCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorRunStepCall) Do(f func(context.Context, func(executor.StepRun) *executor.Task) *records.Step) *MockStepExecutorRunStepCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorRunStepCall) DoAndReturn(f func(context.Context, func(executor.StepRun) *executor.Task) *records.Step) *MockStepExecutorRunStepCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveState mocks base method.
func (m *MockStepExecutor) SaveState(state map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveState", state)
}

// SaveState indicates an expected call of SaveState.
func (mr *MockStepExecutorMockRecorder) SaveState(state any) *MockStepExecutorSaveStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveState", reflect.TypeOf((*MockStepExecutor)(nil).SaveState), state)
	return &MockStepExecutorSaveStateCall{Call: call}
}

// MockStepExecutorSaveStateCall wrap *gomock.Call
type MockStepExecutorSaveStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorSaveStateCall) Return() *MockStepExecutorSaveStateCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorSaveStateCall) Do(f func(map[string]string)) *MockStepExecutorSaveStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorSaveStateCall) DoAndReturn(f func(map[string]string)) *MockStepExecutorSaveStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetEnv mocks base method.
func (m *MockStepExecutor) SetEnv(env map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEnv", env)
}

// SetEnv indicates an expected call of SetEnv.
func (mr *MockStepExecutorMockRecorder) SetEnv(env any) *MockStepExecutorSetEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnv", reflect.TypeOf((*MockStepExecutor)(nil).SetEnv), env)
	return &MockStepExecutorSetEnvCall{Call: call}
}

// MockStepExecutorSetEnvCall wrap *gomock.Call
type MockStepExecutorSetEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorSetEnvCall) Return() *MockStepExecutorSetEnvCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorSetEnvCall) Do(f func(map[string]string)) *MockStepExecutorSetEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorSetEnvCall) DoAndReturn(f func(map[string]string)) *MockStepExecutorSetEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetOutput mocks base method.
func (m *MockStepExecutor) SetOutput(output map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOutput", output)
}

// SetOutput indicates an expected call of SetOutput.
func (mr *MockStepExecutorMockRecorder) SetOutput(output any) *MockStepExecutorSetOutputCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOutput", reflect.TypeOf((*MockStepExecutor)(nil).SetOutput), output)
	return &MockStepExecutorSetOutputCall{Call: call}
}

// MockStepExecutorSetOutputCall wrap *gomock.Call
type MockStepExecutorSetOutputCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorSetOutputCall) Return() *MockStepExecutorSetOutputCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorSetOutputCall) Do(f func(map[string]string)) *MockStepExecutorSetOutputCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorSetOutputCall) DoAndReturn(f func(map[string]string)) *MockStepExecutorSetOutputCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetStatus mocks base method.
func (m *MockStepExecutor) SetStatus(status records.Result) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStatus", status)
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockStepExecutorMockRecorder) SetStatus(status any) *MockStepExecutorSetStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockStepExecutor)(nil).SetStatus), status)
	return &MockStepExecutorSetStatusCall{Call: call}
}

// MockStepExecutorSetStatusCall wrap *gomock.Call
type MockStepExecutorSetStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorSetStatusCall) Return() *MockStepExecutorSetStatusCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorSetStatusCall) Do(f func(records.Result)) *MockStepExecutorSetStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorSetStatusCall) DoAndReturn(f func(records.Result)) *MockStepExecutorSetStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Status mocks base method.
func (m *MockStepExecutor) Status() records.Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(records.Result)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockStepExecutorMockRecorder) Status() *MockStepExecutorStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockStepExecutor)(nil).Status))
	return &MockStepExecutorStatusCall{Call: call}
}

// MockStepExecutorStatusCall wrap *gomock.Call
type MockStepExecutorStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorStatusCall) Return(arg0 records.Result) *MockStepExecutorStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorStatusCall) Do(f func() records.Result) *MockStepExecutorStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorStatusCall) DoAndReturn(f func() records.Result) *MockStepExecutorStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StepRun mocks base method.
func (m *MockStepExecutor) StepRun() executor.StepRun {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StepRun")
	ret0, _ := ret[0].(executor.StepRun)
	return ret0
}

// StepRun indicates an expected call of StepRun.
func (mr *MockStepExecutorMockRecorder) StepRun() *MockStepExecutorStepRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StepRun", reflect.TypeOf((*MockStepExecutor)(nil).StepRun))
	return &MockStepExecutorStepRunCall{Call: call}
}

// MockStepExecutorStepRunCall wrap *gomock.Call
type MockStepExecutorStepRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorStepRunCall) Return(arg0 executor.StepRun) *MockStepExecutorStepRunCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorStepRunCall) Do(f func() executor.StepRun) *MockStepExecutorStepRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorStepRunCall) DoAndReturn(f func() executor.StepRun) *MockStepExecutorStepRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
