// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/executor_job.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/executor_job.go -destination=executor/executor_job.go -typed
//

// Package mock_executor is a generated GoMock package.
package mock_executor

import (
	context "context"
	reflect "reflect"

	executor "drassi.run/core/pkg/executor"
	records "drassi.run/core/pkg/model/records"
	dig "go.uber.org/dig"
	gomock "go.uber.org/mock/gomock"
)

// MockJobExecutor is a mock of JobExecutor interface.
type MockJobExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockJobExecutorMockRecorder
}

// MockJobExecutorMockRecorder is the mock recorder for MockJobExecutor.
type MockJobExecutorMockRecorder struct {
	mock *MockJobExecutor
}

// NewMockJobExecutor creates a new mock instance.
func NewMockJobExecutor(ctrl *gomock.Controller) *MockJobExecutor {
	mock := &MockJobExecutor{ctrl: ctrl}
	mock.recorder = &MockJobExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobExecutor) EXPECT() *MockJobExecutorMockRecorder {
	return m.recorder
}

// AddPath mocks base method.
func (m *MockJobExecutor) AddPath(paths []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPath", paths)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPath indicates an expected call of AddPath.
func (mr *MockJobExecutorMockRecorder) AddPath(paths any) *MockJobExecutorAddPathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPath", reflect.TypeOf((*MockJobExecutor)(nil).AddPath), paths)
	return &MockJobExecutorAddPathCall{Call: call}
}

// MockJobExecutorAddPathCall wrap *gomock.Call
type MockJobExecutorAddPathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorAddPathCall) Return(arg0 error) *MockJobExecutorAddPathCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorAddPathCall) Do(f func([]string) error) *MockJobExecutorAddPathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorAddPathCall) DoAndReturn(f func([]string) error) *MockJobExecutorAddPathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Context mocks base method.
func (m *MockJobExecutor) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockJobExecutorMockRecorder) Context() *MockJobExecutorContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockJobExecutor)(nil).Context))
	return &MockJobExecutorContextCall{Call: call}
}

// MockJobExecutorContextCall wrap *gomock.Call
type MockJobExecutorContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorContextCall) Return(arg0 context.Context) *MockJobExecutorContextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorContextCall) Do(f func() context.Context) *MockJobExecutorContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorContextCall) DoAndReturn(f func() context.Context) *MockJobExecutorContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Finalize mocks base method.
func (m *MockJobExecutor) Finalize() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Finalize")
	ret0, _ := ret[0].(error)
	return ret0
}

// Finalize indicates an expected call of Finalize.
func (mr *MockJobExecutorMockRecorder) Finalize() *MockJobExecutorFinalizeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockJobExecutor)(nil).Finalize))
	return &MockJobExecutorFinalizeCall{Call: call}
}

// MockJobExecutorFinalizeCall wrap *gomock.Call
type MockJobExecutorFinalizeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorFinalizeCall) Return(arg0 error) *MockJobExecutorFinalizeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorFinalizeCall) Do(f func() error) *MockJobExecutorFinalizeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorFinalizeCall) DoAndReturn(f func() error) *MockJobExecutorFinalizeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Initialize mocks base method.
func (m *MockJobExecutor) Initialize(scope *dig.Scope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", scope)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockJobExecutorMockRecorder) Initialize(scope any) *MockJobExecutorInitializeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockJobExecutor)(nil).Initialize), scope)
	return &MockJobExecutorInitializeCall{Call: call}
}

// MockJobExecutorInitializeCall wrap *gomock.Call
type MockJobExecutorInitializeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorInitializeCall) Return(arg0 error) *MockJobExecutorInitializeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorInitializeCall) Do(f func(*dig.Scope) error) *MockJobExecutorInitializeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorInitializeCall) DoAndReturn(f func(*dig.Scope) error) *MockJobExecutorInitializeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// JobRun mocks base method.
func (m *MockJobExecutor) JobRun() *executor.JobRun {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobRun")
	ret0, _ := ret[0].(*executor.JobRun)
	return ret0
}

// JobRun indicates an expected call of JobRun.
func (mr *MockJobExecutorMockRecorder) JobRun() *MockJobExecutorJobRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobRun", reflect.TypeOf((*MockJobExecutor)(nil).JobRun))
	return &MockJobExecutorJobRunCall{Call: call}
}

// MockJobExecutorJobRunCall wrap *gomock.Call
type MockJobExecutorJobRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorJobRunCall) Return(arg0 *executor.JobRun) *MockJobExecutorJobRunCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorJobRunCall) Do(f func() *executor.JobRun) *MockJobExecutorJobRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorJobRunCall) DoAndReturn(f func() *executor.JobRun) *MockJobExecutorJobRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RunJob mocks base method.
func (m *MockJobExecutor) RunJob() *records.Job {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunJob")
	ret0, _ := ret[0].(*records.Job)
	return ret0
}

// RunJob indicates an expected call of RunJob.
func (mr *MockJobExecutorMockRecorder) RunJob() *MockJobExecutorRunJobCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunJob", reflect.TypeOf((*MockJobExecutor)(nil).RunJob))
	return &MockJobExecutorRunJobCall{Call: call}
}

// MockJobExecutorRunJobCall wrap *gomock.Call
type MockJobExecutorRunJobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorRunJobCall) Return(arg0 *records.Job) *MockJobExecutorRunJobCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorRunJobCall) Do(f func() *records.Job) *MockJobExecutorRunJobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorRunJobCall) DoAndReturn(f func() *records.Job) *MockJobExecutorRunJobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetContext mocks base method.
func (m *MockJobExecutor) SetContext(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetContext", ctx)
}

// SetContext indicates an expected call of SetContext.
func (mr *MockJobExecutorMockRecorder) SetContext(ctx any) *MockJobExecutorSetContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContext", reflect.TypeOf((*MockJobExecutor)(nil).SetContext), ctx)
	return &MockJobExecutorSetContextCall{Call: call}
}

// MockJobExecutorSetContextCall wrap *gomock.Call
type MockJobExecutorSetContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorSetContextCall) Return() *MockJobExecutorSetContextCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorSetContextCall) Do(f func(context.Context)) *MockJobExecutorSetContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorSetContextCall) DoAndReturn(f func(context.Context)) *MockJobExecutorSetContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetEnv mocks base method.
func (m *MockJobExecutor) SetEnv(env map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEnv", env)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEnv indicates an expected call of SetEnv.
func (mr *MockJobExecutorMockRecorder) SetEnv(env any) *MockJobExecutorSetEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnv", reflect.TypeOf((*MockJobExecutor)(nil).SetEnv), env)
	return &MockJobExecutorSetEnvCall{Call: call}
}

// MockJobExecutorSetEnvCall wrap *gomock.Call
type MockJobExecutorSetEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorSetEnvCall) Return(arg0 error) *MockJobExecutorSetEnvCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorSetEnvCall) Do(f func(map[string]string) error) *MockJobExecutorSetEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorSetEnvCall) DoAndReturn(f func(map[string]string) error) *MockJobExecutorSetEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetStatus mocks base method.
func (m *MockJobExecutor) SetStatus(status records.Result) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStatus", status)
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockJobExecutorMockRecorder) SetStatus(status any) *MockJobExecutorSetStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockJobExecutor)(nil).SetStatus), status)
	return &MockJobExecutorSetStatusCall{Call: call}
}

// MockJobExecutorSetStatusCall wrap *gomock.Call
type MockJobExecutorSetStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorSetStatusCall) Return() *MockJobExecutorSetStatusCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorSetStatusCall) Do(f func(records.Result)) *MockJobExecutorSetStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorSetStatusCall) DoAndReturn(f func(records.Result)) *MockJobExecutorSetStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SystemPaths mocks base method.
func (m *MockJobExecutor) SystemPaths() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemPaths")
	ret0, _ := ret[0].([]string)
	return ret0
}

// SystemPaths indicates an expected call of SystemPaths.
func (mr *MockJobExecutorMockRecorder) SystemPaths() *MockJobExecutorSystemPathsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemPaths", reflect.TypeOf((*MockJobExecutor)(nil).SystemPaths))
	return &MockJobExecutorSystemPathsCall{Call: call}
}

// MockJobExecutorSystemPathsCall wrap *gomock.Call
type MockJobExecutorSystemPathsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorSystemPathsCall) Return(arg0 []string) *MockJobExecutorSystemPathsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorSystemPathsCall) Do(f func() []string) *MockJobExecutorSystemPathsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorSystemPathsCall) DoAndReturn(f func() []string) *MockJobExecutorSystemPathsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
