// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/job_executor.go
//
// Generated by this command:
//
//	mockgen -typed -destination=executor/job_executor.go -source=../pkg/executor/job_executor.go
//

// Package mock_executor is a generated GoMock package.
package mock_executor

import (
	reflect "reflect"

	executor "drassi.run/core/pkg/executor"
	expression "drassi.run/core/pkg/expression"
	records "drassi.run/core/pkg/model/records"
	sandboxer "drassi.run/core/pkg/sandboxer"
	gomock "go.uber.org/mock/gomock"
)

// MockJobExecutor is a mock of JobExecutor interface.
type MockJobExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockJobExecutorMockRecorder
	isgomock struct{}
}

// MockJobExecutorMockRecorder is the mock recorder for MockJobExecutor.
type MockJobExecutorMockRecorder struct {
	mock *MockJobExecutor
}

// NewMockJobExecutor creates a new mock instance.
func NewMockJobExecutor(ctrl *gomock.Controller) *MockJobExecutor {
	mock := &MockJobExecutor{ctrl: ctrl}
	mock.recorder = &MockJobExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobExecutor) EXPECT() *MockJobExecutorMockRecorder {
	return m.recorder
}

// AddPath mocks base method.
func (m *MockJobExecutor) AddPath(paths []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPath", paths)
}

// AddPath indicates an expected call of AddPath.
func (mr *MockJobExecutorMockRecorder) AddPath(paths any) *MockJobExecutorAddPathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPath", reflect.TypeOf((*MockJobExecutor)(nil).AddPath), paths)
	return &MockJobExecutorAddPathCall{Call: call}
}

// MockJobExecutorAddPathCall wrap *gomock.Call
type MockJobExecutorAddPathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorAddPathCall) Return() *MockJobExecutorAddPathCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorAddPathCall) Do(f func([]string)) *MockJobExecutorAddPathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorAddPathCall) DoAndReturn(f func([]string)) *MockJobExecutorAddPathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateTask mocks base method.
func (m *MockJobExecutor) CreateTask() *executor.JobTask {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask")
	ret0, _ := ret[0].(*executor.JobTask)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockJobExecutorMockRecorder) CreateTask() *MockJobExecutorCreateTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockJobExecutor)(nil).CreateTask))
	return &MockJobExecutorCreateTaskCall{Call: call}
}

// MockJobExecutorCreateTaskCall wrap *gomock.Call
type MockJobExecutorCreateTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorCreateTaskCall) Return(arg0 *executor.JobTask) *MockJobExecutorCreateTaskCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorCreateTaskCall) Do(f func() *executor.JobTask) *MockJobExecutorCreateTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorCreateTaskCall) DoAndReturn(f func() *executor.JobTask) *MockJobExecutorCreateTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Env mocks base method.
func (m *MockJobExecutor) Env() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Env")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// Env indicates an expected call of Env.
func (mr *MockJobExecutorMockRecorder) Env() *MockJobExecutorEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*MockJobExecutor)(nil).Env))
	return &MockJobExecutorEnvCall{Call: call}
}

// MockJobExecutorEnvCall wrap *gomock.Call
type MockJobExecutorEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorEnvCall) Return(arg0 map[string]string) *MockJobExecutorEnvCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorEnvCall) Do(f func() map[string]string) *MockJobExecutorEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorEnvCall) DoAndReturn(f func() map[string]string) *MockJobExecutorEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExprEnv mocks base method.
func (m *MockJobExecutor) ExprEnv() expression.Env {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExprEnv")
	ret0, _ := ret[0].(expression.Env)
	return ret0
}

// ExprEnv indicates an expected call of ExprEnv.
func (mr *MockJobExecutorMockRecorder) ExprEnv() *MockJobExecutorExprEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExprEnv", reflect.TypeOf((*MockJobExecutor)(nil).ExprEnv))
	return &MockJobExecutorExprEnvCall{Call: call}
}

// MockJobExecutorExprEnvCall wrap *gomock.Call
type MockJobExecutorExprEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorExprEnvCall) Return(arg0 expression.Env) *MockJobExecutorExprEnvCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorExprEnvCall) Do(f func() expression.Env) *MockJobExecutorExprEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorExprEnvCall) DoAndReturn(f func() expression.Env) *MockJobExecutorExprEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Forge mocks base method.
func (m *MockJobExecutor) Forge() *records.Forge {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Forge")
	ret0, _ := ret[0].(*records.Forge)
	return ret0
}

// Forge indicates an expected call of Forge.
func (mr *MockJobExecutorMockRecorder) Forge() *MockJobExecutorForgeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Forge", reflect.TypeOf((*MockJobExecutor)(nil).Forge))
	return &MockJobExecutorForgeCall{Call: call}
}

// MockJobExecutorForgeCall wrap *gomock.Call
type MockJobExecutorForgeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorForgeCall) Return(arg0 *records.Forge) *MockJobExecutorForgeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorForgeCall) Do(f func() *records.Forge) *MockJobExecutorForgeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorForgeCall) DoAndReturn(f func() *records.Forge) *MockJobExecutorForgeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// JobSpec mocks base method.
func (m *MockJobExecutor) JobSpec() *executor.JobSpec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobSpec")
	ret0, _ := ret[0].(*executor.JobSpec)
	return ret0
}

// JobSpec indicates an expected call of JobSpec.
func (mr *MockJobExecutorMockRecorder) JobSpec() *MockJobExecutorJobSpecCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobSpec", reflect.TypeOf((*MockJobExecutor)(nil).JobSpec))
	return &MockJobExecutorJobSpecCall{Call: call}
}

// MockJobExecutorJobSpecCall wrap *gomock.Call
type MockJobExecutorJobSpecCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorJobSpecCall) Return(arg0 *executor.JobSpec) *MockJobExecutorJobSpecCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorJobSpecCall) Do(f func() *executor.JobSpec) *MockJobExecutorJobSpecCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorJobSpecCall) DoAndReturn(f func() *executor.JobSpec) *MockJobExecutorJobSpecCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Path mocks base method.
func (m *MockJobExecutor) Path() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Path indicates an expected call of Path.
func (mr *MockJobExecutorMockRecorder) Path() *MockJobExecutorPathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockJobExecutor)(nil).Path))
	return &MockJobExecutorPathCall{Call: call}
}

// MockJobExecutorPathCall wrap *gomock.Call
type MockJobExecutorPathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorPathCall) Return(arg0 []string) *MockJobExecutorPathCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorPathCall) Do(f func() []string) *MockJobExecutorPathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorPathCall) DoAndReturn(f func() []string) *MockJobExecutorPathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Sandbox mocks base method.
func (m *MockJobExecutor) Sandbox() sandboxer.Sandbox {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sandbox")
	ret0, _ := ret[0].(sandboxer.Sandbox)
	return ret0
}

// Sandbox indicates an expected call of Sandbox.
func (mr *MockJobExecutorMockRecorder) Sandbox() *MockJobExecutorSandboxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sandbox", reflect.TypeOf((*MockJobExecutor)(nil).Sandbox))
	return &MockJobExecutorSandboxCall{Call: call}
}

// MockJobExecutorSandboxCall wrap *gomock.Call
type MockJobExecutorSandboxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorSandboxCall) Return(arg0 sandboxer.Sandbox) *MockJobExecutorSandboxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorSandboxCall) Do(f func() sandboxer.Sandbox) *MockJobExecutorSandboxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorSandboxCall) DoAndReturn(f func() sandboxer.Sandbox) *MockJobExecutorSandboxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetEnv mocks base method.
func (m *MockJobExecutor) SetEnv(env map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEnv", env)
}

// SetEnv indicates an expected call of SetEnv.
func (mr *MockJobExecutorMockRecorder) SetEnv(env any) *MockJobExecutorSetEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnv", reflect.TypeOf((*MockJobExecutor)(nil).SetEnv), env)
	return &MockJobExecutorSetEnvCall{Call: call}
}

// MockJobExecutorSetEnvCall wrap *gomock.Call
type MockJobExecutorSetEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorSetEnvCall) Return() *MockJobExecutorSetEnvCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorSetEnvCall) Do(f func(map[string]string)) *MockJobExecutorSetEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorSetEnvCall) DoAndReturn(f func(map[string]string)) *MockJobExecutorSetEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
