// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/job_executor.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/job_executor.go -destination=executor/job_executor.go -typed
//

// Package mock_executor is a generated GoMock package.
package mock_executor

import (
	context "context"
	reflect "reflect"

	executor "drassi.run/core/pkg/executor"
	expression "drassi.run/core/pkg/expression"
	records "drassi.run/core/pkg/model/records"
	sandboxer "drassi.run/core/pkg/sandboxer"
	gomock "go.uber.org/mock/gomock"
)

// MockJobExecutor is a mock of JobExecutor interface.
type MockJobExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockJobExecutorMockRecorder
	isgomock struct{}
}

// MockJobExecutorMockRecorder is the mock recorder for MockJobExecutor.
type MockJobExecutorMockRecorder struct {
	mock *MockJobExecutor
}

// NewMockJobExecutor creates a new mock instance.
func NewMockJobExecutor(ctrl *gomock.Controller) *MockJobExecutor {
	mock := &MockJobExecutor{ctrl: ctrl}
	mock.recorder = &MockJobExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobExecutor) EXPECT() *MockJobExecutorMockRecorder {
	return m.recorder
}

// AddPath mocks base method.
func (m *MockJobExecutor) AddPath(paths []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPath", paths)
}

// AddPath indicates an expected call of AddPath.
func (mr *MockJobExecutorMockRecorder) AddPath(paths any) *MockJobExecutorAddPathCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPath", reflect.TypeOf((*MockJobExecutor)(nil).AddPath), paths)
	return &MockJobExecutorAddPathCall{Call: call}
}

// MockJobExecutorAddPathCall wrap *gomock.Call
type MockJobExecutorAddPathCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorAddPathCall) Return() *MockJobExecutorAddPathCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorAddPathCall) Do(f func([]string)) *MockJobExecutorAddPathCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorAddPathCall) DoAndReturn(f func([]string)) *MockJobExecutorAddPathCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Env mocks base method.
func (m *MockJobExecutor) Env() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Env")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// Env indicates an expected call of Env.
func (mr *MockJobExecutorMockRecorder) Env() *MockJobExecutorEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*MockJobExecutor)(nil).Env))
	return &MockJobExecutorEnvCall{Call: call}
}

// MockJobExecutorEnvCall wrap *gomock.Call
type MockJobExecutorEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorEnvCall) Return(arg0 map[string]string) *MockJobExecutorEnvCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorEnvCall) Do(f func() map[string]string) *MockJobExecutorEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorEnvCall) DoAndReturn(f func() map[string]string) *MockJobExecutorEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExprEnv mocks base method.
func (m *MockJobExecutor) ExprEnv() expression.Env {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExprEnv")
	ret0, _ := ret[0].(expression.Env)
	return ret0
}

// ExprEnv indicates an expected call of ExprEnv.
func (mr *MockJobExecutorMockRecorder) ExprEnv() *MockJobExecutorExprEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExprEnv", reflect.TypeOf((*MockJobExecutor)(nil).ExprEnv))
	return &MockJobExecutorExprEnvCall{Call: call}
}

// MockJobExecutorExprEnvCall wrap *gomock.Call
type MockJobExecutorExprEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorExprEnvCall) Return(arg0 expression.Env) *MockJobExecutorExprEnvCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorExprEnvCall) Do(f func() expression.Env) *MockJobExecutorExprEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorExprEnvCall) DoAndReturn(f func() expression.Env) *MockJobExecutorExprEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Finalize mocks base method.
func (m *MockJobExecutor) Finalize(ctx context.Context) (*records.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Finalize", ctx)
	ret0, _ := ret[0].(*records.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Finalize indicates an expected call of Finalize.
func (mr *MockJobExecutorMockRecorder) Finalize(ctx any) *MockJobExecutorFinalizeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockJobExecutor)(nil).Finalize), ctx)
	return &MockJobExecutorFinalizeCall{Call: call}
}

// MockJobExecutorFinalizeCall wrap *gomock.Call
type MockJobExecutorFinalizeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorFinalizeCall) Return(arg0 *records.Job, arg1 error) *MockJobExecutorFinalizeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorFinalizeCall) Do(f func(context.Context) (*records.Job, error)) *MockJobExecutorFinalizeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorFinalizeCall) DoAndReturn(f func(context.Context) (*records.Job, error)) *MockJobExecutorFinalizeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Initialize mocks base method.
func (m *MockJobExecutor) Initialize(ctx context.Context) (*records.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", ctx)
	ret0, _ := ret[0].(*records.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Initialize indicates an expected call of Initialize.
func (mr *MockJobExecutorMockRecorder) Initialize(ctx any) *MockJobExecutorInitializeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockJobExecutor)(nil).Initialize), ctx)
	return &MockJobExecutorInitializeCall{Call: call}
}

// MockJobExecutorInitializeCall wrap *gomock.Call
type MockJobExecutorInitializeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorInitializeCall) Return(arg0 *records.Job, arg1 error) *MockJobExecutorInitializeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorInitializeCall) Do(f func(context.Context) (*records.Job, error)) *MockJobExecutorInitializeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorInitializeCall) DoAndReturn(f func(context.Context) (*records.Job, error)) *MockJobExecutorInitializeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// JobSpec mocks base method.
func (m *MockJobExecutor) JobSpec() *executor.JobSpec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobSpec")
	ret0, _ := ret[0].(*executor.JobSpec)
	return ret0
}

// JobSpec indicates an expected call of JobSpec.
func (mr *MockJobExecutorMockRecorder) JobSpec() *MockJobExecutorJobSpecCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobSpec", reflect.TypeOf((*MockJobExecutor)(nil).JobSpec))
	return &MockJobExecutorJobSpecCall{Call: call}
}

// MockJobExecutorJobSpecCall wrap *gomock.Call
type MockJobExecutorJobSpecCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorJobSpecCall) Return(arg0 *executor.JobSpec) *MockJobExecutorJobSpecCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorJobSpecCall) Do(f func() *executor.JobSpec) *MockJobExecutorJobSpecCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorJobSpecCall) DoAndReturn(f func() *executor.JobSpec) *MockJobExecutorJobSpecCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RunJob mocks base method.
func (m *MockJobExecutor) RunJob(ctx context.Context) (*records.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunJob", ctx)
	ret0, _ := ret[0].(*records.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunJob indicates an expected call of RunJob.
func (mr *MockJobExecutorMockRecorder) RunJob(ctx any) *MockJobExecutorRunJobCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunJob", reflect.TypeOf((*MockJobExecutor)(nil).RunJob), ctx)
	return &MockJobExecutorRunJobCall{Call: call}
}

// MockJobExecutorRunJobCall wrap *gomock.Call
type MockJobExecutorRunJobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorRunJobCall) Return(arg0 *records.Job, arg1 error) *MockJobExecutorRunJobCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorRunJobCall) Do(f func(context.Context) (*records.Job, error)) *MockJobExecutorRunJobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorRunJobCall) DoAndReturn(f func(context.Context) (*records.Job, error)) *MockJobExecutorRunJobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Sandbox mocks base method.
func (m *MockJobExecutor) Sandbox() sandboxer.Sandbox {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sandbox")
	ret0, _ := ret[0].(sandboxer.Sandbox)
	return ret0
}

// Sandbox indicates an expected call of Sandbox.
func (mr *MockJobExecutorMockRecorder) Sandbox() *MockJobExecutorSandboxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sandbox", reflect.TypeOf((*MockJobExecutor)(nil).Sandbox))
	return &MockJobExecutorSandboxCall{Call: call}
}

// MockJobExecutorSandboxCall wrap *gomock.Call
type MockJobExecutorSandboxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorSandboxCall) Return(arg0 sandboxer.Sandbox) *MockJobExecutorSandboxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorSandboxCall) Do(f func() sandboxer.Sandbox) *MockJobExecutorSandboxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorSandboxCall) DoAndReturn(f func() sandboxer.Sandbox) *MockJobExecutorSandboxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetEnv mocks base method.
func (m *MockJobExecutor) SetEnv(env map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEnv", env)
}

// SetEnv indicates an expected call of SetEnv.
func (mr *MockJobExecutorMockRecorder) SetEnv(env any) *MockJobExecutorSetEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnv", reflect.TypeOf((*MockJobExecutor)(nil).SetEnv), env)
	return &MockJobExecutorSetEnvCall{Call: call}
}

// MockJobExecutorSetEnvCall wrap *gomock.Call
type MockJobExecutorSetEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorSetEnvCall) Return() *MockJobExecutorSetEnvCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorSetEnvCall) Do(f func(map[string]string)) *MockJobExecutorSetEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorSetEnvCall) DoAndReturn(f func(map[string]string)) *MockJobExecutorSetEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetStatus mocks base method.
func (m *MockJobExecutor) SetStatus(status records.Result) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStatus", status)
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockJobExecutorMockRecorder) SetStatus(status any) *MockJobExecutorSetStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockJobExecutor)(nil).SetStatus), status)
	return &MockJobExecutorSetStatusCall{Call: call}
}

// MockJobExecutorSetStatusCall wrap *gomock.Call
type MockJobExecutorSetStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorSetStatusCall) Return() *MockJobExecutorSetStatusCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorSetStatusCall) Do(f func(records.Result)) *MockJobExecutorSetStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorSetStatusCall) DoAndReturn(f func(records.Result)) *MockJobExecutorSetStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Status mocks base method.
func (m *MockJobExecutor) Status() records.Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(records.Result)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockJobExecutorMockRecorder) Status() *MockJobExecutorStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockJobExecutor)(nil).Status))
	return &MockJobExecutorStatusCall{Call: call}
}

// MockJobExecutorStatusCall wrap *gomock.Call
type MockJobExecutorStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorStatusCall) Return(arg0 records.Result) *MockJobExecutorStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorStatusCall) Do(f func() records.Result) *MockJobExecutorStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorStatusCall) DoAndReturn(f func() records.Result) *MockJobExecutorStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SystemEnv mocks base method.
func (m *MockJobExecutor) SystemEnv() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemEnv")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// SystemEnv indicates an expected call of SystemEnv.
func (mr *MockJobExecutorMockRecorder) SystemEnv() *MockJobExecutorSystemEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemEnv", reflect.TypeOf((*MockJobExecutor)(nil).SystemEnv))
	return &MockJobExecutorSystemEnvCall{Call: call}
}

// MockJobExecutorSystemEnvCall wrap *gomock.Call
type MockJobExecutorSystemEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorSystemEnvCall) Return(arg0 map[string]string) *MockJobExecutorSystemEnvCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorSystemEnvCall) Do(f func() map[string]string) *MockJobExecutorSystemEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorSystemEnvCall) DoAndReturn(f func() map[string]string) *MockJobExecutorSystemEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SystemPaths mocks base method.
func (m *MockJobExecutor) SystemPaths() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemPaths")
	ret0, _ := ret[0].([]string)
	return ret0
}

// SystemPaths indicates an expected call of SystemPaths.
func (mr *MockJobExecutorMockRecorder) SystemPaths() *MockJobExecutorSystemPathsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemPaths", reflect.TypeOf((*MockJobExecutor)(nil).SystemPaths))
	return &MockJobExecutorSystemPathsCall{Call: call}
}

// MockJobExecutorSystemPathsCall wrap *gomock.Call
type MockJobExecutorSystemPathsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockJobExecutorSystemPathsCall) Return(arg0 []string) *MockJobExecutorSystemPathsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockJobExecutorSystemPathsCall) Do(f func() []string) *MockJobExecutorSystemPathsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockJobExecutorSystemPathsCall) DoAndReturn(f func() []string) *MockJobExecutorSystemPathsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
