// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/stack.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/stack.go -destination=executor/stack.go -typed
//

// Package mock_executor is a generated GoMock package.
package mock_executor

import (
	reflect "reflect"

	executor "drassi.run/core/pkg/executor"
	gomock "go.uber.org/mock/gomock"
)

// MockStack is a mock of Stack interface.
type MockStack struct {
	ctrl     *gomock.Controller
	recorder *MockStackMockRecorder
	isgomock struct{}
}

// MockStackMockRecorder is the mock recorder for MockStack.
type MockStackMockRecorder struct {
	mock *MockStack
}

// NewMockStack creates a new mock instance.
func NewMockStack(ctrl *gomock.Controller) *MockStack {
	mock := &MockStack{ctrl: ctrl}
	mock.recorder = &MockStackMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStack) EXPECT() *MockStackMockRecorder {
	return m.recorder
}

// Job mocks base method.
func (m *MockStack) Job() executor.JobExecutor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Job")
	ret0, _ := ret[0].(executor.JobExecutor)
	return ret0
}

// Job indicates an expected call of Job.
func (mr *MockStackMockRecorder) Job() *MockStackJobCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Job", reflect.TypeOf((*MockStack)(nil).Job))
	return &MockStackJobCall{Call: call}
}

// MockStackJobCall wrap *gomock.Call
type MockStackJobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStackJobCall) Return(arg0 executor.JobExecutor) *MockStackJobCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStackJobCall) Do(f func() executor.JobExecutor) *MockStackJobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStackJobCall) DoAndReturn(f func() executor.JobExecutor) *MockStackJobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Leaf mocks base method.
func (m *MockStack) Leaf() executor.StepExecutor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leaf")
	ret0, _ := ret[0].(executor.StepExecutor)
	return ret0
}

// Leaf indicates an expected call of Leaf.
func (mr *MockStackMockRecorder) Leaf() *MockStackLeafCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leaf", reflect.TypeOf((*MockStack)(nil).Leaf))
	return &MockStackLeafCall{Call: call}
}

// MockStackLeafCall wrap *gomock.Call
type MockStackLeafCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStackLeafCall) Return(arg0 executor.StepExecutor) *MockStackLeafCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStackLeafCall) Do(f func() executor.StepExecutor) *MockStackLeafCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStackLeafCall) DoAndReturn(f func() executor.StepExecutor) *MockStackLeafCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Root mocks base method.
func (m *MockStack) Root() executor.StepExecutor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Root")
	ret0, _ := ret[0].(executor.StepExecutor)
	return ret0
}

// Root indicates an expected call of Root.
func (mr *MockStackMockRecorder) Root() *MockStackRootCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Root", reflect.TypeOf((*MockStack)(nil).Root))
	return &MockStackRootCall{Call: call}
}

// MockStackRootCall wrap *gomock.Call
type MockStackRootCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStackRootCall) Return(arg0 executor.StepExecutor) *MockStackRootCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStackRootCall) Do(f func() executor.StepExecutor) *MockStackRootCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStackRootCall) DoAndReturn(f func() executor.StepExecutor) *MockStackRootCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stack mocks base method.
func (m *MockStack) Stack() []executor.StepExecutor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stack")
	ret0, _ := ret[0].([]executor.StepExecutor)
	return ret0
}

// Stack indicates an expected call of Stack.
func (mr *MockStackMockRecorder) Stack() *MockStackStackCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stack", reflect.TypeOf((*MockStack)(nil).Stack))
	return &MockStackStackCall{Call: call}
}

// MockStackStackCall wrap *gomock.Call
type MockStackStackCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStackStackCall) Return(arg0 []executor.StepExecutor) *MockStackStackCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStackStackCall) Do(f func() []executor.StepExecutor) *MockStackStackCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStackStackCall) DoAndReturn(f func() []executor.StepExecutor) *MockStackStackCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
