// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/step_executor.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/step_executor.go -destination=executor/step_executor.go -typed
//

// Package mock_executor is a generated GoMock package.
package mock_executor

import (
	context "context"
	io "io"
	reflect "reflect"

	executor "drassi.run/core/pkg/executor"
	expression "drassi.run/core/pkg/expression"
	records "drassi.run/core/pkg/model/records"
	sandboxer "drassi.run/core/pkg/sandboxer"
	stream "drassi.run/core/pkg/stream"
	gomock "go.uber.org/mock/gomock"
)

// MockStepContext is a mock of StepContext interface.
type MockStepContext struct {
	ctrl     *gomock.Controller
	recorder *MockStepContextMockRecorder
	isgomock struct{}
}

// MockStepContextMockRecorder is the mock recorder for MockStepContext.
type MockStepContextMockRecorder struct {
	mock *MockStepContext
}

// NewMockStepContext creates a new mock instance.
func NewMockStepContext(ctrl *gomock.Controller) *MockStepContext {
	mock := &MockStepContext{ctrl: ctrl}
	mock.recorder = &MockStepContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStepContext) EXPECT() *MockStepContextMockRecorder {
	return m.recorder
}

// ExprEnv mocks base method.
func (m *MockStepContext) ExprEnv() expression.Env {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExprEnv")
	ret0, _ := ret[0].(expression.Env)
	return ret0
}

// ExprEnv indicates an expected call of ExprEnv.
func (mr *MockStepContextMockRecorder) ExprEnv() *MockStepContextExprEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExprEnv", reflect.TypeOf((*MockStepContext)(nil).ExprEnv))
	return &MockStepContextExprEnvCall{Call: call}
}

// MockStepContextExprEnvCall wrap *gomock.Call
type MockStepContextExprEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepContextExprEnvCall) Return(arg0 expression.Env) *MockStepContextExprEnvCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepContextExprEnvCall) Do(f func() expression.Env) *MockStepContextExprEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepContextExprEnvCall) DoAndReturn(f func() expression.Env) *MockStepContextExprEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Sandbox mocks base method.
func (m *MockStepContext) Sandbox() sandboxer.Sandbox {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sandbox")
	ret0, _ := ret[0].(sandboxer.Sandbox)
	return ret0
}

// Sandbox indicates an expected call of Sandbox.
func (mr *MockStepContextMockRecorder) Sandbox() *MockStepContextSandboxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sandbox", reflect.TypeOf((*MockStepContext)(nil).Sandbox))
	return &MockStepContextSandboxCall{Call: call}
}

// MockStepContextSandboxCall wrap *gomock.Call
type MockStepContextSandboxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepContextSandboxCall) Return(arg0 sandboxer.Sandbox) *MockStepContextSandboxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepContextSandboxCall) Do(f func() sandboxer.Sandbox) *MockStepContextSandboxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepContextSandboxCall) DoAndReturn(f func() sandboxer.Sandbox) *MockStepContextSandboxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Streams mocks base method.
func (m *MockStepContext) Streams(ctx context.Context) stream.Streams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Streams", ctx)
	ret0, _ := ret[0].(stream.Streams)
	return ret0
}

// Streams indicates an expected call of Streams.
func (mr *MockStepContextMockRecorder) Streams(ctx any) *MockStepContextStreamsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Streams", reflect.TypeOf((*MockStepContext)(nil).Streams), ctx)
	return &MockStepContextStreamsCall{Call: call}
}

// MockStepContextStreamsCall wrap *gomock.Call
type MockStepContextStreamsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepContextStreamsCall) Return(arg0 stream.Streams) *MockStepContextStreamsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepContextStreamsCall) Do(f func(context.Context) stream.Streams) *MockStepContextStreamsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepContextStreamsCall) DoAndReturn(f func(context.Context) stream.Streams) *MockStepContextStreamsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockStepExecutor is a mock of StepExecutor interface.
type MockStepExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockStepExecutorMockRecorder
	isgomock struct{}
}

// MockStepExecutorMockRecorder is the mock recorder for MockStepExecutor.
type MockStepExecutorMockRecorder struct {
	mock *MockStepExecutor
}

// NewMockStepExecutor creates a new mock instance.
func NewMockStepExecutor(ctrl *gomock.Controller) *MockStepExecutor {
	mock := &MockStepExecutor{ctrl: ctrl}
	mock.recorder = &MockStepExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStepExecutor) EXPECT() *MockStepExecutorMockRecorder {
	return m.recorder
}

// ActionExecutor mocks base method.
func (m *MockStepExecutor) ActionExecutor() executor.ActionExecutor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActionExecutor")
	ret0, _ := ret[0].(executor.ActionExecutor)
	return ret0
}

// ActionExecutor indicates an expected call of ActionExecutor.
func (mr *MockStepExecutorMockRecorder) ActionExecutor() *MockStepExecutorActionExecutorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActionExecutor", reflect.TypeOf((*MockStepExecutor)(nil).ActionExecutor))
	return &MockStepExecutorActionExecutorCall{Call: call}
}

// MockStepExecutorActionExecutorCall wrap *gomock.Call
type MockStepExecutorActionExecutorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorActionExecutorCall) Return(arg0 executor.ActionExecutor) *MockStepExecutorActionExecutorCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorActionExecutorCall) Do(f func() executor.ActionExecutor) *MockStepExecutorActionExecutorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorActionExecutorCall) DoAndReturn(f func() executor.ActionExecutor) *MockStepExecutorActionExecutorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ComposeEnv mocks base method.
func (m *MockStepExecutor) ComposeEnv(systemEnv bool) map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComposeEnv", systemEnv)
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// ComposeEnv indicates an expected call of ComposeEnv.
func (mr *MockStepExecutorMockRecorder) ComposeEnv(systemEnv any) *MockStepExecutorComposeEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComposeEnv", reflect.TypeOf((*MockStepExecutor)(nil).ComposeEnv), systemEnv)
	return &MockStepExecutorComposeEnvCall{Call: call}
}

// MockStepExecutorComposeEnvCall wrap *gomock.Call
type MockStepExecutorComposeEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorComposeEnvCall) Return(arg0 map[string]string) *MockStepExecutorComposeEnvCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorComposeEnvCall) Do(f func(bool) map[string]string) *MockStepExecutorComposeEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorComposeEnvCall) DoAndReturn(f func(bool) map[string]string) *MockStepExecutorComposeEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateStepSummary mocks base method.
func (m *MockStepExecutor) CreateStepSummary(r io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStepSummary", r)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStepSummary indicates an expected call of CreateStepSummary.
func (mr *MockStepExecutorMockRecorder) CreateStepSummary(r any) *MockStepExecutorCreateStepSummaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStepSummary", reflect.TypeOf((*MockStepExecutor)(nil).CreateStepSummary), r)
	return &MockStepExecutorCreateStepSummaryCall{Call: call}
}

// MockStepExecutorCreateStepSummaryCall wrap *gomock.Call
type MockStepExecutorCreateStepSummaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorCreateStepSummaryCall) Return(arg0 error) *MockStepExecutorCreateStepSummaryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorCreateStepSummaryCall) Do(f func(io.Reader) error) *MockStepExecutorCreateStepSummaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorCreateStepSummaryCall) DoAndReturn(f func(io.Reader) error) *MockStepExecutorCreateStepSummaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateTask mocks base method.
func (m *MockStepExecutor) CreateTask(stage executor.Stage) *executor.StepTask {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", stage)
	ret0, _ := ret[0].(*executor.StepTask)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockStepExecutorMockRecorder) CreateTask(stage any) *MockStepExecutorCreateTaskCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockStepExecutor)(nil).CreateTask), stage)
	return &MockStepExecutorCreateTaskCall{Call: call}
}

// MockStepExecutorCreateTaskCall wrap *gomock.Call
type MockStepExecutorCreateTaskCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorCreateTaskCall) Return(arg0 *executor.StepTask) *MockStepExecutorCreateTaskCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorCreateTaskCall) Do(f func(executor.Stage) *executor.StepTask) *MockStepExecutorCreateTaskCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorCreateTaskCall) DoAndReturn(f func(executor.Stage) *executor.StepTask) *MockStepExecutorCreateTaskCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExprEnv mocks base method.
func (m *MockStepExecutor) ExprEnv() expression.Env {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExprEnv")
	ret0, _ := ret[0].(expression.Env)
	return ret0
}

// ExprEnv indicates an expected call of ExprEnv.
func (mr *MockStepExecutorMockRecorder) ExprEnv() *MockStepExecutorExprEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExprEnv", reflect.TypeOf((*MockStepExecutor)(nil).ExprEnv))
	return &MockStepExecutorExprEnvCall{Call: call}
}

// MockStepExecutorExprEnvCall wrap *gomock.Call
type MockStepExecutorExprEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorExprEnvCall) Return(arg0 expression.Env) *MockStepExecutorExprEnvCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorExprEnvCall) Do(f func() expression.Env) *MockStepExecutorExprEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorExprEnvCall) DoAndReturn(f func() expression.Env) *MockStepExecutorExprEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// JobExecutor mocks base method.
func (m *MockStepExecutor) JobExecutor() executor.JobExecutor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobExecutor")
	ret0, _ := ret[0].(executor.JobExecutor)
	return ret0
}

// JobExecutor indicates an expected call of JobExecutor.
func (mr *MockStepExecutorMockRecorder) JobExecutor() *MockStepExecutorJobExecutorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobExecutor", reflect.TypeOf((*MockStepExecutor)(nil).JobExecutor))
	return &MockStepExecutorJobExecutorCall{Call: call}
}

// MockStepExecutorJobExecutorCall wrap *gomock.Call
type MockStepExecutorJobExecutorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorJobExecutorCall) Return(arg0 executor.JobExecutor) *MockStepExecutorJobExecutorCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorJobExecutorCall) Do(f func() executor.JobExecutor) *MockStepExecutorJobExecutorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorJobExecutorCall) DoAndReturn(f func() executor.JobExecutor) *MockStepExecutorJobExecutorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Parent mocks base method.
func (m *MockStepExecutor) Parent() executor.StepExecutor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parent")
	ret0, _ := ret[0].(executor.StepExecutor)
	return ret0
}

// Parent indicates an expected call of Parent.
func (mr *MockStepExecutorMockRecorder) Parent() *MockStepExecutorParentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parent", reflect.TypeOf((*MockStepExecutor)(nil).Parent))
	return &MockStepExecutorParentCall{Call: call}
}

// MockStepExecutorParentCall wrap *gomock.Call
type MockStepExecutorParentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorParentCall) Return(arg0 executor.StepExecutor) *MockStepExecutorParentCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorParentCall) Do(f func() executor.StepExecutor) *MockStepExecutorParentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorParentCall) DoAndReturn(f func() executor.StepExecutor) *MockStepExecutorParentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Sandbox mocks base method.
func (m *MockStepExecutor) Sandbox() sandboxer.Sandbox {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sandbox")
	ret0, _ := ret[0].(sandboxer.Sandbox)
	return ret0
}

// Sandbox indicates an expected call of Sandbox.
func (mr *MockStepExecutorMockRecorder) Sandbox() *MockStepExecutorSandboxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sandbox", reflect.TypeOf((*MockStepExecutor)(nil).Sandbox))
	return &MockStepExecutorSandboxCall{Call: call}
}

// MockStepExecutorSandboxCall wrap *gomock.Call
type MockStepExecutorSandboxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorSandboxCall) Return(arg0 sandboxer.Sandbox) *MockStepExecutorSandboxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorSandboxCall) Do(f func() sandboxer.Sandbox) *MockStepExecutorSandboxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorSandboxCall) DoAndReturn(f func() sandboxer.Sandbox) *MockStepExecutorSandboxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveState mocks base method.
func (m *MockStepExecutor) SaveState(state map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveState", state)
}

// SaveState indicates an expected call of SaveState.
func (mr *MockStepExecutorMockRecorder) SaveState(state any) *MockStepExecutorSaveStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveState", reflect.TypeOf((*MockStepExecutor)(nil).SaveState), state)
	return &MockStepExecutorSaveStateCall{Call: call}
}

// MockStepExecutorSaveStateCall wrap *gomock.Call
type MockStepExecutorSaveStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorSaveStateCall) Return() *MockStepExecutorSaveStateCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorSaveStateCall) Do(f func(map[string]string)) *MockStepExecutorSaveStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorSaveStateCall) DoAndReturn(f func(map[string]string)) *MockStepExecutorSaveStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetEnv mocks base method.
func (m *MockStepExecutor) SetEnv(env map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEnv", env)
}

// SetEnv indicates an expected call of SetEnv.
func (mr *MockStepExecutorMockRecorder) SetEnv(env any) *MockStepExecutorSetEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnv", reflect.TypeOf((*MockStepExecutor)(nil).SetEnv), env)
	return &MockStepExecutorSetEnvCall{Call: call}
}

// MockStepExecutorSetEnvCall wrap *gomock.Call
type MockStepExecutorSetEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorSetEnvCall) Return() *MockStepExecutorSetEnvCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorSetEnvCall) Do(f func(map[string]string)) *MockStepExecutorSetEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorSetEnvCall) DoAndReturn(f func(map[string]string)) *MockStepExecutorSetEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetOutput mocks base method.
func (m *MockStepExecutor) SetOutput(output map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOutput", output)
}

// SetOutput indicates an expected call of SetOutput.
func (mr *MockStepExecutorMockRecorder) SetOutput(output any) *MockStepExecutorSetOutputCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOutput", reflect.TypeOf((*MockStepExecutor)(nil).SetOutput), output)
	return &MockStepExecutorSetOutputCall{Call: call}
}

// MockStepExecutorSetOutputCall wrap *gomock.Call
type MockStepExecutorSetOutputCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorSetOutputCall) Return() *MockStepExecutorSetOutputCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorSetOutputCall) Do(f func(map[string]string)) *MockStepExecutorSetOutputCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorSetOutputCall) DoAndReturn(f func(map[string]string)) *MockStepExecutorSetOutputCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetStatus mocks base method.
func (m *MockStepExecutor) SetStatus(status records.Result) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStatus", status)
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockStepExecutorMockRecorder) SetStatus(status any) *MockStepExecutorSetStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockStepExecutor)(nil).SetStatus), status)
	return &MockStepExecutorSetStatusCall{Call: call}
}

// MockStepExecutorSetStatusCall wrap *gomock.Call
type MockStepExecutorSetStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorSetStatusCall) Return() *MockStepExecutorSetStatusCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorSetStatusCall) Do(f func(records.Result)) *MockStepExecutorSetStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorSetStatusCall) DoAndReturn(f func(records.Result)) *MockStepExecutorSetStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Status mocks base method.
func (m *MockStepExecutor) Status() records.Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(records.Result)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockStepExecutorMockRecorder) Status() *MockStepExecutorStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockStepExecutor)(nil).Status))
	return &MockStepExecutorStatusCall{Call: call}
}

// MockStepExecutorStatusCall wrap *gomock.Call
type MockStepExecutorStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorStatusCall) Return(arg0 records.Result) *MockStepExecutorStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorStatusCall) Do(f func() records.Result) *MockStepExecutorStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorStatusCall) DoAndReturn(f func() records.Result) *MockStepExecutorStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StepSpec mocks base method.
func (m *MockStepExecutor) StepSpec() *executor.StepSpec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StepSpec")
	ret0, _ := ret[0].(*executor.StepSpec)
	return ret0
}

// StepSpec indicates an expected call of StepSpec.
func (mr *MockStepExecutorMockRecorder) StepSpec() *MockStepExecutorStepSpecCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StepSpec", reflect.TypeOf((*MockStepExecutor)(nil).StepSpec))
	return &MockStepExecutorStepSpecCall{Call: call}
}

// MockStepExecutorStepSpecCall wrap *gomock.Call
type MockStepExecutorStepSpecCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorStepSpecCall) Return(arg0 *executor.StepSpec) *MockStepExecutorStepSpecCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorStepSpecCall) Do(f func() *executor.StepSpec) *MockStepExecutorStepSpecCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorStepSpecCall) DoAndReturn(f func() *executor.StepSpec) *MockStepExecutorStepSpecCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Streams mocks base method.
func (m *MockStepExecutor) Streams(ctx context.Context) stream.Streams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Streams", ctx)
	ret0, _ := ret[0].(stream.Streams)
	return ret0
}

// Streams indicates an expected call of Streams.
func (mr *MockStepExecutorMockRecorder) Streams(ctx any) *MockStepExecutorStreamsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Streams", reflect.TypeOf((*MockStepExecutor)(nil).Streams), ctx)
	return &MockStepExecutorStreamsCall{Call: call}
}

// MockStepExecutorStreamsCall wrap *gomock.Call
type MockStepExecutorStreamsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepExecutorStreamsCall) Return(arg0 stream.Streams) *MockStepExecutorStreamsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepExecutorStreamsCall) Do(f func(context.Context) stream.Streams) *MockStepExecutorStreamsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepExecutorStreamsCall) DoAndReturn(f func(context.Context) stream.Streams) *MockStepExecutorStreamsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockStepRunDecorator is a mock of StepRunDecorator interface.
type MockStepRunDecorator struct {
	ctrl     *gomock.Controller
	recorder *MockStepRunDecoratorMockRecorder
	isgomock struct{}
}

// MockStepRunDecoratorMockRecorder is the mock recorder for MockStepRunDecorator.
type MockStepRunDecoratorMockRecorder struct {
	mock *MockStepRunDecorator
}

// NewMockStepRunDecorator creates a new mock instance.
func NewMockStepRunDecorator(ctrl *gomock.Controller) *MockStepRunDecorator {
	mock := &MockStepRunDecorator{ctrl: ctrl}
	mock.recorder = &MockStepRunDecoratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStepRunDecorator) EXPECT() *MockStepRunDecoratorMockRecorder {
	return m.recorder
}

// DecorateStepRun mocks base method.
func (m *MockStepRunDecorator) DecorateStepRun(arg0 *executor.StepTask) executor.StepRun {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecorateStepRun", arg0)
	ret0, _ := ret[0].(executor.StepRun)
	return ret0
}

// DecorateStepRun indicates an expected call of DecorateStepRun.
func (mr *MockStepRunDecoratorMockRecorder) DecorateStepRun(arg0 any) *MockStepRunDecoratorDecorateStepRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecorateStepRun", reflect.TypeOf((*MockStepRunDecorator)(nil).DecorateStepRun), arg0)
	return &MockStepRunDecoratorDecorateStepRunCall{Call: call}
}

// MockStepRunDecoratorDecorateStepRunCall wrap *gomock.Call
type MockStepRunDecoratorDecorateStepRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStepRunDecoratorDecorateStepRunCall) Return(arg0 executor.StepRun) *MockStepRunDecoratorDecorateStepRunCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStepRunDecoratorDecorateStepRunCall) Do(f func(*executor.StepTask) executor.StepRun) *MockStepRunDecoratorDecorateStepRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStepRunDecoratorDecorateStepRunCall) DoAndReturn(f func(*executor.StepTask) executor.StepRun) *MockStepRunDecoratorDecorateStepRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
