// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/runtime/provider.go
//
// Generated by this command:
//
//	mockgen -typed -destination=runtime/provider.go -source=../pkg/runtime/provider.go
//

// Package mock_runtime is a generated GoMock package.
package mock_runtime

import (
	reflect "reflect"

	runtime "drassi.run/core/pkg/runtime"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockProvider) Get(nameOrAlias string) (runtime.Runtime, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", nameOrAlias)
	ret0, _ := ret[0].(runtime.Runtime)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProviderMockRecorder) Get(nameOrAlias any) *MockProviderGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProvider)(nil).Get), nameOrAlias)
	return &MockProviderGetCall{Call: call}
}

// MockProviderGetCall wrap *gomock.Call
type MockProviderGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderGetCall) Return(arg0 runtime.Runtime, arg1 error) *MockProviderGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderGetCall) Do(f func(string) (runtime.Runtime, error)) *MockProviderGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderGetCall) DoAndReturn(f func(string) (runtime.Runtime, error)) *MockProviderGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
