// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/runtime/runtime.go
//
// Generated by this command:
//
//	mockgen -typed -destination=runtime/runtime.go -source=../pkg/runtime/runtime.go
//

// Package mock_runtime is a generated GoMock package.
package mock_runtime

import (
	context "context"
	reflect "reflect"

	stream "drassi.run/core/pkg/stream"
	gomock "go.uber.org/mock/gomock"
)

// MockRuntime is a mock of Runtime interface.
type MockRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeMockRecorder
	isgomock struct{}
}

// MockRuntimeMockRecorder is the mock recorder for MockRuntime.
type MockRuntimeMockRecorder struct {
	mock *MockRuntime
}

// NewMockRuntime creates a new mock instance.
func NewMockRuntime(ctrl *gomock.Controller) *MockRuntime {
	mock := &MockRuntime{ctrl: ctrl}
	mock.recorder = &MockRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime) EXPECT() *MockRuntimeMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockRuntime) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockRuntimeMockRecorder) Name() *MockRuntimeNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockRuntime)(nil).Name))
	return &MockRuntimeNameCall{Call: call}
}

// MockRuntimeNameCall wrap *gomock.Call
type MockRuntimeNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRuntimeNameCall) Return(arg0 string) *MockRuntimeNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRuntimeNameCall) Do(f func() string) *MockRuntimeNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRuntimeNameCall) DoAndReturn(f func() string) *MockRuntimeNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Run mocks base method.
func (m *MockRuntime) Run(ctx context.Context, scriptPath string, paths []string, env map[string]string, workdir string, streams *stream.Streams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, scriptPath, paths, env, workdir, streams)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockRuntimeMockRecorder) Run(ctx, scriptPath, paths, env, workdir, streams any) *MockRuntimeRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRuntime)(nil).Run), ctx, scriptPath, paths, env, workdir, streams)
	return &MockRuntimeRunCall{Call: call}
}

// MockRuntimeRunCall wrap *gomock.Call
type MockRuntimeRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRuntimeRunCall) Return(arg0 error) *MockRuntimeRunCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRuntimeRunCall) Do(f func(context.Context, string, []string, map[string]string, string, *stream.Streams) error) *MockRuntimeRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRuntimeRunCall) DoAndReturn(f func(context.Context, string, []string, map[string]string, string, *stream.Streams) error) *MockRuntimeRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
