// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	runner "expression_parser/runner"

	mock "github.com/stretchr/testify/mock"
)

// IExecutionContext is an autogenerated mock type for the IExecutionContext type
type IExecutionContext struct {
	mock.Mock
}

// GetGitHubContext provides a mock function with given fields: name
func (_m *IExecutionContext) GetGitHubContext(name string) string {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetGitHubContext")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsEmbedded provides a mock function with given fields:
func (_m *IExecutionContext) IsEmbedded() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEmbedded")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// JobContext provides a mock function with given fields:
func (_m *IExecutionContext) JobContext() *runner.JobContext {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for JobContext")
	}

	var r0 *runner.JobContext
	if rf, ok := ret.Get(0).(func() *runner.JobContext); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*runner.JobContext)
		}
	}

	return r0
}

// NameOf provides a mock function with given fields:
func (_m *IExecutionContext) NameOf() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NameOf")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Stage provides a mock function with given fields:
func (_m *IExecutionContext) Stage() runner.ActionRunStage {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stage")
	}

	var r0 runner.ActionRunStage
	if rf, ok := ret.Get(0).(func() runner.ActionRunStage); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(runner.ActionRunStage)
	}

	return r0
}

// NewIExecutionContext creates a new instance of IExecutionContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIExecutionContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *IExecutionContext {
	mock := &IExecutionContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
