# SPDX-FileCopyrightText: (c) 2024 The Drassi Authors
#
# SPDX-License-Identifier: Apache-2.0

FROM cgr.dev/chainguard/static
COPY gitea-runner /usr/bin/gitea-runner
ENTRYPOINT ["/usr/bin/gitea-runner"]
