// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/store/oci/manager.go
//
// Generated by this command:
//
//	mockgen -typed -destination=store/oci/manager.go -source=../pkg/store/oci/manager.go
//

// Package mock_ocistore is a generated GoMock package.
package mock_ocistore

import (
	context "context"
	io "io"
	reflect "reflect"

	ocistore "drassi.run/core/pkg/store/oci"
	digest "github.com/opencontainers/go-digest"
	v1 "github.com/opencontainers/image-spec/specs-go/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockManager) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockManagerMockRecorder) Close() *MockManagerCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockManager)(nil).Close))
	return &MockManagerCloseCall{Call: call}
}

// MockManagerCloseCall wrap *gomock.Call
type MockManagerCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerCloseCall) Return(arg0 error) *MockManagerCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerCloseCall) Do(f func() error) *MockManagerCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerCloseCall) DoAndReturn(f func() error) *MockManagerCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Mount mocks base method.
func (m *MockManager) Mount(ctx context.Context, image ocistore.Image, opts ...ocistore.MountOption) (*ocistore.Mount, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, image}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Mount", varargs...)
	ret0, _ := ret[0].(*ocistore.Mount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Mount indicates an expected call of Mount.
func (mr *MockManagerMockRecorder) Mount(ctx, image any, opts ...any) *MockManagerMountCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, image}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mount", reflect.TypeOf((*MockManager)(nil).Mount), varargs...)
	return &MockManagerMountCall{Call: call}
}

// MockManagerMountCall wrap *gomock.Call
type MockManagerMountCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerMountCall) Return(arg0 *ocistore.Mount, arg1 error) *MockManagerMountCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerMountCall) Do(f func(context.Context, ocistore.Image, ...ocistore.MountOption) (*ocistore.Mount, error)) *MockManagerMountCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerMountCall) DoAndReturn(f func(context.Context, ocistore.Image, ...ocistore.MountOption) (*ocistore.Mount, error)) *MockManagerMountCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Pull mocks base method.
func (m *MockManager) Pull(ctx context.Context, imageRef string, opts ...ocistore.PullOption) (ocistore.Image, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, imageRef}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Pull", varargs...)
	ret0, _ := ret[0].(ocistore.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pull indicates an expected call of Pull.
func (mr *MockManagerMockRecorder) Pull(ctx, imageRef any, opts ...any) *MockManagerPullCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, imageRef}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockManager)(nil).Pull), varargs...)
	return &MockManagerPullCall{Call: call}
}

// MockManagerPullCall wrap *gomock.Call
type MockManagerPullCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerPullCall) Return(arg0 ocistore.Image, arg1 error) *MockManagerPullCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerPullCall) Do(f func(context.Context, string, ...ocistore.PullOption) (ocistore.Image, error)) *MockManagerPullCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerPullCall) DoAndReturn(f func(context.Context, string, ...ocistore.PullOption) (ocistore.Image, error)) *MockManagerPullCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Read mocks base method.
func (m *MockManager) Read(ctx context.Context, image ocistore.Image, opts ...ocistore.ReadOption) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, image}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Read", varargs...)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockManagerMockRecorder) Read(ctx, image any, opts ...any) *MockManagerReadCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, image}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockManager)(nil).Read), varargs...)
	return &MockManagerReadCall{Call: call}
}

// MockManagerReadCall wrap *gomock.Call
type MockManagerReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerReadCall) Return(arg0 io.ReadCloser, arg1 error) *MockManagerReadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerReadCall) Do(f func(context.Context, ocistore.Image, ...ocistore.ReadOption) (io.ReadCloser, error)) *MockManagerReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerReadCall) DoAndReturn(f func(context.Context, ocistore.Image, ...ocistore.ReadOption) (io.ReadCloser, error)) *MockManagerReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockImage is a mock of Image interface.
type MockImage struct {
	ctrl     *gomock.Controller
	recorder *MockImageMockRecorder
	isgomock struct{}
}

// MockImageMockRecorder is the mock recorder for MockImage.
type MockImageMockRecorder struct {
	mock *MockImage
}

// NewMockImage creates a new mock instance.
func NewMockImage(ctrl *gomock.Controller) *MockImage {
	mock := &MockImage{ctrl: ctrl}
	mock.recorder = &MockImageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImage) EXPECT() *MockImageMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockImage) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockImageMockRecorder) Name() *MockImageNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockImage)(nil).Name))
	return &MockImageNameCall{Call: call}
}

// MockImageNameCall wrap *gomock.Call
type MockImageNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImageNameCall) Return(arg0 string) *MockImageNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImageNameCall) Do(f func() string) *MockImageNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImageNameCall) DoAndReturn(f func() string) *MockImageNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RootFS mocks base method.
func (m *MockImage) RootFS(ctx context.Context) ([]digest.Digest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RootFS", ctx)
	ret0, _ := ret[0].([]digest.Digest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RootFS indicates an expected call of RootFS.
func (mr *MockImageMockRecorder) RootFS(ctx any) *MockImageRootFSCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RootFS", reflect.TypeOf((*MockImage)(nil).RootFS), ctx)
	return &MockImageRootFSCall{Call: call}
}

// MockImageRootFSCall wrap *gomock.Call
type MockImageRootFSCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImageRootFSCall) Return(arg0 []digest.Digest, arg1 error) *MockImageRootFSCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImageRootFSCall) Do(f func(context.Context) ([]digest.Digest, error)) *MockImageRootFSCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImageRootFSCall) DoAndReturn(f func(context.Context) ([]digest.Digest, error)) *MockImageRootFSCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Spec mocks base method.
func (m *MockImage) Spec(ctx context.Context) (v1.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Spec", ctx)
	ret0, _ := ret[0].(v1.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Spec indicates an expected call of Spec.
func (mr *MockImageMockRecorder) Spec(ctx any) *MockImageSpecCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Spec", reflect.TypeOf((*MockImage)(nil).Spec), ctx)
	return &MockImageSpecCall{Call: call}
}

// MockImageSpecCall wrap *gomock.Call
type MockImageSpecCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImageSpecCall) Return(arg0 v1.Image, arg1 error) *MockImageSpecCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImageSpecCall) Do(f func(context.Context) (v1.Image, error)) *MockImageSpecCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImageSpecCall) DoAndReturn(f func(context.Context) (v1.Image, error)) *MockImageSpecCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Target mocks base method.
func (m *MockImage) Target() v1.Descriptor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Target")
	ret0, _ := ret[0].(v1.Descriptor)
	return ret0
}

// Target indicates an expected call of Target.
func (mr *MockImageMockRecorder) Target() *MockImageTargetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Target", reflect.TypeOf((*MockImage)(nil).Target))
	return &MockImageTargetCall{Call: call}
}

// MockImageTargetCall wrap *gomock.Call
type MockImageTargetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockImageTargetCall) Return(arg0 v1.Descriptor) *MockImageTargetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockImageTargetCall) Do(f func() v1.Descriptor) *MockImageTargetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockImageTargetCall) DoAndReturn(f func() v1.Descriptor) *MockImageTargetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
