// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/store/oci/manager.go
//
// Generated by this command:
//
//	mockgen -typed -destination=store/oci/manager.go -source=../pkg/store/oci/manager.go
//

// Package mock_ocistore is a generated GoMock package.
package mock_ocistore

import (
	context "context"
	io "io"
	reflect "reflect"

	ocistore "drassi.run/core/pkg/store/oci"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockManager) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockManagerMockRecorder) Close() *MockManagerCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockManager)(nil).Close))
	return &MockManagerCloseCall{Call: call}
}

// MockManagerCloseCall wrap *gomock.Call
type MockManagerCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerCloseCall) Return(arg0 error) *MockManagerCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerCloseCall) Do(f func() error) *MockManagerCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerCloseCall) DoAndReturn(f func() error) *MockManagerCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Image mocks base method.
func (m *MockManager) Image(ctx context.Context, imageRef string) (*ocistore.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Image", ctx, imageRef)
	ret0, _ := ret[0].(*ocistore.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Image indicates an expected call of Image.
func (mr *MockManagerMockRecorder) Image(ctx, imageRef any) *MockManagerImageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Image", reflect.TypeOf((*MockManager)(nil).Image), ctx, imageRef)
	return &MockManagerImageCall{Call: call}
}

// MockManagerImageCall wrap *gomock.Call
type MockManagerImageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerImageCall) Return(arg0 *ocistore.Image, arg1 error) *MockManagerImageCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerImageCall) Do(f func(context.Context, string) (*ocistore.Image, error)) *MockManagerImageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerImageCall) DoAndReturn(f func(context.Context, string) (*ocistore.Image, error)) *MockManagerImageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Mount mocks base method.
func (m *MockManager) Mount(ctx context.Context, image *ocistore.Image, opts ...ocistore.MountOption) (string, string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, image}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Mount", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Mount indicates an expected call of Mount.
func (mr *MockManagerMockRecorder) Mount(ctx, image any, opts ...any) *MockManagerMountCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, image}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mount", reflect.TypeOf((*MockManager)(nil).Mount), varargs...)
	return &MockManagerMountCall{Call: call}
}

// MockManagerMountCall wrap *gomock.Call
type MockManagerMountCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerMountCall) Return(mountDir, layerId string, err error) *MockManagerMountCall {
	c.Call = c.Call.Return(mountDir, layerId, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerMountCall) Do(f func(context.Context, *ocistore.Image, ...ocistore.MountOption) (string, string, error)) *MockManagerMountCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerMountCall) DoAndReturn(f func(context.Context, *ocistore.Image, ...ocistore.MountOption) (string, string, error)) *MockManagerMountCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Pull mocks base method.
func (m *MockManager) Pull(ctx context.Context, imageRef string, opts ...ocistore.PullOption) (*ocistore.Image, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, imageRef}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Pull", varargs...)
	ret0, _ := ret[0].(*ocistore.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pull indicates an expected call of Pull.
func (mr *MockManagerMockRecorder) Pull(ctx, imageRef any, opts ...any) *MockManagerPullCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, imageRef}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockManager)(nil).Pull), varargs...)
	return &MockManagerPullCall{Call: call}
}

// MockManagerPullCall wrap *gomock.Call
type MockManagerPullCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerPullCall) Return(arg0 *ocistore.Image, arg1 error) *MockManagerPullCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerPullCall) Do(f func(context.Context, string, ...ocistore.PullOption) (*ocistore.Image, error)) *MockManagerPullCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerPullCall) DoAndReturn(f func(context.Context, string, ...ocistore.PullOption) (*ocistore.Image, error)) *MockManagerPullCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Read mocks base method.
func (m *MockManager) Read(ctx context.Context, image *ocistore.Image, opts ...ocistore.ReadOption) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, image}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Read", varargs...)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockManagerMockRecorder) Read(ctx, image any, opts ...any) *MockManagerReadCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, image}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockManager)(nil).Read), varargs...)
	return &MockManagerReadCall{Call: call}
}

// MockManagerReadCall wrap *gomock.Call
type MockManagerReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerReadCall) Return(arg0 io.ReadCloser, arg1 error) *MockManagerReadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerReadCall) Do(f func(context.Context, *ocistore.Image, ...ocistore.ReadOption) (io.ReadCloser, error)) *MockManagerReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerReadCall) DoAndReturn(f func(context.Context, *ocistore.Image, ...ocistore.ReadOption) (io.ReadCloser, error)) *MockManagerReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Unmount mocks base method.
func (m *MockManager) Unmount(ctx context.Context, layerId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmount", ctx, layerId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmount indicates an expected call of Unmount.
func (mr *MockManagerMockRecorder) Unmount(ctx, layerId any) *MockManagerUnmountCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmount", reflect.TypeOf((*MockManager)(nil).Unmount), ctx, layerId)
	return &MockManagerUnmountCall{Call: call}
}

// MockManagerUnmountCall wrap *gomock.Call
type MockManagerUnmountCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerUnmountCall) Return(arg0 error) *MockManagerUnmountCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerUnmountCall) Do(f func(context.Context, string) error) *MockManagerUnmountCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerUnmountCall) DoAndReturn(f func(context.Context, string) error) *MockManagerUnmountCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
