// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/reporter/reporter.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/reporter/reporter.go -destination=executor/reporter/reporter.go -typed
//

// Package mock_reporter is a generated GoMock package.
package mock_reporter

import (
	context "context"
	io "io"
	reflect "reflect"

	executor "drassi.run/core/pkg/executor"
	reporter "drassi.run/core/pkg/executor/reporter"
	records "drassi.run/core/pkg/model/records"
	gomock "go.uber.org/mock/gomock"
)

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
	isgomock struct{}
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// AddIssue mocks base method.
func (m *MockReporter) AddIssue(ctx context.Context, issue *reporter.Issue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIssue", ctx, issue)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIssue indicates an expected call of AddIssue.
func (mr *MockReporterMockRecorder) AddIssue(ctx, issue any) *MockReporterAddIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIssue", reflect.TypeOf((*MockReporter)(nil).AddIssue), ctx, issue)
	return &MockReporterAddIssueCall{Call: call}
}

// MockReporterAddIssueCall wrap *gomock.Call
type MockReporterAddIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterAddIssueCall) Return(arg0 error) *MockReporterAddIssueCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterAddIssueCall) Do(f func(context.Context, *reporter.Issue) error) *MockReporterAddIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterAddIssueCall) DoAndReturn(f func(context.Context, *reporter.Issue) error) *MockReporterAddIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AttachFile mocks base method.
func (m *MockReporter) AttachFile(kind, name string, reader io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachFile", kind, name, reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachFile indicates an expected call of AttachFile.
func (mr *MockReporterMockRecorder) AttachFile(kind, name, reader any) *MockReporterAttachFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachFile", reflect.TypeOf((*MockReporter)(nil).AttachFile), kind, name, reader)
	return &MockReporterAttachFileCall{Call: call}
}

// MockReporterAttachFileCall wrap *gomock.Call
type MockReporterAttachFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterAttachFileCall) Return(arg0 error) *MockReporterAttachFileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterAttachFileCall) Do(f func(string, string, io.Reader) error) *MockReporterAttachFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterAttachFileCall) DoAndReturn(f func(string, string, io.Reader) error) *MockReporterAttachFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Close mocks base method.
func (m *MockReporter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockReporterMockRecorder) Close() *MockReporterCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockReporter)(nil).Close))
	return &MockReporterCloseCall{Call: call}
}

// MockReporterCloseCall wrap *gomock.Call
type MockReporterCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterCloseCall) Return(arg0 error) *MockReporterCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterCloseCall) Do(f func() error) *MockReporterCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterCloseCall) DoAndReturn(f func() error) *MockReporterCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EndJob mocks base method.
func (m *MockReporter) EndJob(ctx context.Context, je executor.JobExecutor, result *records.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndJob", ctx, je, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndJob indicates an expected call of EndJob.
func (mr *MockReporterMockRecorder) EndJob(ctx, je, result any) *MockReporterEndJobCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndJob", reflect.TypeOf((*MockReporter)(nil).EndJob), ctx, je, result)
	return &MockReporterEndJobCall{Call: call}
}

// MockReporterEndJobCall wrap *gomock.Call
type MockReporterEndJobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterEndJobCall) Return(arg0 error) *MockReporterEndJobCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterEndJobCall) Do(f func(context.Context, executor.JobExecutor, *records.Job) error) *MockReporterEndJobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterEndJobCall) DoAndReturn(f func(context.Context, executor.JobExecutor, *records.Job) error) *MockReporterEndJobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EndStep mocks base method.
func (m *MockReporter) EndStep(ctx context.Context, stage executor.Stage, se executor.StepExecutor, result *records.Step) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndStep", ctx, stage, se, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndStep indicates an expected call of EndStep.
func (mr *MockReporterMockRecorder) EndStep(ctx, stage, se, result any) *MockReporterEndStepCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndStep", reflect.TypeOf((*MockReporter)(nil).EndStep), ctx, stage, se, result)
	return &MockReporterEndStepCall{Call: call}
}

// MockReporterEndStepCall wrap *gomock.Call
type MockReporterEndStepCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterEndStepCall) Return(arg0 error) *MockReporterEndStepCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterEndStepCall) Do(f func(context.Context, executor.Stage, executor.StepExecutor, *records.Step) error) *MockReporterEndStepCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterEndStepCall) DoAndReturn(f func(context.Context, executor.Stage, executor.StepExecutor, *records.Step) error) *MockReporterEndStepCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Log mocks base method.
func (m *MockReporter) Log(ctx context.Context, msg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Log indicates an expected call of Log.
func (mr *MockReporterMockRecorder) Log(ctx, msg any) *MockReporterLogCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockReporter)(nil).Log), ctx, msg)
	return &MockReporterLogCall{Call: call}
}

// MockReporterLogCall wrap *gomock.Call
type MockReporterLogCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterLogCall) Return(arg0 error) *MockReporterLogCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterLogCall) Do(f func(context.Context, string) error) *MockReporterLogCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterLogCall) DoAndReturn(f func(context.Context, string) error) *MockReporterLogCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StartJob mocks base method.
func (m *MockReporter) StartJob(ctx context.Context, je executor.JobExecutor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartJob", ctx, je)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartJob indicates an expected call of StartJob.
func (mr *MockReporterMockRecorder) StartJob(ctx, je any) *MockReporterStartJobCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartJob", reflect.TypeOf((*MockReporter)(nil).StartJob), ctx, je)
	return &MockReporterStartJobCall{Call: call}
}

// MockReporterStartJobCall wrap *gomock.Call
type MockReporterStartJobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterStartJobCall) Return(arg0 error) *MockReporterStartJobCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterStartJobCall) Do(f func(context.Context, executor.JobExecutor) error) *MockReporterStartJobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterStartJobCall) DoAndReturn(f func(context.Context, executor.JobExecutor) error) *MockReporterStartJobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StartStep mocks base method.
func (m *MockReporter) StartStep(ctx context.Context, stage executor.Stage, se executor.StepExecutor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartStep", ctx, stage, se)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartStep indicates an expected call of StartStep.
func (mr *MockReporterMockRecorder) StartStep(ctx, stage, se any) *MockReporterStartStepCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartStep", reflect.TypeOf((*MockReporter)(nil).StartStep), ctx, stage, se)
	return &MockReporterStartStepCall{Call: call}
}

// MockReporterStartStepCall wrap *gomock.Call
type MockReporterStartStepCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReporterStartStepCall) Return(arg0 error) *MockReporterStartStepCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReporterStartStepCall) Do(f func(context.Context, executor.Stage, executor.StepExecutor) error) *MockReporterStartStepCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReporterStartStepCall) DoAndReturn(f func(context.Context, executor.Stage, executor.StepExecutor) error) *MockReporterStartStepCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
