// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/store/git/manager.go
//
// Generated by this command:
//
//	mockgen -typed -destination=store/git/manager.go -source=../pkg/store/git/manager.go
//

// Package mock_gitstore is a generated GoMock package.
package mock_gitstore

import (
	context "context"
	io "io"
	reflect "reflect"

	gitstore "drassi.run/core/pkg/store/git"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockManager) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockManagerMockRecorder) Close() *MockManagerCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockManager)(nil).Close))
	return &MockManagerCloseCall{Call: call}
}

// MockManagerCloseCall wrap *gomock.Call
type MockManagerCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerCloseCall) Return(arg0 error) *MockManagerCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerCloseCall) Do(f func() error) *MockManagerCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerCloseCall) DoAndReturn(f func() error) *MockManagerCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Fetch mocks base method.
func (m *MockManager) Fetch(ctx context.Context, repo *gitstore.RepoReference, opts ...gitstore.FetchOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, repo}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Fetch", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockManagerMockRecorder) Fetch(ctx, repo any, opts ...any) *MockManagerFetchCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, repo}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockManager)(nil).Fetch), varargs...)
	return &MockManagerFetchCall{Call: call}
}

// MockManagerFetchCall wrap *gomock.Call
type MockManagerFetchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerFetchCall) Return(rev string, err error) *MockManagerFetchCall {
	c.Call = c.Call.Return(rev, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerFetchCall) Do(f func(context.Context, *gitstore.RepoReference, ...gitstore.FetchOption) (string, error)) *MockManagerFetchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerFetchCall) DoAndReturn(f func(context.Context, *gitstore.RepoReference, ...gitstore.FetchOption) (string, error)) *MockManagerFetchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Read mocks base method.
func (m *MockManager) Read(ctx context.Context, repo *gitstore.RepoReference, rev string, opts ...gitstore.ReadOption) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, repo, rev}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Read", varargs...)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockManagerMockRecorder) Read(ctx, repo, rev any, opts ...any) *MockManagerReadCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, repo, rev}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockManager)(nil).Read), varargs...)
	return &MockManagerReadCall{Call: call}
}

// MockManagerReadCall wrap *gomock.Call
type MockManagerReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManagerReadCall) Return(arg0 io.ReadCloser, arg1 error) *MockManagerReadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManagerReadCall) Do(f func(context.Context, *gitstore.RepoReference, string, ...gitstore.ReadOption) (io.ReadCloser, error)) *MockManagerReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManagerReadCall) DoAndReturn(f func(context.Context, *gitstore.RepoReference, string, ...gitstore.ReadOption) (io.ReadCloser, error)) *MockManagerReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
