//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRunner) DeepCopyInto(out *GitHubRunner) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRunner.
func (in *GitHubRunner) DeepCopy() *GitHubRunner {
	if in == nil {
		return nil
	}
	out := new(GitHubRunner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitHubRunner) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRunnerAuthorization) DeepCopyInto(out *GitHubRunnerAuthorization) {
	*out = *in
	out.SecretRef = in.SecretRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRunnerAuthorization.
func (in *GitHubRunnerAuthorization) DeepCopy() *GitHubRunnerAuthorization {
	if in == nil {
		return nil
	}
	out := new(GitHubRunnerAuthorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRunnerSpec) DeepCopyInto(out *GitHubRunnerSpec) {
	*out = *in
	out.Authorization = in.Authorization
	in.SandboxerRef.DeepCopyInto(&out.SandboxerRef)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRunnerSpec.
func (in *GitHubRunnerSpec) DeepCopy() *GitHubRunnerSpec {
	if in == nil {
		return nil
	}
	out := new(GitHubRunnerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubRunnerStatus) DeepCopyInto(out *GitHubRunnerStatus) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubRunnerStatus.
func (in *GitHubRunnerStatus) DeepCopy() *GitHubRunnerStatus {
	if in == nil {
		return nil
	}
	out := new(GitHubRunnerStatus)
	in.DeepCopyInto(out)
	return out
}
