// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/command/console.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/command/console.go -destination=executor/command/console.go -typed
//

// Package mock_command is a generated GoMock package.
package mock_command

import (
	context "context"
	reflect "reflect"

	command "drassi.run/core/pkg/executor/command"
	gomock "go.uber.org/mock/gomock"
)

// MockConsoleManager is a mock of ConsoleManager interface.
type MockConsoleManager[R any] struct {
	ctrl     *gomock.Controller
	recorder *MockConsoleManagerMockRecorder[R]
	isgomock struct{}
}

// MockConsoleManagerMockRecorder is the mock recorder for MockConsoleManager.
type MockConsoleManagerMockRecorder[R any] struct {
	mock *MockConsoleManager[R]
}

// NewMockConsoleManager creates a new mock instance.
func NewMockConsoleManager[R any](ctrl *gomock.Controller) *MockConsoleManager[R] {
	mock := &MockConsoleManager[R]{ctrl: ctrl}
	mock.recorder = &MockConsoleManagerMockRecorder[R]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsoleManager[R]) EXPECT() *MockConsoleManagerMockRecorder[R] {
	return m.recorder
}

// ParseCommand mocks base method.
func (m *MockConsoleManager[R]) ParseCommand(line string) *command.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseCommand", line)
	ret0, _ := ret[0].(*command.Command)
	return ret0
}

// ParseCommand indicates an expected call of ParseCommand.
func (mr *MockConsoleManagerMockRecorder[R]) ParseCommand(line any) *MockConsoleManagerParseCommandCall[R] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseCommand", reflect.TypeOf((*MockConsoleManager[R])(nil).ParseCommand), line)
	return &MockConsoleManagerParseCommandCall[R]{Call: call}
}

// MockConsoleManagerParseCommandCall wrap *gomock.Call
type MockConsoleManagerParseCommandCall[R any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConsoleManagerParseCommandCall[R]) Return(arg0 *command.Command) *MockConsoleManagerParseCommandCall[R] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConsoleManagerParseCommandCall[R]) Do(f func(string) *command.Command) *MockConsoleManagerParseCommandCall[R] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConsoleManagerParseCommandCall[R]) DoAndReturn(f func(string) *command.Command) *MockConsoleManagerParseCommandCall[R] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Process mocks base method.
func (m *MockConsoleManager[R]) Process(ctx context.Context, res R, line string, cmd *command.Command) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, res, line, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockConsoleManagerMockRecorder[R]) Process(ctx, res, line, cmd any) *MockConsoleManagerProcessCall[R] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockConsoleManager[R])(nil).Process), ctx, res, line, cmd)
	return &MockConsoleManagerProcessCall[R]{Call: call}
}

// MockConsoleManagerProcessCall wrap *gomock.Call
type MockConsoleManagerProcessCall[R any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConsoleManagerProcessCall[R]) Return(arg0 error) *MockConsoleManagerProcessCall[R] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConsoleManagerProcessCall[R]) Do(f func(context.Context, R, string, *command.Command) error) *MockConsoleManagerProcessCall[R] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConsoleManagerProcessCall[R]) DoAndReturn(f func(context.Context, R, string, *command.Command) error) *MockConsoleManagerProcessCall[R] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Register mocks base method.
func (m *MockConsoleManager[R]) Register(handler *command.ConsoleHandler[R]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockConsoleManagerMockRecorder[R]) Register(handler any) *MockConsoleManagerRegisterCall[R] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockConsoleManager[R])(nil).Register), handler)
	return &MockConsoleManagerRegisterCall[R]{Call: call}
}

// MockConsoleManagerRegisterCall wrap *gomock.Call
type MockConsoleManagerRegisterCall[R any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConsoleManagerRegisterCall[R]) Return(arg0 error) *MockConsoleManagerRegisterCall[R] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConsoleManagerRegisterCall[R]) Do(f func(*command.ConsoleHandler[R]) error) *MockConsoleManagerRegisterCall[R] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConsoleManagerRegisterCall[R]) DoAndReturn(f func(*command.ConsoleHandler[R]) error) *MockConsoleManagerRegisterCall[R] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
