// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/executor/command/file.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/executor/command/file.go -destination=executor/command/file.go -typed
//

// Package mock_command is a generated GoMock package.
package mock_command

import (
	context "context"
	reflect "reflect"

	command "drassi.run/core/pkg/executor/command"
	gomock "go.uber.org/mock/gomock"
)

// MockFileManager is a mock of FileManager interface.
type MockFileManager struct {
	ctrl     *gomock.Controller
	recorder *MockFileManagerMockRecorder
	isgomock struct{}
}

// MockFileManagerMockRecorder is the mock recorder for MockFileManager.
type MockFileManagerMockRecorder struct {
	mock *MockFileManager
}

// NewMockFileManager creates a new mock instance.
func NewMockFileManager(ctrl *gomock.Controller) *MockFileManager {
	mock := &MockFileManager{ctrl: ctrl}
	mock.recorder = &MockFileManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileManager) EXPECT() *MockFileManagerMockRecorder {
	return m.recorder
}

// Env mocks base method.
func (m *MockFileManager) Env(suffix string) map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Env", suffix)
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// Env indicates an expected call of Env.
func (mr *MockFileManagerMockRecorder) Env(suffix any) *MockFileManagerEnvCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*MockFileManager)(nil).Env), suffix)
	return &MockFileManagerEnvCall{Call: call}
}

// MockFileManagerEnvCall wrap *gomock.Call
type MockFileManagerEnvCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileManagerEnvCall) Return(arg0 map[string]string) *MockFileManagerEnvCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileManagerEnvCall) Do(f func(string) map[string]string) *MockFileManagerEnvCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileManagerEnvCall) DoAndReturn(f func(string) map[string]string) *MockFileManagerEnvCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Initialize mocks base method.
func (m *MockFileManager) Initialize(ctx context.Context, suffix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", ctx, suffix)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockFileManagerMockRecorder) Initialize(ctx, suffix any) *MockFileManagerInitializeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockFileManager)(nil).Initialize), ctx, suffix)
	return &MockFileManagerInitializeCall{Call: call}
}

// MockFileManagerInitializeCall wrap *gomock.Call
type MockFileManagerInitializeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileManagerInitializeCall) Return(arg0 error) *MockFileManagerInitializeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileManagerInitializeCall) Do(f func(context.Context, string) error) *MockFileManagerInitializeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileManagerInitializeCall) DoAndReturn(f func(context.Context, string) error) *MockFileManagerInitializeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Process mocks base method.
func (m *MockFileManager) Process(ctx context.Context, suffix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, suffix)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockFileManagerMockRecorder) Process(ctx, suffix any) *MockFileManagerProcessCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockFileManager)(nil).Process), ctx, suffix)
	return &MockFileManagerProcessCall{Call: call}
}

// MockFileManagerProcessCall wrap *gomock.Call
type MockFileManagerProcessCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileManagerProcessCall) Return(arg0 error) *MockFileManagerProcessCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileManagerProcessCall) Do(f func(context.Context, string) error) *MockFileManagerProcessCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileManagerProcessCall) DoAndReturn(f func(context.Context, string) error) *MockFileManagerProcessCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Register mocks base method.
func (m *MockFileManager) Register(handler *command.FileHandler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockFileManagerMockRecorder) Register(handler any) *MockFileManagerRegisterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockFileManager)(nil).Register), handler)
	return &MockFileManagerRegisterCall{Call: call}
}

// MockFileManagerRegisterCall wrap *gomock.Call
type MockFileManagerRegisterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileManagerRegisterCall) Return(arg0 error) *MockFileManagerRegisterCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileManagerRegisterCall) Do(f func(*command.FileHandler) error) *MockFileManagerRegisterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileManagerRegisterCall) DoAndReturn(f func(*command.FileHandler) error) *MockFileManagerRegisterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
