# SPDX-FileCopyrightText: (c) 2024 The Drassi Authors
#
# SPDX-License-Identifier: Apache-2.0

name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - ".github/workflows/lint.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.work
          cache: false

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.2

      - name: Run golangci-lint
        # TODO (dungdm93): there are few wanrings left in core
        # golangci-lint run ./core/...
        run: |
            golangci-lint run ./gha-runner
            golangci-lint run ./gitea-runner
