# SPDX-FileCopyrightText: (c) 2024 The Drassi Authors
#
# SPDX-License-Identifier: Apache-2.0

name: Verify

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.26 ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.work.sum

      - name: Test
        run: go list -m | xargs -I {} go test "{}/..."

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check License Header
        uses: ./.github/actions/hawkeye

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Run golangci-lint (core)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          working-directory: ./core
          args: --timeout=10m
