// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/sandboxer/engine.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/sandboxer/engine.go -destination=sandboxer/engine.go -typed
//

// Package mock_sandboxer is a generated GoMock package.
package mock_sandboxer

import (
	context "context"
	reflect "reflect"

	sandboxer "drassi.run/core/pkg/sandboxer"
	gomock "go.uber.org/mock/gomock"
)

// MockEngine is a mock of Engine interface.
type MockEngine struct {
	ctrl     *gomock.Controller
	recorder *MockEngineMockRecorder
}

// MockEngineMockRecorder is the mock recorder for MockEngine.
type MockEngineMockRecorder struct {
	mock *MockEngine
}

// NewMockEngine creates a new mock instance.
func NewMockEngine(ctrl *gomock.Controller) *MockEngine {
	mock := &MockEngine{ctrl: ctrl}
	mock.recorder = &MockEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngine) EXPECT() *MockEngineMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEngine) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEngineMockRecorder) Close() *MockEngineCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEngine)(nil).Close))
	return &MockEngineCloseCall{Call: call}
}

// MockEngineCloseCall wrap *gomock.Call
type MockEngineCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineCloseCall) Return(arg0 error) *MockEngineCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineCloseCall) Do(f func() error) *MockEngineCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineCloseCall) DoAndReturn(f func() error) *MockEngineCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Launch mocks base method.
func (m *MockEngine) Launch(arg0 context.Context, arg1 *sandboxer.LaunchRequest) (*sandboxer.LaunchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Launch", arg0, arg1)
	ret0, _ := ret[0].(*sandboxer.LaunchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Launch indicates an expected call of Launch.
func (mr *MockEngineMockRecorder) Launch(arg0, arg1 any) *MockEngineLaunchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Launch", reflect.TypeOf((*MockEngine)(nil).Launch), arg0, arg1)
	return &MockEngineLaunchCall{Call: call}
}

// MockEngineLaunchCall wrap *gomock.Call
type MockEngineLaunchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEngineLaunchCall) Return(arg0 *sandboxer.LaunchResponse, arg1 error) *MockEngineLaunchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEngineLaunchCall) Do(f func(context.Context, *sandboxer.LaunchRequest) (*sandboxer.LaunchResponse, error)) *MockEngineLaunchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEngineLaunchCall) DoAndReturn(f func(context.Context, *sandboxer.LaunchRequest) (*sandboxer.LaunchResponse, error)) *MockEngineLaunchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
