// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/sandboxer/interface.go
//
// Generated by this command:
//
//	mockgen -source=../pkg/sandboxer/interface.go -destination=sandboxer/interface.go -typed
//

// Package mock_sandboxer is a generated GoMock package.
package mock_sandboxer

import (
	context "context"
	io "io"
	reflect "reflect"

	sandboxer "drassi.run/core/pkg/sandboxer"
	gomock "go.uber.org/mock/gomock"
)

// MockSandbox is a mock of Sandbox interface.
type MockSandbox struct {
	ctrl     *gomock.Controller
	recorder *MockSandboxMockRecorder
}

// MockSandboxMockRecorder is the mock recorder for MockSandbox.
type MockSandboxMockRecorder struct {
	mock *MockSandbox
}

// NewMockSandbox creates a new mock instance.
func NewMockSandbox(ctrl *gomock.Controller) *MockSandbox {
	mock := &MockSandbox{ctrl: ctrl}
	mock.recorder = &MockSandboxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSandbox) EXPECT() *MockSandboxMockRecorder {
	return m.recorder
}

// BuildImage mocks base method.
func (m *MockSandbox) BuildImage(ctx context.Context, image, dockerfile, contextPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildImage", ctx, image, dockerfile, contextPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuildImage indicates an expected call of BuildImage.
func (mr *MockSandboxMockRecorder) BuildImage(ctx, image, dockerfile, contextPath any) *MockSandboxBuildImageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildImage", reflect.TypeOf((*MockSandbox)(nil).BuildImage), ctx, image, dockerfile, contextPath)
	return &MockSandboxBuildImageCall{Call: call}
}

// MockSandboxBuildImageCall wrap *gomock.Call
type MockSandboxBuildImageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxBuildImageCall) Return(arg0 error) *MockSandboxBuildImageCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxBuildImageCall) Do(f func(context.Context, string, string, string) error) *MockSandboxBuildImageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxBuildImageCall) DoAndReturn(f func(context.Context, string, string, string) error) *MockSandboxBuildImageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CopyIn mocks base method.
func (m *MockSandbox) CopyIn(ctx context.Context, reader io.Reader, dst string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyIn", ctx, reader, dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyIn indicates an expected call of CopyIn.
func (mr *MockSandboxMockRecorder) CopyIn(ctx, reader, dst any) *MockSandboxCopyInCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyIn", reflect.TypeOf((*MockSandbox)(nil).CopyIn), ctx, reader, dst)
	return &MockSandboxCopyInCall{Call: call}
}

// MockSandboxCopyInCall wrap *gomock.Call
type MockSandboxCopyInCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxCopyInCall) Return(arg0 error) *MockSandboxCopyInCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxCopyInCall) Do(f func(context.Context, io.Reader, string) error) *MockSandboxCopyInCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxCopyInCall) DoAndReturn(f func(context.Context, io.Reader, string) error) *MockSandboxCopyInCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CopyOut mocks base method.
func (m *MockSandbox) CopyOut(ctx context.Context, src string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyOut", ctx, src)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyOut indicates an expected call of CopyOut.
func (mr *MockSandboxMockRecorder) CopyOut(ctx, src any) *MockSandboxCopyOutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyOut", reflect.TypeOf((*MockSandbox)(nil).CopyOut), ctx, src)
	return &MockSandboxCopyOutCall{Call: call}
}

// MockSandboxCopyOutCall wrap *gomock.Call
type MockSandboxCopyOutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxCopyOutCall) Return(arg0 io.ReadCloser, arg1 error) *MockSandboxCopyOutCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxCopyOutCall) Do(f func(context.Context, string) (io.ReadCloser, error)) *MockSandboxCopyOutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxCopyOutCall) DoAndReturn(f func(context.Context, string) (io.ReadCloser, error)) *MockSandboxCopyOutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Execute mocks base method.
func (m *MockSandbox) Execute(ctx context.Context, cmd []string, env map[string]string, workdir string, streams *sandboxer.Streams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, cmd, env, workdir, streams)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockSandboxMockRecorder) Execute(ctx, cmd, env, workdir, streams any) *MockSandboxExecuteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSandbox)(nil).Execute), ctx, cmd, env, workdir, streams)
	return &MockSandboxExecuteCall{Call: call}
}

// MockSandboxExecuteCall wrap *gomock.Call
type MockSandboxExecuteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxExecuteCall) Return(arg0 error) *MockSandboxExecuteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxExecuteCall) Do(f func(context.Context, []string, map[string]string, string, *sandboxer.Streams) error) *MockSandboxExecuteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxExecuteCall) DoAndReturn(f func(context.Context, []string, map[string]string, string, *sandboxer.Streams) error) *MockSandboxExecuteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetActionsDir mocks base method.
func (m *MockSandbox) GetActionsDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActionsDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetActionsDir indicates an expected call of GetActionsDir.
func (mr *MockSandboxMockRecorder) GetActionsDir() *MockSandboxGetActionsDirCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActionsDir", reflect.TypeOf((*MockSandbox)(nil).GetActionsDir))
	return &MockSandboxGetActionsDirCall{Call: call}
}

// MockSandboxGetActionsDirCall wrap *gomock.Call
type MockSandboxGetActionsDirCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxGetActionsDirCall) Return(arg0 string) *MockSandboxGetActionsDirCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxGetActionsDirCall) Do(f func() string) *MockSandboxGetActionsDirCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxGetActionsDirCall) DoAndReturn(f func() string) *MockSandboxGetActionsDirCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetTempDir mocks base method.
func (m *MockSandbox) GetTempDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTempDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTempDir indicates an expected call of GetTempDir.
func (mr *MockSandboxMockRecorder) GetTempDir() *MockSandboxGetTempDirCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTempDir", reflect.TypeOf((*MockSandbox)(nil).GetTempDir))
	return &MockSandboxGetTempDirCall{Call: call}
}

// MockSandboxGetTempDirCall wrap *gomock.Call
type MockSandboxGetTempDirCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxGetTempDirCall) Return(arg0 string) *MockSandboxGetTempDirCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxGetTempDirCall) Do(f func() string) *MockSandboxGetTempDirCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxGetTempDirCall) DoAndReturn(f func() string) *MockSandboxGetTempDirCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetToolsDir mocks base method.
func (m *MockSandbox) GetToolsDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToolsDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetToolsDir indicates an expected call of GetToolsDir.
func (mr *MockSandboxMockRecorder) GetToolsDir() *MockSandboxGetToolsDirCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToolsDir", reflect.TypeOf((*MockSandbox)(nil).GetToolsDir))
	return &MockSandboxGetToolsDirCall{Call: call}
}

// MockSandboxGetToolsDirCall wrap *gomock.Call
type MockSandboxGetToolsDirCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxGetToolsDirCall) Return(arg0 string) *MockSandboxGetToolsDirCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxGetToolsDirCall) Do(f func() string) *MockSandboxGetToolsDirCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxGetToolsDirCall) DoAndReturn(f func() string) *MockSandboxGetToolsDirCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetWorkspaceDir mocks base method.
func (m *MockSandbox) GetWorkspaceDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetWorkspaceDir indicates an expected call of GetWorkspaceDir.
func (mr *MockSandboxMockRecorder) GetWorkspaceDir() *MockSandboxGetWorkspaceDirCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceDir", reflect.TypeOf((*MockSandbox)(nil).GetWorkspaceDir))
	return &MockSandboxGetWorkspaceDirCall{Call: call}
}

// MockSandboxGetWorkspaceDirCall wrap *gomock.Call
type MockSandboxGetWorkspaceDirCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxGetWorkspaceDirCall) Return(arg0 string) *MockSandboxGetWorkspaceDirCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxGetWorkspaceDirCall) Do(f func() string) *MockSandboxGetWorkspaceDirCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxGetWorkspaceDirCall) DoAndReturn(f func() string) *MockSandboxGetWorkspaceDirCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Paths mocks base method.
func (m *MockSandbox) Paths() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Paths")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Paths indicates an expected call of Paths.
func (mr *MockSandboxMockRecorder) Paths() *MockSandboxPathsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paths", reflect.TypeOf((*MockSandbox)(nil).Paths))
	return &MockSandboxPathsCall{Call: call}
}

// MockSandboxPathsCall wrap *gomock.Call
type MockSandboxPathsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxPathsCall) Return(arg0 []string) *MockSandboxPathsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxPathsCall) Do(f func() []string) *MockSandboxPathsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxPathsCall) DoAndReturn(f func() []string) *MockSandboxPathsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PullImage mocks base method.
func (m *MockSandbox) PullImage(ctx context.Context, image string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullImage", ctx, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// PullImage indicates an expected call of PullImage.
func (mr *MockSandboxMockRecorder) PullImage(ctx, image any) *MockSandboxPullImageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullImage", reflect.TypeOf((*MockSandbox)(nil).PullImage), ctx, image)
	return &MockSandboxPullImageCall{Call: call}
}

// MockSandboxPullImageCall wrap *gomock.Call
type MockSandboxPullImageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxPullImageCall) Return(arg0 error) *MockSandboxPullImageCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxPullImageCall) Do(f func(context.Context, string) error) *MockSandboxPullImageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxPullImageCall) DoAndReturn(f func(context.Context, string) error) *MockSandboxPullImageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RunContainer mocks base method.
func (m *MockSandbox) RunContainer(ctx context.Context, image string, entrypoint, cmd []string, env map[string]string, workdir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunContainer", ctx, image, entrypoint, cmd, env, workdir)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunContainer indicates an expected call of RunContainer.
func (mr *MockSandboxMockRecorder) RunContainer(ctx, image, entrypoint, cmd, env, workdir any) *MockSandboxRunContainerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunContainer", reflect.TypeOf((*MockSandbox)(nil).RunContainer), ctx, image, entrypoint, cmd, env, workdir)
	return &MockSandboxRunContainerCall{Call: call}
}

// MockSandboxRunContainerCall wrap *gomock.Call
type MockSandboxRunContainerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxRunContainerCall) Return(arg0 error) *MockSandboxRunContainerCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxRunContainerCall) Do(f func(context.Context, string, []string, []string, map[string]string, string) error) *MockSandboxRunContainerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxRunContainerCall) DoAndReturn(f func(context.Context, string, []string, []string, map[string]string, string) error) *MockSandboxRunContainerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSandboxRuntime is a mock of SandboxRuntime interface.
type MockSandboxRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockSandboxRuntimeMockRecorder
}

// MockSandboxRuntimeMockRecorder is the mock recorder for MockSandboxRuntime.
type MockSandboxRuntimeMockRecorder struct {
	mock *MockSandboxRuntime
}

// NewMockSandboxRuntime creates a new mock instance.
func NewMockSandboxRuntime(ctrl *gomock.Controller) *MockSandboxRuntime {
	mock := &MockSandboxRuntime{ctrl: ctrl}
	mock.recorder = &MockSandboxRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSandboxRuntime) EXPECT() *MockSandboxRuntimeMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSandboxRuntime) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSandboxRuntimeMockRecorder) Close() *MockSandboxRuntimeCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSandboxRuntime)(nil).Close))
	return &MockSandboxRuntimeCloseCall{Call: call}
}

// MockSandboxRuntimeCloseCall wrap *gomock.Call
type MockSandboxRuntimeCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxRuntimeCloseCall) Return(arg0 error) *MockSandboxRuntimeCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxRuntimeCloseCall) Do(f func() error) *MockSandboxRuntimeCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxRuntimeCloseCall) DoAndReturn(f func() error) *MockSandboxRuntimeCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Connect mocks base method.
func (m *MockSandboxRuntime) Connect(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockSandboxRuntimeMockRecorder) Connect(arg0 any) *MockSandboxRuntimeConnectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockSandboxRuntime)(nil).Connect), arg0)
	return &MockSandboxRuntimeConnectCall{Call: call}
}

// MockSandboxRuntimeConnectCall wrap *gomock.Call
type MockSandboxRuntimeConnectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxRuntimeConnectCall) Return(arg0 error) *MockSandboxRuntimeConnectCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxRuntimeConnectCall) Do(f func(context.Context) error) *MockSandboxRuntimeConnectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxRuntimeConnectCall) DoAndReturn(f func(context.Context) error) *MockSandboxRuntimeConnectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CopyFromSandbox mocks base method.
func (m *MockSandboxRuntime) CopyFromSandbox(arg0 context.Context, arg1 sandboxer.CopyFromSandboxRequest) (sandboxer.CopyFromSandboxResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFromSandbox", arg0, arg1)
	ret0, _ := ret[0].(sandboxer.CopyFromSandboxResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyFromSandbox indicates an expected call of CopyFromSandbox.
func (mr *MockSandboxRuntimeMockRecorder) CopyFromSandbox(arg0, arg1 any) *MockSandboxRuntimeCopyFromSandboxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFromSandbox", reflect.TypeOf((*MockSandboxRuntime)(nil).CopyFromSandbox), arg0, arg1)
	return &MockSandboxRuntimeCopyFromSandboxCall{Call: call}
}

// MockSandboxRuntimeCopyFromSandboxCall wrap *gomock.Call
type MockSandboxRuntimeCopyFromSandboxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxRuntimeCopyFromSandboxCall) Return(arg0 sandboxer.CopyFromSandboxResponse, arg1 error) *MockSandboxRuntimeCopyFromSandboxCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxRuntimeCopyFromSandboxCall) Do(f func(context.Context, sandboxer.CopyFromSandboxRequest) (sandboxer.CopyFromSandboxResponse, error)) *MockSandboxRuntimeCopyFromSandboxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxRuntimeCopyFromSandboxCall) DoAndReturn(f func(context.Context, sandboxer.CopyFromSandboxRequest) (sandboxer.CopyFromSandboxResponse, error)) *MockSandboxRuntimeCopyFromSandboxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CopyToSandbox mocks base method.
func (m *MockSandboxRuntime) CopyToSandbox(arg0 context.Context, arg1 sandboxer.CopyToSandboxRequest) (sandboxer.CopyToSandboxResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyToSandbox", arg0, arg1)
	ret0, _ := ret[0].(sandboxer.CopyToSandboxResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyToSandbox indicates an expected call of CopyToSandbox.
func (mr *MockSandboxRuntimeMockRecorder) CopyToSandbox(arg0, arg1 any) *MockSandboxRuntimeCopyToSandboxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyToSandbox", reflect.TypeOf((*MockSandboxRuntime)(nil).CopyToSandbox), arg0, arg1)
	return &MockSandboxRuntimeCopyToSandboxCall{Call: call}
}

// MockSandboxRuntimeCopyToSandboxCall wrap *gomock.Call
type MockSandboxRuntimeCopyToSandboxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxRuntimeCopyToSandboxCall) Return(arg0 sandboxer.CopyToSandboxResponse, arg1 error) *MockSandboxRuntimeCopyToSandboxCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxRuntimeCopyToSandboxCall) Do(f func(context.Context, sandboxer.CopyToSandboxRequest) (sandboxer.CopyToSandboxResponse, error)) *MockSandboxRuntimeCopyToSandboxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxRuntimeCopyToSandboxCall) DoAndReturn(f func(context.Context, sandboxer.CopyToSandboxRequest) (sandboxer.CopyToSandboxResponse, error)) *MockSandboxRuntimeCopyToSandboxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExecuteSandbox mocks base method.
func (m *MockSandboxRuntime) ExecuteSandbox(arg0 context.Context, arg1 sandboxer.ExecuteSandboxRequest) (sandboxer.ExecuteSandboxResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteSandbox", arg0, arg1)
	ret0, _ := ret[0].(sandboxer.ExecuteSandboxResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteSandbox indicates an expected call of ExecuteSandbox.
func (mr *MockSandboxRuntimeMockRecorder) ExecuteSandbox(arg0, arg1 any) *MockSandboxRuntimeExecuteSandboxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteSandbox", reflect.TypeOf((*MockSandboxRuntime)(nil).ExecuteSandbox), arg0, arg1)
	return &MockSandboxRuntimeExecuteSandboxCall{Call: call}
}

// MockSandboxRuntimeExecuteSandboxCall wrap *gomock.Call
type MockSandboxRuntimeExecuteSandboxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxRuntimeExecuteSandboxCall) Return(arg0 sandboxer.ExecuteSandboxResponse, arg1 error) *MockSandboxRuntimeExecuteSandboxCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxRuntimeExecuteSandboxCall) Do(f func(context.Context, sandboxer.ExecuteSandboxRequest) (sandboxer.ExecuteSandboxResponse, error)) *MockSandboxRuntimeExecuteSandboxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxRuntimeExecuteSandboxCall) DoAndReturn(f func(context.Context, sandboxer.ExecuteSandboxRequest) (sandboxer.ExecuteSandboxResponse, error)) *MockSandboxRuntimeExecuteSandboxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LaunchSandbox mocks base method.
func (m *MockSandboxRuntime) LaunchSandbox(arg0 context.Context, arg1 sandboxer.LaunchSandboxRequest) (sandboxer.LaunchSandboxResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LaunchSandbox", arg0, arg1)
	ret0, _ := ret[0].(sandboxer.LaunchSandboxResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LaunchSandbox indicates an expected call of LaunchSandbox.
func (mr *MockSandboxRuntimeMockRecorder) LaunchSandbox(arg0, arg1 any) *MockSandboxRuntimeLaunchSandboxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LaunchSandbox", reflect.TypeOf((*MockSandboxRuntime)(nil).LaunchSandbox), arg0, arg1)
	return &MockSandboxRuntimeLaunchSandboxCall{Call: call}
}

// MockSandboxRuntimeLaunchSandboxCall wrap *gomock.Call
type MockSandboxRuntimeLaunchSandboxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxRuntimeLaunchSandboxCall) Return(arg0 sandboxer.LaunchSandboxResponse, arg1 error) *MockSandboxRuntimeLaunchSandboxCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxRuntimeLaunchSandboxCall) Do(f func(context.Context, sandboxer.LaunchSandboxRequest) (sandboxer.LaunchSandboxResponse, error)) *MockSandboxRuntimeLaunchSandboxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxRuntimeLaunchSandboxCall) DoAndReturn(f func(context.Context, sandboxer.LaunchSandboxRequest) (sandboxer.LaunchSandboxResponse, error)) *MockSandboxRuntimeLaunchSandboxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TerminateSandbox mocks base method.
func (m *MockSandboxRuntime) TerminateSandbox(arg0 context.Context, arg1 sandboxer.TerminateSandboxRequest) (sandboxer.TerminateSandboxResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateSandbox", arg0, arg1)
	ret0, _ := ret[0].(sandboxer.TerminateSandboxResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TerminateSandbox indicates an expected call of TerminateSandbox.
func (mr *MockSandboxRuntimeMockRecorder) TerminateSandbox(arg0, arg1 any) *MockSandboxRuntimeTerminateSandboxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateSandbox", reflect.TypeOf((*MockSandboxRuntime)(nil).TerminateSandbox), arg0, arg1)
	return &MockSandboxRuntimeTerminateSandboxCall{Call: call}
}

// MockSandboxRuntimeTerminateSandboxCall wrap *gomock.Call
type MockSandboxRuntimeTerminateSandboxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxRuntimeTerminateSandboxCall) Return(arg0 sandboxer.TerminateSandboxResponse, arg1 error) *MockSandboxRuntimeTerminateSandboxCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxRuntimeTerminateSandboxCall) Do(f func(context.Context, sandboxer.TerminateSandboxRequest) (sandboxer.TerminateSandboxResponse, error)) *MockSandboxRuntimeTerminateSandboxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxRuntimeTerminateSandboxCall) DoAndReturn(f func(context.Context, sandboxer.TerminateSandboxRequest) (sandboxer.TerminateSandboxResponse, error)) *MockSandboxRuntimeTerminateSandboxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
