// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/sandboxer/mounter.go
//
// Generated by this command:
//
//	mockgen -typed -destination=sandboxer/mounter.go -source=../pkg/sandboxer/mounter.go
//

// Package mock_sandboxer is a generated GoMock package.
package mock_sandboxer

import (
	reflect "reflect"

	types "drassi.run/core/pkg/container/types"
	sandboxer "drassi.run/core/pkg/sandboxer"
	gomock "go.uber.org/mock/gomock"
)

// MockMounter is a mock of Mounter interface.
type MockMounter struct {
	ctrl     *gomock.Controller
	recorder *MockMounterMockRecorder
	isgomock struct{}
}

// MockMounterMockRecorder is the mock recorder for MockMounter.
type MockMounterMockRecorder struct {
	mock *MockMounter
}

// NewMockMounter creates a new mock instance.
func NewMockMounter(ctrl *gomock.Controller) *MockMounter {
	mock := &MockMounter{ctrl: ctrl}
	mock.recorder = &MockMounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMounter) EXPECT() *MockMounterMockRecorder {
	return m.recorder
}

// OverlayMounts mocks base method.
func (m *MockMounter) OverlayMounts(targetLayout sandboxer.Layout, coarse bool) []*types.Mount {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OverlayMounts", targetLayout, coarse)
	ret0, _ := ret[0].([]*types.Mount)
	return ret0
}

// OverlayMounts indicates an expected call of OverlayMounts.
func (mr *MockMounterMockRecorder) OverlayMounts(targetLayout, coarse any) *MockMounterOverlayMountsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OverlayMounts", reflect.TypeOf((*MockMounter)(nil).OverlayMounts), targetLayout, coarse)
	return &MockMounterOverlayMountsCall{Call: call}
}

// MockMounterOverlayMountsCall wrap *gomock.Call
type MockMounterOverlayMountsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMounterOverlayMountsCall) Return(arg0 []*types.Mount) *MockMounterOverlayMountsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMounterOverlayMountsCall) Do(f func(sandboxer.Layout, bool) []*types.Mount) *MockMounterOverlayMountsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMounterOverlayMountsCall) DoAndReturn(f func(sandboxer.Layout, bool) []*types.Mount) *MockMounterOverlayMountsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RuntimeMounts mocks base method.
func (m *MockMounter) RuntimeMounts(targetLayout sandboxer.Layout) []*types.Mount {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RuntimeMounts", targetLayout)
	ret0, _ := ret[0].([]*types.Mount)
	return ret0
}

// RuntimeMounts indicates an expected call of RuntimeMounts.
func (mr *MockMounterMockRecorder) RuntimeMounts(targetLayout any) *MockMounterRuntimeMountsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RuntimeMounts", reflect.TypeOf((*MockMounter)(nil).RuntimeMounts), targetLayout)
	return &MockMounterRuntimeMountsCall{Call: call}
}

// MockMounterRuntimeMountsCall wrap *gomock.Call
type MockMounterRuntimeMountsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMounterRuntimeMountsCall) Return(arg0 []*types.Mount) *MockMounterRuntimeMountsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMounterRuntimeMountsCall) Do(f func(sandboxer.Layout) []*types.Mount) *MockMounterRuntimeMountsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMounterRuntimeMountsCall) DoAndReturn(f func(sandboxer.Layout) []*types.Mount) *MockMounterRuntimeMountsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
