// Code generated by MockGen. DO NOT EDIT.
// Source: ../pkg/sandboxer/sandbox.go
//
// Generated by this command:
//
//	mockgen -typed -destination=sandboxer/sandbox.go -source=../pkg/sandboxer/sandbox.go
//

// Package mock_sandboxer is a generated GoMock package.
package mock_sandboxer

import (
	context "context"
	io "io"
	fs "io/fs"
	reflect "reflect"

	sandboxer "drassi.run/core/pkg/sandboxer"
	stream "drassi.run/core/pkg/stream"
	gomock "go.uber.org/mock/gomock"
)

// MockSandbox is a mock of Sandbox interface.
type MockSandbox struct {
	ctrl     *gomock.Controller
	recorder *MockSandboxMockRecorder
	isgomock struct{}
}

// MockSandboxMockRecorder is the mock recorder for MockSandbox.
type MockSandboxMockRecorder struct {
	mock *MockSandbox
}

// NewMockSandbox creates a new mock instance.
func NewMockSandbox(ctrl *gomock.Controller) *MockSandbox {
	mock := &MockSandbox{ctrl: ctrl}
	mock.recorder = &MockSandboxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSandbox) EXPECT() *MockSandboxMockRecorder {
	return m.recorder
}

// CopyIn mocks base method.
func (m *MockSandbox) CopyIn(ctx context.Context, reader io.Reader, dst string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyIn", ctx, reader, dst)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyIn indicates an expected call of CopyIn.
func (mr *MockSandboxMockRecorder) CopyIn(ctx, reader, dst any) *MockSandboxCopyInCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyIn", reflect.TypeOf((*MockSandbox)(nil).CopyIn), ctx, reader, dst)
	return &MockSandboxCopyInCall{Call: call}
}

// MockSandboxCopyInCall wrap *gomock.Call
type MockSandboxCopyInCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxCopyInCall) Return(arg0 error) *MockSandboxCopyInCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxCopyInCall) Do(f func(context.Context, io.Reader, string) error) *MockSandboxCopyInCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxCopyInCall) DoAndReturn(f func(context.Context, io.Reader, string) error) *MockSandboxCopyInCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CopyOut mocks base method.
func (m *MockSandbox) CopyOut(ctx context.Context, src string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyOut", ctx, src)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyOut indicates an expected call of CopyOut.
func (mr *MockSandboxMockRecorder) CopyOut(ctx, src any) *MockSandboxCopyOutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyOut", reflect.TypeOf((*MockSandbox)(nil).CopyOut), ctx, src)
	return &MockSandboxCopyOutCall{Call: call}
}

// MockSandboxCopyOutCall wrap *gomock.Call
type MockSandboxCopyOutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxCopyOutCall) Return(arg0 io.ReadCloser, arg1 error) *MockSandboxCopyOutCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxCopyOutCall) Do(f func(context.Context, string) (io.ReadCloser, error)) *MockSandboxCopyOutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxCopyOutCall) DoAndReturn(f func(context.Context, string) (io.ReadCloser, error)) *MockSandboxCopyOutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Execute mocks base method.
func (m *MockSandbox) Execute(ctx context.Context, cmd, path []string, env map[string]string, workdir string, streams *stream.Streams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, cmd, path, env, workdir, streams)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockSandboxMockRecorder) Execute(ctx, cmd, path, env, workdir, streams any) *MockSandboxExecuteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockSandbox)(nil).Execute), ctx, cmd, path, env, workdir, streams)
	return &MockSandboxExecuteCall{Call: call}
}

// MockSandboxExecuteCall wrap *gomock.Call
type MockSandboxExecuteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxExecuteCall) Return(arg0 error) *MockSandboxExecuteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxExecuteCall) Do(f func(context.Context, []string, []string, map[string]string, string, *stream.Streams) error) *MockSandboxExecuteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxExecuteCall) DoAndReturn(f func(context.Context, []string, []string, map[string]string, string, *stream.Streams) error) *MockSandboxExecuteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Layout mocks base method.
func (m *MockSandbox) Layout() *sandboxer.Layout {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Layout")
	ret0, _ := ret[0].(*sandboxer.Layout)
	return ret0
}

// Layout indicates an expected call of Layout.
func (mr *MockSandboxMockRecorder) Layout() *MockSandboxLayoutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Layout", reflect.TypeOf((*MockSandbox)(nil).Layout))
	return &MockSandboxLayoutCall{Call: call}
}

// MockSandboxLayoutCall wrap *gomock.Call
type MockSandboxLayoutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxLayoutCall) Return(arg0 *sandboxer.Layout) *MockSandboxLayoutCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxLayoutCall) Do(f func() *sandboxer.Layout) *MockSandboxLayoutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxLayoutCall) DoAndReturn(f func() *sandboxer.Layout) *MockSandboxLayoutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stat mocks base method.
func (m *MockSandbox) Stat(ctx context.Context, path string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", ctx, path)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockSandboxMockRecorder) Stat(ctx, path any) *MockSandboxStatCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockSandbox)(nil).Stat), ctx, path)
	return &MockSandboxStatCall{Call: call}
}

// MockSandboxStatCall wrap *gomock.Call
type MockSandboxStatCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxStatCall) Return(arg0 fs.FileInfo, arg1 error) *MockSandboxStatCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxStatCall) Do(f func(context.Context, string) (fs.FileInfo, error)) *MockSandboxStatCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxStatCall) DoAndReturn(f func(context.Context, string) (fs.FileInfo, error)) *MockSandboxStatCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Terminate mocks base method.
func (m *MockSandbox) Terminate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Terminate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Terminate indicates an expected call of Terminate.
func (mr *MockSandboxMockRecorder) Terminate(ctx any) *MockSandboxTerminateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Terminate", reflect.TypeOf((*MockSandbox)(nil).Terminate), ctx)
	return &MockSandboxTerminateCall{Call: call}
}

// MockSandboxTerminateCall wrap *gomock.Call
type MockSandboxTerminateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSandboxTerminateCall) Return(arg0 error) *MockSandboxTerminateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSandboxTerminateCall) Do(f func(context.Context) error) *MockSandboxTerminateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSandboxTerminateCall) DoAndReturn(f func(context.Context) error) *MockSandboxTerminateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
